(function(){
 let consoleView=null,opening=false,cinema=null,eventId='',music=null,impact=null,hum=null,frame=null,diceStarted=false;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const host=()=>{let d=document;try{while(d.defaultView.frameElement)d=d.defaultView.parent.document;}catch{}return d;};
 function style(doc){if(doc.querySelector('[data-cleanser-style]'))return;const l=doc.createElement('link');l.rel='stylesheet';l.href=new URL('cleanser.css',location.href).href;l.dataset.cleanserStyle='';doc.head.append(l);}
 // Every visual phase is sampled from server-owned active seconds, never wall time.
 function stationChargeVisual(s,complete=false,reduced=false){
  const charging=s.phase==='charging',elapsed=charging?Math.max(0,Math.min(120,120-(Number(s.remaining)||0))):complete?120:0;
  const progress=elapsed/120,angle=reduced?0:elapsed*23,amplitude=2+Math.pow(progress,2)*34;
  const wave=Array.from({length:101},(_,i)=>{const x=i*6,phase=reduced?0:elapsed*5;return `${i?'L':'M'}${x},${(42+Math.sin(i*.46+phase)*Math.sin(i*.13-phase*.3)*amplitude).toFixed(2)}`;}).join(' ');
  return {charging,elapsed,progress,angle,wave,critical:charging&&s.remaining<=5&&s.remaining>0,remaining:Math.max(0,Math.ceil(Number(s.remaining)||0))};
 }
 function stationTargets(room,owner){
  const planets=(room.spaceObjects||[]).filter(o=>o.kind==='planet'&&!o.destroyedAt&&!o.collectedBy);
  // Contact Hull is a rounded condition, not HP: an empty icon can still be a living target.
  const ships=(room.starships||[]).filter(s=>s.id!==owner.id&&!s.isDrone&&!s.isProbe&&!s.isMissile&&!(!s.contactOnly&&!s.analyzedContact&&Number.isFinite(s.currentHullHp)&&s.currentHullHp<=0)&&!s.destroyedAt&&!s.escapedAt&&!s.dockedIn&&!window.SAShipMap?.cloaked?.(s)&&s.ship?.warpState?.phase!=='traveling'&&owner.sensorState?.contacts?.[s.id]?.level==='detected').map(s=>({...s,kind:'starship',name:s.title}));
  const origin=(room.shipPositions||[]).find(p=>p.id===owner.id),range=window.SAShipMap.sensorStats(owner).range;
  return [...planets,...ships].filter(t=>{const point=t.kind==='starship'?(room.shipPositions||[]).find(p=>p.id===t.id):t;return origin&&point&&window.SAShipDistances.hexDistance(origin,point)<=range+1e-8;});
 }
 function stationStyle(doc){if(doc.querySelector('[data-cleanser-station-style]'))return;const l=doc.createElement('link');l.rel='stylesheet';l.href=new URL('cleanser-station.css',location.href).href;l.dataset.cleanserStationStyle='';doc.head.append(l);}
 async function open(unit,sicId){
  if(consoleView||opening)return;opening=true;
  const b=window.SACombatBridge,doc=host(),access=window.SAStationAccess.access(b.state(),unit,sicId);if(!access?.definition.planetaryCleanser){opening=false;return;}
  style(doc);stationStyle(doc);const v=consoleView=doc.createElement('dialog');v.className='cleanser-console cleanser-station';v.dataset.operatorId=unit.id;v.dataset.standaloneConsole='true';v.setAttribute('aria-label','Planetary Cleanser console');
  const pips=Array.from({length:60},(_,i)=>`<path transform="rotate(${i*6} 400 238)" d="M400 63v${i%5?6:13}"/>`).join('');
  const symbols=Array.from({length:24},(_,i)=>`<g data-reactor-die="${i}" class="cleanser-reactor-die"><path d="M0 -9 8.6 -2.8 5.3 7.3 -5.3 7.3 -8.6 -2.8Z M0 -9 0 -3 5.5 1.8 3.4 6.5 M0 -3 -5.5 1.8 -3.4 6.5 M5.5 1.8 -5.5 1.8"/></g>`).join('');
  const sparks=Array.from({length:12},(_,i)=>`<path data-reactor-spark="${i}" class="cleanser-reactor-spark" d="M0 0 12 -7 17 3 30 -12 39 -7 52 -22"/>`).join('');
  v.innerHTML=`<header class="cleanser-station-header"><div class="cleanser-station-title"><small>DEVASTATION SYSTEM / ${esc(unit.characterName)}</small><h2>PLANETARY CLEANSER</h2></div><div data-selector></div><button data-mute type="button">Sound</button><button data-close type="button">Combat View</button></header>
   <div class="cleanser-station-body"><section class="cleanser-reactor" aria-label="Weapon charging chamber"><div class="cleanser-reactor-topline"><span>PHAZON CONTAINMENT CHAMBER</span><strong data-clock-status>STANDBY</strong></div><img class="cleanser-reactor-hardware" src="${new URL('sic-art-planetary-cleanser.webp',location.href).href}" alt="Planetary Cleanser reactor machinery"><div class="cleanser-reactor-glow"></div>
   <svg class="cleanser-reactor-svg" viewBox="0 0 800 470" aria-hidden="true"><g class="cleanser-reactor-grid"><path d="M0 238H800M400 0V470M210 48 590 428M210 428 590 48"/><circle cx="400" cy="238" r="204"/><circle cx="400" cy="238" r="157"/></g><g class="cleanser-reactor-pips">${pips}</g><g data-ring-outer class="cleanser-reactor-ring"><circle cx="400" cy="238" r="188" stroke-dasharray="208 55 22 55"/><path d="M400 38v24m0 352v24M200 238h24m352 0h24"/></g><g data-ring-inner class="cleanser-reactor-ring inner"><circle cx="400" cy="238" r="142" stroke-dasharray="130 45"/><circle cx="400" cy="238" r="125" stroke-dasharray="2 16"/></g><circle class="cleanser-reactor-charge-track" cx="400" cy="238" r="166"/><circle data-reactor-charge class="cleanser-reactor-charge" pathLength="100" cx="400" cy="238" r="166" transform="rotate(-90 400 238)" stroke-dasharray="0 100"/>${symbols}<g class="cleanser-reactor-sparks">${sparks}</g></svg>
   <div class="cleanser-reactor-readout"><small data-phase>STANDBY</small><strong data-countdown-number>02:00</strong><span data-countdown>ACTIVE SECONDS UNTIL CLEANSING</span></div><div class="cleanser-reactor-caption"><span data-containment>CONTAINMENT STABLE</span><b data-charge-percent>0%</b></div><div class="cleanser-waveform"><div><small>ENERGY SIGNATURE</small><span data-wave-label>REACTOR IDLE</span></div><svg viewBox="0 0 600 84" preserveAspectRatio="none" aria-hidden="true"><path d="M0 42H600" class="cleanser-wave-baseline"/><path data-waveform d="M0 42H600"/></svg></div></section>
   <section class="cleanser-target-console"><div class="cleanser-target-heading"><small>TARGET SOLUTION</small><span data-target-type>NO TARGET</span></div><label class="cleanser-target-select">Designate target<select data-target aria-label="Cleanser target"></select></label><div class="cleanser-target-preview"><img data-target-image alt=""><div><strong data-target-name>No target designated</strong><span data-target-position></span><span data-target-displacement></span></div><svg viewBox="0 0 100 100" aria-hidden="true"><path d="M15 35V15H35M65 15H85V35M85 65V85H65M35 85H15V65M50 5V25M50 75V95M5 50H25M75 50H95"/></svg></div><p class="cleanser-target-rule" data-target-rule>Choose a planet or a detected starship.</p><div class="cleanser-power-readouts"><div><small>DARK PHAZON</small><strong data-phazon>0</strong></div><div><small>POWER ROUTING</small><strong data-power>STANDBY</strong></div><div><small>MASKING</small><strong data-masking>—</strong></div></div><progress data-progress max="120" value="0" aria-label="Cleanser charge"></progress><div class="cleanser-charge-actions"><button type="button" data-charge>Begin 120-second Charge</button><button type="button" data-abort hidden>Abort Charge</button></div><p class="cleanser-blast-warning">Blast hits every ship inside 3 hexes of the aim point, including allies. Ships 3 or more hexes away are safe.</p><p data-reason></p><output data-error role="alert"></output><button type="button" data-retry hidden>Retry Command</button><details class="cleanser-charge-report"><summary>Weapon log &amp; operation</summary><p>Charging consumes 1 Dark Phazon, diverts all AU and sets Masking to 0. The fixed aim hex is chosen when charging begins.</p><p data-report></p></details></section></div>
   <footer class="cleanser-station-footer"><div class="cleanser-operator"><svg viewBox="0 0 72 72" aria-hidden="true"><circle class="cleanser-atb-track" cx="36" cy="36" r="29"/><circle data-atb-ring pathLength="100" cx="36" cy="36" r="29" transform="rotate(-90 36 36)" stroke-dasharray="0 100"/><text data-atb-percent x="36" y="40" text-anchor="middle">0%</text></svg><div><small>OPERATOR ATB · ${esc(unit.characterName)}</small><strong data-operator-state>STANDBY</strong><span data-command-time></span></div></div><div class="cleanser-footer-actions"><button data-hold type="button">Hold</button><button data-leave type="button">Leave Console</button></div></footer>`;
  doc.body.append(v);v.showModal();let busy=false,pending=null,targetKey='',targetImageKey='';const nodes=new Map(),get=s=>{if(!nodes.has(s))nodes.set(s,v.querySelector(s));return nodes.get(s);},reduced=doc.defaultView.matchMedia?.('(prefers-reduced-motion: reduce)');
  function draw(){
   const room=b.state(),person=room.units.find(u=>u.id===unit.id),live=window.SAStationAccess.access(room,person,sicId);
   if(!live||!person){v.close();return;}const ship=live.ship,s=ship.ship.cleanserState||{},charging=s.phase==='charging',targets=stationTargets(room,ship),event=room.planetaryEvent?.shipId===ship.id?room.planetaryEvent:null,complete=['awaitingRoll','rolling','result','firing'].includes(event?.phase);
   const lockedId=charging?s.targetId:complete?event.targetId:null,options=lockedId&&!targets.some(t=>t.id===lockedId)?[...targets,{id:lockedId,name:(charging?s.targetName:event.targetName)||'Locked target',kind:charging?s.targetKind:event.targetKind}]:targets;
   const key=JSON.stringify(options.map(t=>[t.id,t.name,t.kind]));if(key!==targetKey){const old=lockedId||get('[data-target]').value;get('[data-target]').innerHTML=options.length?options.map(t=>`<option value="${esc(t.id)}">${esc(t.name)} · ${t.kind==='starship'?'Starship':'Planet'}</option>`).join(''):'<option value="">No eligible targets</option>';if(options.some(t=>t.id===old))get('[data-target]').value=old;targetKey=key;}
   const mineral=['Dark Phazon','Dark Phaeon'].reduce((n,k)=>n+(ship.ship.minerals?.[k]||0),0),ready=room.activeId===unit.id&&!room.rollPaused&&!person.delayedAction&&!person.delayTimer&&!person.timedAction&&!person.consoleHold;
   const reason=room.practice?'Deploy this ship and a target in an encounter.':live.blocked?'Console is unavailable.':complete?'Resolve the damage roll to fire.':s.cooldown>0?'Weapon cooling down.':!ready?'Waiting for your turn.':!targets.length?'Place a planet or detect a starship first.':mineral<1?'Requires 1 Dark Phazon.':live.item.impaired||live.item.impairmentPoints?'Repair the weapon first.':ship.auState?.maximum<1?'Requires a working AU supply.':'';
   const visual=stationChargeVisual(s,complete,Boolean(reduced?.matches)),clockRunning=room.running&&!room.hardPaused&&!room.holdPaused&&!room.pausedForTurn&&!room.rollPaused&&!room.attackResolution&&!room.itemResolution;
   v.dataset.charging=String(charging);v.dataset.critical=String(visual.critical);v.dataset.reducedMotion=String(Boolean(reduced?.matches));v.style.setProperty('--reactor-power',visual.progress);v.style.setProperty('--operator-color',person.color||'#75ffc4');
   get('[data-phase]').textContent=charging?'CHARGING':complete?'CHARGE COMPLETE':s.cooldown>0?'COOLING DOWN':'STANDBY';get('[data-progress]').value=visual.elapsed;
   get('[data-countdown-number]').textContent=complete?'READY':charging?`${String(Math.floor(visual.remaining/60)).padStart(2,'0')}:${String(visual.remaining%60).padStart(2,'0')}`:s.cooldown>0?Math.ceil(s.cooldown/60)+'m':'02:00';
   get('[data-countdown]').textContent=charging?'ACTIVE SECONDS UNTIL CLEANSING':complete?'AWAITING DAMAGE CONFIRMATION':s.cooldown>0?'COOLDOWN REMAINING':'ACTIVE SECONDS TO FULL CHARGE';get('[data-clock-status]').textContent=charging?(clockRunning?'CHARGE ACTIVE':'CHARGE PAUSED'):complete?'CONTAINMENT LOCKED':'REACTOR STANDBY';
   get('[data-containment]').textContent=visual.critical?'FINAL CONTAINMENT RELEASE':visual.progress>.7?'CONTAINMENT UNDER EXTREME LOAD':charging?'PHAZON COMPRESSION ACTIVE':'CONTAINMENT STABLE';get('[data-charge-percent]').textContent=Math.floor(visual.progress*100)+'%';get('[data-wave-label]').textContent=visual.critical?'CRITICAL ENERGY DENSITY':charging?'ENERGY ACCUMULATING':'REACTOR IDLE';
   get('[data-ring-outer]').setAttribute('transform',`rotate(${visual.angle} 400 238)`);get('[data-ring-inner]').setAttribute('transform',`rotate(${-visual.angle*1.4} 400 238)`);get('[data-reactor-charge]').setAttribute('stroke-dasharray',`${visual.progress*100} 100`);get('[data-waveform]').setAttribute('d',visual.wave);
   for(let i=0;i<24;i++){const phase=(visual.elapsed*.11+i/24)%1,angle=(i*137.5+(reduced?.matches?0:visual.elapsed*19))*Math.PI/180,radius=reduced?.matches?190:205-phase*116,x=400+Math.cos(angle)*radius,y=238+Math.sin(angle)*radius;const die=get(`[data-reactor-die="${i}"]`);die.setAttribute('transform',`translate(${x.toFixed(2)} ${y.toFixed(2)}) rotate(${reduced?.matches?0:visual.angle+i*17}) scale(${.65+visual.progress*.5})`);die.setAttribute('opacity',charging?String((.2+.8*visual.progress)*(1-phase*.65)):complete?'.55':'0');}
   for(let i=0;i<12;i++){const angle=i*30+(reduced?.matches?0:visual.elapsed*31),r=112+Math.sin(visual.elapsed*17+i)*20;const spark=get(`[data-reactor-spark="${i}"]`);spark.setAttribute('transform',`translate(${400+Math.cos(angle*Math.PI/180)*r} ${238+Math.sin(angle*Math.PI/180)*r}) rotate(${angle})`);spark.setAttribute('opacity',visual.critical&&!reduced?.matches&&Math.sin(visual.elapsed*22+i*3)>.2?'.9':'0');}
   const targetId=charging?s.targetId:complete?event.targetId:get('[data-target]').value,target=targets.find(t=>t.id===targetId),kind=charging?s.targetKind:complete?event.targetKind:target?.kind,isShip=kind==='starship'||target?.kind==='starship',aim=(charging?s.aimHex:complete?event.aimHex:null),point=target&&(isShip?(room.shipPositions||[]).find(p=>p.id===target.id):target),format=p=>p&&Number.isFinite(p.q)&&Number.isFinite(p.r)?`Q ${Number(p.q.toFixed(1))} / R ${Number(p.r.toFixed(1))}`:'';
   get('[data-target-name]').textContent=target?.name||(charging?s.targetName:complete?event.targetName:'')||'No target designated';get('[data-target-type]').textContent=isShip?'STARSHIP':target?'PLANET':charging?'FIXED AIM':'NO TARGET';get('[data-target-position]').textContent=aim?'LOCKED AIM · '+format(aim):point?'CURRENT HEX · '+format(point):'';
   const displacement=isShip&&aim&&point?window.SAShipDistances?.hexDistance?.(aim,point):null;get('[data-target-displacement]').textContent=isShip&&aim?(Number.isFinite(displacement)?`${displacement.toFixed(1)} / 3 hexes from aim${displacement>=3?' · CLEAR OF BLAST':''}`:'Contact lost · aim remains fixed'):'';get('[data-target-displacement]').dataset.escaped=String(Number.isFinite(displacement)&&displacement>=3);
   get('[data-target-rule]').textContent=isShip?'Fixed aim: a ship 3 or more hexes away when charging completes escapes the blast.':'Destroys the selected planet and hits ships less than 3 hexes from the fixed aim point. Shields absorb a hit without overflow to Hull.';
   const image=get('[data-target-image]'),variant=['ocean','desert','ice','volcanic'].includes(target?.variant)?target.variant:'ocean',rank=target&&isShip?window.SAShipMap?.scaleRank?.(target)||s.targetMapRank||1:s.targetMapRank||1;image.hidden=!target&&!charging&&!complete;const art=isShip?`sic-art-starship-rank-${Math.min(5,Math.max(1,rank))}.webp`:`planet-${variant}.webp`;if(art!==targetImageKey){image.src=new URL(art,location.href).href;targetImageKey=art;}
   get('[data-phazon]').textContent=String(mineral);get('[data-power]').textContent=charging?'ALL AU DIVERTED':Math.floor(ship.auState?.available||0)+' AU';get('[data-masking]').textContent=charging?'0':String(window.SAShipMap?.masking?.(ship)??'—');
   get('[data-charge]').hidden=charging;get('[data-abort]').hidden=!charging;get('[data-charge]').disabled=busy||!!reason;get('[data-abort]').disabled=busy||!ready;get('[data-target]').disabled=charging||complete||busy;
   get('[data-reason]').textContent=charging?(clockRunning?'Charge follows active ATB time.':'ATB paused · reactor charge is preserved.')+(ready?'':' Abort is available on your turn.'):reason;get('[data-report]').textContent=s.lastReport||'No discharge recorded.';
   get('[data-retry]').hidden=!pending||busy;get('[data-retry]').disabled=busy;get('[data-hold]').textContent=person.consoleHold?'Resume':'Hold';get('[data-hold]').disabled=busy||room.practice||(!ready&&!person.consoleHold);get('[data-leave]').disabled=busy||!ready||room.practice;get('[data-mute]').textContent=b.soundEnabled()?'Mute sounds':'Enable sounds';
   const percent=Math.max(0,Math.min(100,(Number(person.atb)||0)/(Number(room.threshold)||100)*100)),command=room.command?.unitId===unit.id?room.command:null;get('[data-atb-ring]').setAttribute('stroke-dasharray',`${percent} 100`);get('[data-atb-percent]').textContent=Math.floor(percent)+'%';get('[data-operator-state]').textContent=person.consoleHold?'HOLDING AT 99%':ready?'YOUR TURN':person.delayedAction?'PROCESSING COMMAND':room.practice?'OUT OF COMBAT':'AWAITING YOUR TURN';get('[data-command-time]').textContent=command?(command.expired?'Command window ended':Math.ceil(command.remaining)+' seconds in command window'):charging?'Weapon charge continues independently of your ATB.':'';
  }
  async function send(kind){if(busy)return;if(!pending&&!b.confirmGmPlayerAction(unit,kind))return;pending||={id:unit.id,starshipId:access.ship.id,sicId,kind,targetId:get('[data-target]').value,receipt:crypto.randomUUID()};busy=true;draw();try{await b.utilityAction(pending);pending=null;get('[data-error]').textContent='';}catch(e){if(e.status>=400&&e.status<500)pending=null;get('[data-error]').textContent=e.message;}finally{busy=false;draw();}}
  get('[data-target]').onchange=draw;get('[data-retry]').onclick=()=>send(pending?.kind);get('[data-charge]').onclick=()=>send('cleanser-charge');get('[data-abort]').onclick=()=>send('cleanser-abort');get('[data-close]').onclick=()=>{window.SAShipNavigationUI.remember(unit);v.close();};get('[data-mute]').onclick=()=>{b.toggleSound();draw();};
  get('[data-hold]').onclick=()=>window.SAShipNavigationUI.toggleHold(b.state().units.find(u=>u.id===unit.id)).catch(e=>get('[data-error]').textContent=e.message);get('[data-leave]').onclick=()=>{v.close();window.SACombatMap.openMove(b.state().units.find(u=>u.id===unit.id));};
  if(access.controlled){const off=doc.createElement('button');off.textContent='Shut Down Captured SIC';off.onclick=async()=>{const session=b.state().units.find(u=>u.id===unit.id)?.hackingSessions?.find(s=>s.control&&s.connected&&s.targetId===access.ship.id&&s.sicId===sicId);if(!session){get('[data-error]').textContent='Return to Hacking to shut down the captured system.';return;}try{await b.action({action:'hackingCommand',id:unit.id,kind:'off',sessionId:session.id,sicId:session.moduleId,receipt:crypto.randomUUID()},'resolve',{throwOnError:true});v.close();}catch(error){get('[data-error]').textContent=error.message;}};get('[data-close]').before(off);}
  window.SAShipNavigationUI.mountSelector(get('[data-selector]'),unit,sicId,()=>v.close());const timer=setInterval(draw,60);draw();v.addEventListener('close',()=>{clearInterval(timer);v.remove();consoleView=null;},{once:true});opening=false;
 }
 function closeCinema(){music?.pause();music=null;impact?.pause();impact=null;frame=null;diceStarted=false;cinema?.remove();cinema=null;}
 let rollView=null,rollFrame=null,rollKey='',rollReady=false,rollSignature='',rollError=null,rollTakeover=null,rollReload=null,loadDeadline=0,rollBusy=false,hiddenRoll='';
 function closeRoll(){rollView?.remove();rollView=rollFrame=null;rollReady=false;rollSignature='';rollBusy=false;}
 const canResolve=(b,e)=>b.mode()==='gm'?e.rollController==='gm'||!b.state().units.some(u=>u.id===e.operatorId&&u.team==='pc'):e.rollController!=='gm'&&b.myUnitId()===e.operatorId;
 function rollPayload(b,e){return {type:'sa-shared-damage-state',sharedDamage:true,rollId:e.id,name:'Planetary Cleanser',title:'Planetary Cleanser damage: 20,000D12',phase:e.phase,canResolve:canResolve(b,e),sides:Array(96).fill(12),values:Array.from({length:96},(_,i)=>1+((e.dice?.[i%3]||1)-1+Math.floor(i/3))%12),score:e.damage,damage:true,immediateResult:true,exertionAvailable:0};}
 async function sendDamage(kind){
  if(rollBusy)return;const b=window.SACombatBridge,e=b.state().planetaryEvent;if(!e)return;rollBusy=true;
  try{await b.action({action:'cleanserDamage',id:e.operatorId,eventId:e.id,kind},'resolve',{throwOnError:true});if(rollError)rollError.replaceChildren();rollSignature='';}
  catch(error){if(rollError){rollError.textContent=error.message+' ';const retry=rollError.ownerDocument.createElement('button');retry.textContent='Retry';retry.onclick=()=>sendDamage(kind);rollError.append(retry);}}
  finally{rollBusy=false;}
 }
 function damagePrompt(b,e,doc){
  if(!['awaitingRoll','rolling','result'].includes(e?.phase)){hiddenRoll='';doc.querySelector('[data-resume-cleanser-roll]')?.remove();closeRoll();return;}
  if(hiddenRoll===e.id+':'+e.phase){if(!doc.querySelector('[data-resume-cleanser-roll]')){const resume=doc.createElement('button');resume.dataset.resumeCleanserRoll='';resume.textContent='View Cleanser Damage Roll';resume.style.cssText='position:fixed;top:12px;right:12px;z-index:10001;background:#34224b;color:white;padding:14px';resume.onclick=()=>{hiddenRoll='';resume.remove();};doc.body.append(resume);}return;}
  doc.querySelector('[data-resume-cleanser-roll]')?.remove();
  if(!rollView||rollKey!==e.id){
   closeRoll();rollKey=e.id;rollView=doc.createElement('dialog');rollView.setAttribute('aria-label','Planetary Cleanser damage roll');
   rollView.style.cssText='position:fixed;inset:0;width:100vw;height:100dvh;max-width:none;max-height:none;margin:0;padding:0;border:0;background:transparent';
   rollFrame=doc.createElement('iframe');rollFrame.title='Planetary Cleanser damage';rollFrame.style.cssText='width:100%;height:100%;border:0;background:transparent';
   rollError=doc.createElement('div');rollError.setAttribute('role','alert');rollError.style.cssText='position:absolute;bottom:12px;left:20%;color:#fff;background:#142a36';
   const controls=doc.createElement('div');controls.style.cssText='position:absolute;top:8px;right:12px;display:flex;gap:6px';
   rollTakeover=doc.createElement('button');rollTakeover.textContent='GM: Resolve this roll';rollTakeover.onclick=()=>sendDamage('takeover');
   rollReload=doc.createElement('button');rollReload.textContent='Retry Loading Dice';
   const reload=()=>{rollReady=false;rollSignature='';loadDeadline=Date.now()+5000;rollFrame.src=new URL('character.html?shipRoll=1',location.href);};
   rollReload.onclick=reload;const back=doc.createElement("button");back.textContent="Return to Combat";back.onclick=()=>{hiddenRoll=e.id+":"+b.state().planetaryEvent.phase;closeRoll();};controls.append(back,rollTakeover,rollReload);rollView.append(rollFrame,controls,rollError);rollView.addEventListener('cancel',event=>{event.preventDefault();hiddenRoll=e.id+':'+b.state().planetaryEvent.phase;closeRoll();});doc.body.append(rollView);rollView.showModal();reload();
  }
  rollTakeover.hidden=b.mode()!=='gm'||canResolve(b,e);rollReload.hidden=rollReady||Date.now()<loadDeadline;
  const signature=JSON.stringify([e.phase,e.rollController,e.damage,canResolve(b,e)]);
  if(rollReady&&signature!==rollSignature){rollSignature=signature;rollFrame.contentWindow.postMessage(rollPayload(b,e),location.origin);}
 }
 function tick(){
  const b=window.SACombatBridge,s=b?.state();if(!s)return;const doc=host(),event=s.planetaryEvent,timeline=window.SACleanserTimeline.forEvent(event);
  const charging=s.starships?.some(ship=>ship.ship?.cleanserState?.phase==='charging');
  if(charging&&!hum){hum=new Audio(new URL('cleanser-charge.wav',location.href));hum.loop=true;hum.volume=.25;}
  if(hum){if(!charging){hum.pause();hum=null;}else if(b.soundEnabled()&&!doc.hidden&&s.running&&!s.hardPaused&&!s.pausedForTurn&&!s.holdPaused&&!s.rollPaused){if(hum.paused)hum.play().catch(()=>{});}else hum.pause();}
  damagePrompt(b,event,doc);
  if(event?.phase!=='firing'){closeCinema();return;}
  if(!cinema||eventId!==event.id){
   closeCinema();eventId=event.id;style(doc);cinema=doc.createElement('dialog');cinema.className='cleanser-cinema';cinema.setAttribute('aria-label','Planetary Cleanser firing cinematic');
   const scene=window.SACleanserImpact.presentation(event);cinema.dataset.targetKind=scene.kind;cinema.dataset.outcome=scene.outcome;
   const remains=scene.showRemains?(scene.remainsArt?`<img class="cleanser-remains" src="${new URL(scene.remainsArt,location.href)}" alt="${esc(scene.remainsAlt)}">`:`<svg class="cleanser-remains cleanser-ship-wreck" viewBox="-100 -100 200 200" role="img" aria-label="Destroyed starship debris">${Array.from({length:24},(_,i)=>`<path d="M-5 -4L6 -2L3 6L-6 3Z" fill="${i%3?'#747e89':'#c18460'}" transform="translate(${Math.sin(i*13.37)*75} ${Math.cos(i*4.91)*60}) rotate(${i*137.5})"/>`).join('')}</svg>`):'';
   const fragments=scene.showFragments?Array.from({length:36},(_,i)=>`<i class="cleanser-fragment" style="--angle:${i*137.5}deg;--travel:${120+i%9*27}px;--fragment:${5+i%7*3}px;--spin:${i*47}deg"></i>`).join(''):'';
   cinema.innerHTML=`<div class="cleanser-stars"></div><div class="cleanser-vignette"></div><header><small>${esc(event.shipName)} / PLANETARY CLEANSER</small><h1>${esc(event.targetName)}</h1><p data-stage>FINAL CONTAINMENT RELEASE</p></header><div class="cleanser-stage"><div class="cleanser-muzzle"></div><div class="cleanser-beam"></div><div class="cleanser-impact"><img class="cleanser-world" src="${new URL(scene.art,location.href)}" alt="${esc(event.targetName)}"><div class="cleanser-fracture"></div><div class="cleanser-void"></div>${scene.outcome==='shielded'?'<div class="cleanser-shield-impact"></div>':''}<svg class="cleanser-wave" viewBox="-100 -100 200 200" aria-hidden="true"><circle r="48" vector-effect="non-scaling-stroke"/></svg><svg class="cleanser-wave cleanser-wave-delayed" viewBox="-100 -100 200 200" aria-hidden="true"><circle r="48" vector-effect="non-scaling-stroke"/></svg>${remains}${fragments}</div></div><div class="cleanser-flash"></div><div class="cleanser-damage"><small>DAMAGE / 20,000D12</small><strong>${Number(event.damage).toLocaleString()}</strong><span>${esc(scene.result)}</span></div><footer><span>Shared firing sequence · Combat paused</span><button type="button" data-mute>Mute sounds</button><span data-seconds></span></footer>`;
   cinema.addEventListener('cancel',e=>e.preventDefault());doc.body.append(cinema);cinema.showModal();cinema.querySelector('[data-mute]').onclick=()=>b.toggleSound();
   music=new Audio(new URL(timeline.audio,location.href));music.volume=.65;music.preload='auto';music.hidden=true;music.dataset.cleanserAudio='';cinema.append(music);
   if(timeline.impactAudio){impact=new Audio(new URL(timeline.impactAudio,location.href));impact.volume=.65;impact.preload='auto';impact.hidden=true;impact.dataset.cleanserImpactAudio='';cinema.append(impact);}
  }
  const elapsed=Math.max(0,Math.min(timeline.duration,(Date.now()-event.startedAt)/1000));
  cinema.style.setProperty('--elapsed',elapsed+'s');cinema.dataset.stage=window.SACleanserTimeline.stage(timeline,elapsed);
  cinema.querySelector('[data-stage]').textContent=window.SACleanserImpact.presentation(event).stages[cinema.dataset.stage];
  cinema.querySelector('[data-seconds]').textContent=Math.max(0,Math.ceil((event.endsAt-Date.now())/1000))+'s';cinema.querySelector('[data-mute]').textContent=b.soundEnabled()?'Mute sounds':'Enable sounds';
  window.SACleanserTimeline.syncAudio(music,elapsed,b.soundEnabled()&&!doc.hidden,timeline);
  window.SACleanserTimeline.syncAudio(impact,Math.max(0,elapsed-timeline.explosion)+(timeline.impactOffset||0),b.soundEnabled()&&!doc.hidden&&elapsed>=timeline.explosion,{audioSeconds:20});
  if(elapsed>=timeline.dice&&!diceStarted){diceStarted=true;frame=doc.createElement('iframe');frame.className='cleanser-dice';frame.title='Simulated damage — standard dice animation';frame.src=new URL('character.html?shipRoll=1',location.href);cinema.append(frame);}
 }
 function receive(e){
  if(e.origin!==location.origin)return;
  if(rollFrame&&e.source===rollFrame.contentWindow){
   const b=window.SACombatBridge,event=b.state().planetaryEvent;if(event?.id!==rollKey)return;
   if(e.data?.type==='sa-ship-skill-ready')rollFrame.contentWindow.postMessage({...rollPayload(b,event),type:'sa-ship-skill-open'},location.origin);
   if(e.data?.type==='sa-ship-skill-opened')rollReady=true;
   if(e.data?.rollId===rollKey){
    if(e.data.type==='sa-shared-damage-roll'&&canResolve(b,event))void sendDamage('roll');
    if(e.data.type==='sa-shared-damage-shown'&&canResolve(b,event))void sendDamage('shown');
    if(e.data.type==='sa-ship-skill-result'&&canResolve(b,event))void sendDamage('confirm');
   }
   return;
  }
  if(!frame||e.source!==frame.contentWindow)return;const event=window.SACombatBridge?.state()?.planetaryEvent;if(!event||event.id!==eventId)return;
  if(e.data?.type==='sa-ship-skill-ready')frame.contentWindow.postMessage({type:'sa-ship-skill-open',rollId:event.id,name:'Planetary Cleanser',title:'20,000D12 DAMAGE',sides:Array(96).fill(12),values:Array.from({length:96},(_,i)=>1+((event.dice?.[i%3]||1)-1+Math.floor(i/3))%12),diceFlood:true,score:event.damage,displayScore:event.damage,damage:true,immediateResult:true,spectator:true,simulated:true,exertionAvailable:0},location.origin);
  if(e.data?.type==='sa-automatic-dice-shown')setTimeout(()=>{if(frame?.isConnected)frame.remove();},700);
 }
 const doc=host();doc.defaultView.addEventListener('message',receive);const timer=setInterval(tick,100);
 window.addEventListener('pagehide',()=>{clearInterval(timer);doc.defaultView.removeEventListener('message',receive);closeCinema();closeRoll();hum?.pause();consoleView?.close();});
 window.SACleanserConsole={open,isOpen:()=>Boolean(consoleView||opening)};
}());
