export const FUBS_ENTRIES = [
  null,
  "Someone died saving your life a long time ago. Who was it, and why did they sacrifice themselves to save you?",
  "You were crippled for almost three years. How did you get hurt, and how did you recover even though doctors said it was impossible?",
  "It is possible you have an older brother or sister. Explain why your character does not know, and elaborate.",
  "One of your grandparents gave you something very special that you lost or destroyed by accident. What was the item, how did you lose or break it, and how does this make your character feel?",
  "There is a planet you have visited once, and you would be thrilled to visit it again. What was so great about the planet, and why have you not decided to simply move there?",
  "Possibly the worst thing you had to do was kill that person. Why did you have to kill them, and why do you regret it so badly?",
  "You and all the others had your rifles pointed at the woman. The man who hired you slowly stepped closer to her with a smirk on his face. She dropped her guns with a defeated look as her eyes met yours. That is when she gave you a wink. What did the wink mean? What happened?",
  "You fell in love with someone, but the relationship was impossible, so you had to walk away. Why? If they came back into your life, what would you do?",
  "At some point, you were in an all-out war and fought alongside several others against a foe. What was this war? How did you get involved? Who did you fight alongside?",
  "You have a secret that only you and five others know about. Who are these five people, and what is this secret? What negative thing would happen to you if this secret got out?",
  "You are missing the memory of X years. What years are they, and what have you found out? Did you hit your head? Did you ask for the memories to be removed? Were you in a coma?",
  "You used to go by a different name. Why did you change it? What was it?",
  "You used to have a pet that you loved more than anything in the world. Then you killed it. Why did this happen?",
  "When you were under 10 years old, you witnessed a murder. What were the circumstances? How did you react?",
  "The last words you heard them say before the communicator went to static were, \"I love you too.\" What happened? Who was this person?",
  "You thought you killed someone, but later you discovered you had failed. Why did you try to kill them, and how did you discover they are still alive?",
  "Someone attempted to murder you shortly after the two of you made love. Who was this person, and why did they try to kill you?",
  "You used to care for a blind elderly person. Why did you take care of them, and how did this make you feel?",
  "You were tied to a chair and tortured. For how long? Why? Who did this to you?",
  "You were found naked and unconscious on a beach. Who found you, and how did you get there?",
  "You and a few others survived in an area with high radiation for a long period. How? Why were you there? What caused the radiation?",
  "You used to go to a popular club, and everyone there adored you. Now you do not feel welcome there. Why? What was this club? Where was it? When was the last time you visited?",
  "You have a very long story you sometimes tell that involves a trap door. What is this story? Do you exaggerate the tale?",
  "You spent a long time trying to save someone's life, but you failed. What happened? How did they die?",
  "You ended up saving the life of someone much younger than you. What were the circumstances? How does this person view you?",
  "Choose a skill you have at 2 or higher. Explain the most implausible story about how this skill was developed.",
  "You have a relative whom you would kill where they stand if you saw them again. Who is this relative, and what did they do?",
  "You met someone who looked exactly like you. Explain how this happened.",
  "You were trained by someone to be the best at something. Explain who trained you, and why.",
  "You once saw a dead elephant floating in space. Explain.",
  "You have a unique scar. What is so unique about it, and how did you get it?",
  "The doctors said you were clinically dead for over 20 minutes. How are you alive now? What happened?",
  "Two in the morning, in a snowstorm, and you are digging a deep hole with a shovel. What were the circumstances?",
  "There is a planet that you will, under no circumstances, ever visit again. Why? Is it out of fear, pride, or honor? What happened there?",
  "You might have a son or daughter, but you are not sure. Who is the other parent, and what are the circumstances?",
  "You and a group of people were about to commit a bank robbery. You had inside information that it was a bad idea, but telling the group this information would get you into even more trouble. Explain why.",
  "You were in love with someone who loved you just as deeply, but that did not change the fact that you had to fight to the death. What happened?",
  "You discovered a paradise planet with breathable air and no civilization whatsoever. Explain how you discovered this planet and why you have not told anyone.",
  "When you were younger, your opinion of androids and droids changed forever. How did it change, and what caused it?",
  "Explain why, for a while, you thought your father was an android. Was he? What happened?",
  "You make your way out of the broken building. The hot sun feels brighter than normal. You go through your things and pull out some water, drinking it as fast as you are able. After you catch your breath, you start to smile. The smile turns into a laugh. Seconds later, a solar eclipse shrouds the area in shadow. You are no longer smiling. You are running. Why? What caused this situation?",
  "A large faction or federation would kill you if they knew that you knew the location of an object. What is the object, and why is it so important?",
  "Finally, after years of searching, you found it. Explain what it is, why it is so important, and at least one huge sacrifice you had to make to obtain it.",
  "You used to be a very talented artist. Explain why you gave it up, and why you will always refuse to showcase this talent.",
  "Write an elaborate story about your character in which the last line must be, \"...and that is why I always carry a _____ with me, wherever I go.\"",
  "You were determined to prove it was all a hoax. Explain what you tried to debunk and your character's reaction to discovering the truth.",
  "You used to think they were just stupid animals, until they saved your life. What happened? What kind of animals are they?",
  "You were arrested and thrown in jail, but the person who actually committed the crime was roaming free. How did you get caught up in this?",
  "At some point, you woke up drifting in outer space. What were you inside, and how did you manage to survive?",
  "The sound of an inserted sound or song drives you mad. Explain why.",
  "You had the gun pointed at you, with your own finger on the trigger. What happened, and why?",
  "You owe someone a life debt. What did this person do for you, and have they asked you for favors since?",
  "Explain why you were deaf and/or blind for almost three months, and who helped you during this period.",
  "Choose a skill you have at 2 or higher. Explain how this skill was developed through an encounter involving a ghost.",
  "You have had a recurring dream. Do you still have it? If not, when did it stop? What was the dream? Was it a nightmare?",
  "Choose another PC's home world. Explain why you had to travel there, and how you avoided trouble with the authorities.",
  "Choose another PC's friend or relative. Explain why you happened to be traveling with them for five months, and what you thought of them. Do the two of you know this happened? Do you keep it a secret? Why?",
  "They were your best friend for decades. Now you cannot stand the sight of each other. What happened? Who is this person?",
  "You witnessed the destruction of a civilized planet. Explain what happened, and how this made your character feel.",
  "You used to have an enemy or lover who was [other PC's race]. This [other PC] reminds you of this person. Explain how this makes you feel.",
  "You worked at a bar for a short period. What was your job there? Describe an incident at this bar that involved [another PC].",
  "You were once offered the most prestigious title by a royal king. Explain why you turned it down, and how the king reacted.",
  "The blizzard continues as you trudge through the deep snow. You approach the barely visible building amid the blinding white. You have been searching for this place for years. You open the door and step into the frozen cabin. Everything becomes silent. The computer terminal on the wall still has power. You approach it and pull out your duffle bag. What is in your bag? Why are you there? Explain this situation.",
  "You encountered [other PC] a long time ago, before you knew each other, but you were both working against the other. Explain what happened, and how you feel about it.",
  "As soon as you saw [other PC], you knew you had found the person you had been looking for. You give them an object during the first gaming session. What is this object, and why do you need to give it to [other PC]?",
  "The fate of an entire galaxy was at stake, including [other PC's home world]. Explain how you saved trillions of lives, and why you will never take credit for such a heroic act.",
  "The man you used to work for was begging you for his life. Did you kill him? Why was he begging? What happened?",
  "You gave a vial of biological material to a complete stranger with a set of specific instructions. What caused this act of desperation, and did the stranger follow through?",
  "After that day, the voice in your head never talked to you again. Explain what happened.",
  "You were forced to find a hermit on a wasteland planet several light-years away. Why? What happened once you found him?",
  "You activated the airlock and jumped down into the gas giant. You knew you were probably going to die a horrible death, but you had to try to save them. Did you? Who were they? How did you survive?",
  "The insane nurse laughed at you. \"This whole planet is a giant ball of ice! You cannot escape here!\" What happened? How did you escape? Who was the nurse?",
  "After performing some scans, it was obvious this planet had no life signs. The weapon of mass destruction must have destroyed all life. What were you doing here? What was the war about?",
  "You knew that if you traveled to the dark side of the planet, you were going to die, but you felt you did not have a choice because they would do the same for you. What happened? Why would you die? Why would you risk your own life to save them?",
  "The two of them pointed their guns at you. You were unarmed. Suddenly, a giant beast ate both of your assailants, but you did not run because you knew you were safe now. What happened? What was this beast? Why were the two threatening to kill you?",
  "Explain the story of why you had to impersonate a genetic engineer.",
  "The technology you held could have changed the universe as we know it. You could have been rich beyond your wildest imagination. Explain why you had to destroy it or how you lost it. How did you come across something so impactful? What was it?",
  "Oops. Something you did accidentally destroyed a large building, town, city, continent, or planet. Roll to determine which one randomly, or simply choose one. Explain how this happened and how many others know about it. How did it make you feel?",
  "The ship's sensors picked up nothing. You were passing the edge of the known universe. No stars in the sky. No other ships. Nothing nearby for several million light-years. How did you wind up in this situation? A voice crackles over the ship's communicator. Who is it? How is this possible?",
  "As a last resort, you powered up the FTL drive. After you activated it, you thought you were going to die for sure. The ship was suddenly in a star system not charted in any records by any known race or civilization. Explain what happened, why you thought you were going to die, and how you got back.",
  "Explain why you were at a funeral with a concealed weapon in your coat.",
  "You were leading the two people right into a trap. Why did they trust you, and why did you betray that trust? What happened?",
  "While performing a makeshift autopsy, you discovered the identity of the real killer. What did you do next? What caused this scenario?",
  "Stranded somewhere with several towns and civilized structures, you discover that there are no people anywhere on the whole planet. What happened? How did you get off this planet?",
  "Roll again. That story must somehow tie in with [other PC].",
  "Roll again. That story must somehow tie in with [the story of another PC], but not involve [that PC].",
  "As you pressed onward, you started to notice that everyone in the town was staring at you. Every single one. What happened? What were the circumstances?",
  "You woke up handcuffed to a post with a seven-year-old child pointing a fully automatic rifle at you. Explain how you got into this situation and how you got out.",
  "Your character spent 10 to 30 years in prison. Explain why you were convicted of the charges, and who helped you survive on the inside. Did you escape?",
  "Roll another story. That story is a lie that you are convinced happened to you. Why does your character believe it?",
  "You used to be in love with an A.I. Did you know they were an A.I.? What happened? How did it make you feel? Where are they now?",
  "For three days, you were shadowing this person. Who were they, and why were you shadowing them?",
  "For a while, your face was on billboards and every television channel. Explain why this was, and what ended up happening.",
  "You squeezed their hand as hard as you could, but the force was too great. They were gone. Explain what happened, who this person was, and what kind of force was too great.",
  "Explain how you ended up inside a dimensional rift. How did you escape? What caused it? Was anyone with you?",
  "You knew they were not who they claimed to be. You played along for a little while, but only until you could find your weapons. What happened?",
  "You told your teacher that the star charts were wrong. She laughed at you and said, \"Do not be silly.\" But you were right, and the star charts are still wrong. Explain why, and how you knew.",
  "Explain how and why you lived the exact same day more than once.",
  "For a few hours, you had superpowers. Explain how you got them, and why they were temporary.",
  "You are going to be born 25 decades in the future. Explain how this is possible.",
];

export const FUBS_CHAIN_RESULTS = new Set([85, 86, 90]);

export function fubsEntry(result) {
  return FUBS_ENTRIES[Number(result)] || "";
}
