const gear = (id, name, cost, description, extra = {}) => ({ id, name, cost, description, ...extra });

export const GEAR = [
  gear("360-camera", "360 Degree Camera", 200, "Mountable camera that records in every direction at once."),
  gear("one-man-vehicle", "4 Wheeled 1-Man Vehicle", 1800, "Motorized one-person vehicle. Move Speed 5; each consecutive Move adds +5, to a maximum of 20.", { special: "vehicle", seats: 1, moveSpeed: 5, acceleration: 5, maximumMoveSpeed: 20 }),
  gear("ai-calculator", "A.I. Calculator", 25, "User-friendly calculator for complex formulas with typed, drawn, and verbal input."),
  gear("ai-software", "A.I. Software", 700, "Generic software for use with an A.I. system."),
  gear("addictive-smoked-drug", "Addictive Smoked Drug", 5, "Genetically engineered addictive herb mixture inhaled for a euphoric effect."),
  gear("advanced-climbing-gear", "Adv. Climbing Gear", 80, "All-purpose climbing gear. Adds +4 to Climb rolls."),
  gear("advanced-backpack", "Advanced Backpack", 1000, "Anti-gravity mesh backpack that reduces the weight of objects within by 80%."),
  gear("all-purpose-antidote", "All-Purpose Antidote", 225, "Injection that cures most common poisons, venoms, viruses, and diseases. Do not use more than once in 14 days."),
  gear("altered-reality-glass", "Altered Reality Glass", 350, "Wearable holographic interface used for advertisements, games, social data, tutorials, and object labeling."),
  gear("antique-lock-pick-set", "Antique Lock Pick Set", 40, "Used to pick mechanical locks, including those used by low-technology civilizations."),
  gear("aqua-suit", "Aqua-Suit", 60, "Preserves Move Speed in water and provides six hours of breathable air."),
  gear("basic-clothing-set", "Basic Clothing Set", 35, "A set of common clothing."),
  gear("basic-toolbox", "Basic Toolbox", 75, "Fundamental tools for non-electronic repairs and mechanical structures."),
  gear("beacon-locator", "Beacon Locator", 80, "Locator with 10 beacons. Reports distance and direction through most materials up to 50 kilometers."),
  gear("binoculars", "Binoculars", 15, "Allows detailed perception of great distances."),
  gear("biological-scanner", "Biological Scanning/Detection", 1000, "Pocket scanner for biological life signs, health, anatomy, substances, food, and water."),
  gear("black-box", "Black Box", 100, "Durable recorder and distress beacon triggered by abnormal motion, impact, speed, or a crash."),
  gear("blue-towel", "Blue Towel", 20, "Royal blue towel. Multiple uses."),
  gear("bolt-handcuffs", "Bolt Handcuffs", 45, "Endernium-strength restraints for most humanoid beings."),
  gear("intoxicating-liquid", "Bottle of Intoxicating Liquid", 10, "If drunk: +2 to Charisma and Willpower rolls, and -3 to Dexterity and Intellect rolls until the session ends.", { special: "intoxicant", decrementLabel: "Drink / Remove" }),
  gear("briefcase", "Briefcase", 30, "Portable carrying case with a digital security lock."),
  gear("camera-headset", "Camera Headset", 25, "Headband that mounts a Remote Camera, sold separately."),
  gear("canteen-water-purifier", "Canteen/Water Purifier", 10, "Small container that converts nearly any water source into drinkable liquid."),
  gear("chameleon-cloak", "Chameleon Cloak", 320, "Changes pattern to match touched surfaces. Adds +4 to Stealth/Hide while immobile."),
  gear("childs-toy", "Child's Toy", 15, "A typical children's toy."),
  gear("cleaning-supplies", "Cleaning Supplies", 20, "All-purpose cleaning supplies."),
  gear("collapsible-pillow", "Collapsible Pillow", 60, "Deflatable pillow that fits in a pocket. Not a flotation device."),
  gear("communicator", "Communicator", 75, "Communicates with other communicators up to one astronomical unit, subject to interference."),
  gear("digital-binoculars", "Digital Binoculars", 300, "Up to 100x zoom. Adds +4 to Common Knowledge and Research rolls. Requires a Slow Delayed Resolution to focus in combat.", { special: "digital-binoculars" }),
  gear("distress-flares", "Distress Flares", 20, "Pack of five bright aerial lights that hover for approximately one hour."),
  gear("earplugs-dark-shades", "Earplugs/Dark Shades", 10, "Protects against harmful noise or light while worn; -3 to Perception rolls."),
  gear("electronics-toolkit", "Electronics Toolkit", 100, "Tools and wires for electronic work. Adds +2 to Engineering rolls. Five uses."),
  gear("emf-scanner", "EMF Scanner", 225, "Detects abnormal electrical disturbances up to eight units away."),
  gear("external-storage-unit", "External Storage Unit", 100, "Stores nearly limitless digital data; size and appearance are customized."),
  gear("fancy-clothing", "Fancy Clothing", 180, "A custom set of impressive clothing."),
  gear("fireworks", "Fireworks", 125, "Display pyrotechnics that can also be used as distress flares."),
  gear("first-aid-kit", "First Aid Kit", 35, "One-use medical kit. In combat, First Aid begins a delayed treatment and improves the healing result.", { special: "first-aid" }),
  gear("flashlight-laser-light", "Flashlight/Laser Light", 20, "Lightweight light that switches between a beam and a laser pointer."),
  gear("folding-motorbike", "Folding Motorbike", 300, "Two-wheeled dirt bike that folds into an eighty-pound luggage form."),
  gear("geological-scanner", "Geological Scanning/Detection", 1000, "Pocket scanner for caves, minerals, stone age, rotation speed, and other geological data."),
  gear("grappling-gun", "Grappling Gun", 250, "Two-handed grappling launcher with cable reaching 30 CvC units."),
  gear("gravity-boots", "Gravity Boots", 40, "Allows walking on surfaces in very low or zero gravity."),
  gear("heat-vision-goggles", "Heat Vision Goggles", 280, "-5 to Perception rolls, but automatically detects heat-based objects and lifeforms."),
  gear("holographic-dummy", "Holographic Dummy", 230, "Wristband that projects a mirror image of its user up to six units away."),
  gear("holo-projector", "Holo-Projector", 700, "Projects holograms within three units for maps, entertainment, communication, or distraction."),
  gear("holo-watch-laptop", "Holo-Watch Laptop PC", 2500, "Portable computer that projects a virtual keyboard, mouse, and holographic display."),
  gear("hover-drone", "Hover Drone", 800, "Remote-controlled black orb with a VR headset and optional Remote Camera support."),
  gear("hoverboard", "Hoverboard", 350, "Requires Athletics 2.0. Adds +2 Move Speed, ignores terrain, and gives -4 to combat Attribute rolls."),
  gear("insect-repellent", "Insect Repellent", 10, "One hundred sprays that kill small insects and hurt larger ones."),
  gear("laser-tripwires", "Invisible Laser Tripwires", 120, "Motion-triggered security system with wrist or computer alerts."),
  gear("jet-pack", "Jet-Pack", 5500, "Thirty flight charges. While used, Flight Move Speed is 4 and each Move spends one charge.", { special: "jet-pack", chargesMax: 30, rechargeKind: "charge" }),
  gear("jewelry", "Jewelry", 30, "A decorative wearable accessory."),
  gear("kevlar-vest", "Kevlar Vest", 850, "Reduces Physical-element Damage by 20. Cannot be worn with another suit or armor."),
  gear("large-drum", "Large Drum", 80, "One-square-meter container for ordinary material or liquid; holds up to 100 Minerals."),
  gear("lighter", "Lighter", 5, "Portable fire starter with approximately 1,000 uses."),
  gear("medium-container", "Medium Container", 60, "One-square-meter drawer container for normal or delicate materials; holds 100 Minerals."),
  gear("megaphone", "Megaphone", 25, "Amplifies the user's voice for distress or long-distance communication."),
  gear("metal-detector", "Metal Detector/Minesweeper", 180, "Detects metal and minerals underground up to three units away and highlights likely manufactured objects."),
  gear("metrological-scanner", "Metrological Scanning/Detection", 1000, "Pocket scanner for weather, atmosphere, mass, gravity, probability, and related measurements."),
  gear("microscope", "Microscope", 130, "Allows detailed perception of microscopic organisms."),
  gear("mineral-extractor", "Mineral Extractor", 1800, "Extracts minerals from a planet using the rulebook's escalating hourly die procedure."),
  gear("mobile-zero-point-energy", "Mobile Zero-Point Energy", 250, "Provides 3 EN and 1 AU for up to one hour. Recharges overnight from an AU-producing Engine.", { special: "zero-point", rechargeKind: "state", chargeStateMax: "Full" }),
  gear("motion-detector", "Motion Detector", 2800, "Reports moderate motion within ten CvC units and may attach to size A or B weapons."),
  gear("army-knife", "Multi-Function Army Knife", 40, "Compact collection of repair, survival, navigation, cutting, and fishing tools."),
  gear("night-vision-goggles", "Night Vision Goggles", 120, "Eliminates darkness modifiers, but gives -5 to Perception in a lit area."),
  gear("wristwatch", "Non-Electronic Wristwatch", 25, "Electronic-disturbance-proof watch with a compass."),
  gear("paintchalk", "PaintChalk", 20, "Colored paint sticks that draw on any non-biological surface."),
  gear("parachute", "Parachute", 100, "Compact parachute supporting characters up to 300 pounds."),
  gear("pet", "Pet", 150, "A small biological pet."),
  gear("playing-cards", "Playing Cards", 10, "Standard cards for Grintixvinupdx, Vutgudder, Wrakkle, Hexmute, and other games."),
  gear("portable-rations", "Portable Rations", 20, "Three acceptable-tasting nutritious meals."),
  gear("portable-theatre", "Portable Theatre", 80, "Tiny projector with surround sound and over 12,000 movies."),
  gear("powdered-alcohol", "Powdered Alcohol", 25, "Small canister used to spike a drink."),
  gear("power-shields", "Power Shields", 1400, "Projects a stationary 30 HP shield around the user and nearby protected characters. Stops projectiles with no overflow.", { special: "power-shields", chargesMax: 30, rechargeKind: "charge" }),
  gear("powerful-magnet", "Powerful Magnet", 125, "A curiously powerful magnet with a customized shape."),
  gear("printer", "Printer", 100, "Portable wireless printer that generates paper; one Dianium fuels 250 pages."),
  gear("quadcorder", "Quadcorder", 3000, "Combines biological, geological, metrological, and temporlogical scanning in one pocket device."),
  gear("radiation-blanket", "Radiation Blanket", 25, "Fabric-like sheet that protects its user from powerful radiation."),
  gear("random-number-generators", "Random Number Generators (Set of 7)", 5, "Various numbered shapes used to generate random numbers."),
  gear("red-towel", "Red Towel", 500, "Ruby red towel. The most massively useful thing an interstellar hitchhiker can have."),
  gear("remote-camera", "Remote Camera", 120, "Small mountable camera that records or streams to a computer."),
  gear("robokitty", "Robokitty", 350, "Electronic cat that passes the Feline Turing Test. Requires 1 AU every 24 hours."),
  gear("robomouse", "Robomouse", 325, "Programmable electronic mouse with a camera. Requires 1 AU every 72 hours."),
  gear("rope", "Rope", 15, "Fifty feet of rope."),
  gear("ship-beacon", "Ship Beacon", 2600, "Locator and beacon set with an 80,000-light-year range."),
  gear("shovel", "Shovel", 25, "Used to dig through dirt and soft terrain."),
  gear("sleeved-fire-extinguisher", "Sleeved Fire Extinguisher", 30, "Concealable extinguisher that reduces fire intensity by 5 at Range 4."),
  gear("small-atv", "Small ATV, 5 Passenger", 2500, "Five-person vehicle. Move Speed 3; each consecutive Move adds +3, to a maximum of 12.", { special: "vehicle", seats: 5, moveSpeed: 3, acceleration: 3, maximumMoveSpeed: 12 }),
  gear("small-container", "Small Container", 15, "Portable box for a small portion of material."),
  gear("smoke-grenade", "Smoke Grenade", 60, "Detonates after five seconds. Fills a six-unit radius with -8 to Perception and Projectile rolls; the penalty weakens by 1 every six seconds.", { special: "smoke-grenade", decrementLabel: "Throw / Remove" }),
  gear("space-suit", "Space Suit", 800, "Provides air, vacuum protection, 20 Suit HP, magnetic boots, and basic zero-gravity thrusters."),
  gear("string", "String", 5, "A small spool of string, twine, or yarn."),
  gear("sunglasses", "Sunglasses", 5, "Stylish shades that reduce discomfort from intense sunlight."),
  gear("survival-kit", "Survival Kit", 150, "Distress flare, compass, flashlight, mirror, army knife, radio, purifier, telescope, ration, and white towel."),
  gear("tape", "Tape", 5, "Adhesive roll that sticks to nearly any surface."),
  gear("temporlogical-scanner", "Temporlogical Scanning/Detection", 1000, "Pocket scanner for temporal disturbances, black holes, time flow, dark matter, paradoxes, and exact age."),
  gear("tent-blanket", "Tent/Blanket", 35, "Thirty-minute setup. Provides temperature control, air, and weather resistance for 30 hours."),
  gear("transmission-descrambler", "Transmission Descrambler", 210, "Translates standard encrypted radio messages into readable text or images."),
  gear("tripod-telescope", "Tripod Telescope", 85, "Stationary telescope for detailed perception over astronomical distances."),
  gear("umbrella", "Umbrella", 10, "Acid-proof protection from falling liquids."),
  gear("universal-credit-stick", "Universal Credit-Stick", 20, "Converts and stores currencies and is linked to its registered user."),
  gear("voice-mimic", "Voice Mimic", 160, "Changes the user's voice and can mimic a specific recorded speaker. Does not translate languages."),
  gear("vr-game", "VR Game", 50, "A game for a VR headset; the purchaser chooses the genre."),
  gear("vr-headset", "VR Headset", 200, "Immersive virtual interface. Adds +2 to Computer Systems when adapted to a terminal."),
  gear("universal-translator", "Universal Translator", 600, "Chest-mounted translator that converts speech with a five-second delay."),
  gear("weather-modifier", "Weather Modifier", 2500, "Projects an ionic pulse that modifies local weather; resolved with Intellect + Science/Physics."),
  gear("white-towel", "White Towel", 15, "Basic generic towel."),
];

export function gearById(id) {
  return GEAR.find((entry) => entry.id === id) || null;
}
