(() => {
 const defaults=[['Awareness Check','Perception','Awareness'],['Computer Check','Intellect','Computer Systems'],['Persuade Check','Charisma','Negotiation/Persuade'],['Self-Control Check','Willpower','Self-Control'],['Athletics Check','Dexterity','Athletics/Endurance']].map(([name,attribute,skill])=>({name,attribute,skill,difficulty:10}));
 let state,token,host,body,status,signature='',queue=Promise.resolve();
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 async function send(path,data){const r=await fetch('/api/campaign/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:state.code,token,...data})});const value=await r.json();if(!r.ok)throw Error(value.error);return value;}
 const presets=id=>structuredClone(state.quickPrompts?.[id]??defaults);
 const targets=id=>state.characters.filter(c=>id==='everyone'||c.id===id).map(c=>c.id);
 const run=fn=>()=>{queue=queue.then(async()=>{try{await fn();status.textContent='Saved / sent.';}catch(e){status.textContent=e.message;}});return queue;};
 async function save(column,list){const result=await send('quick-prompts',{column,presets:list});state.quickPrompts=result.campaign.quickPrompts;signature='';render();}
 async function prompt(ids,p){if(!ids.length)throw Error('Choose at least one character.');await send('roll/request',{targetIds:ids,attribute:p.attribute,skill:p.skill,difficulty:p.difficulty,source:p.name});}
 function render(){if(!host)return;const key=JSON.stringify([state.characters.map(c=>[c.id,c.character.identity?.characterName]),state.quickPrompts]);if(key===signature)return;signature=key;
 host.querySelector('section').style.width='min('+Math.min(1100,Math.max(620,(state.characters.length+1)*250))+'px,94vw)';
 const draft=body.querySelector('[data-name]')?{name:body.querySelector('[data-name]').value,attribute:body.querySelector('[data-attribute]').value,skill:body.querySelector('[data-skill]').value,difficulty:body.querySelector('[data-difficulty]').value,recipients:[...body.querySelectorAll('[data-recipient]:checked')].map(i=>i.value)}:null;
 const names=state.characters.map(c=>({id:c.id,name:c.character.identity?.characterName||'Unnamed Character'}));
 body.innerHTML=`<h2>Quick Prompt</h2><div class="quick-prompt-compose"><label>Attribute<select data-attribute>${document.querySelector('#promptAttribute')?.innerHTML||''}</select></label><label>Skill<select data-skill>${document.querySelector('#promptSkill')?.innerHTML||''}</select></label><label>Difficulty<input data-difficulty type="number" step="1" value="10"></label><label>Button name<input data-name placeholder="Skill Check"></label><fieldset><legend>Recipients</legend>${names.map(n=>`<label><input type="checkbox" data-recipient value="${esc(n.id)}">${esc(n.name)}</label>`).join('')}</fieldset><button data-send>Send</button><button data-add>Add to Quick Prompts</button></div><div class="quick-prompt-columns"></div>`;
 if(draft){for(const field of ['name','attribute','skill','difficulty'])body.querySelector('[data-'+field+']').value=draft[field];body.querySelectorAll('[data-recipient]').forEach(i=>i.checked=draft.recipients.includes(i.value));}
 const current=()=>({name:body.querySelector('[data-name]').value||body.querySelector('[data-skill]').value+' Check',attribute:body.querySelector('[data-attribute]').value,skill:body.querySelector('[data-skill]').value,difficulty:Math.round(Number(body.querySelector('[data-difficulty]').value)||0)});
 const selected=()=>[...body.querySelectorAll('[data-recipient]:checked')].map(i=>i.value);
 body.querySelector('[data-send]').onclick=run(()=>prompt(selected(),current()));
 body.querySelector('[data-add]').onclick=run(async()=>{const columns=selected();if(!columns.length)columns.push('everyone');if(columns.some(id=>presets(id).length>=10))throw Error('That column has ten prompts. Delete one first.');const item=current();for(const column of columns)await save(column,[...presets(column),item]);});
 for(const column of [...names,{id:'everyone',name:'Everyone'}]){const section=document.createElement('section');section.innerHTML=`<h3>${esc(column.name)}</h3>`;presets(column.id).forEach((p,index)=>{const row=document.createElement('div');row.className='quick-prompt-row';row.innerHTML=`<button data-roll>${esc(p.name)}</button><input type="number" step="1" value="${p.difficulty}" aria-label="${esc(column.name+' '+p.name+' difficulty')}"><button data-delete aria-label="Delete ${esc(p.name)}">×</button>`;row.querySelector('[data-roll]').onclick=run(()=>prompt(targets(column.id),{...p,difficulty:Math.round(Number(row.querySelector('input').value)||0)}));const difficultyInput=row.querySelector('input');let saveTimer;const persistDifficulty=()=>{clearTimeout(saveTimer);const value=Math.round(Number(difficultyInput.value)||0);saveTimer=setTimeout(()=>{void run(async()=>{const list=presets(column.id);if(!list[index])return;list[index].difficulty=value;await save(column.id,list);})();},250);};difficultyInput.addEventListener('input',persistDifficulty);difficultyInput.addEventListener('change',persistDifficulty);row.querySelector('[data-delete]').onclick=run(()=>save(column.id,presets(column.id).filter((_,i)=>i!==index)));section.append(row);});const award=document.createElement('button');award.textContent='+1 Reverence';award.className='quick-reverence';award.onclick=run(()=>send('quick-prompts',{column:column.id,kind:'reverence',receipt:crypto.randomUUID()}));section.append(award);body.querySelector('.quick-prompt-columns').append(section);}
 }
 window.SAQuickPrompts={update(next,key){state=next;token=key;if(!host){host=document.createElement('aside');host.className='quick-prompts';const toggle=document.createElement('button');toggle.textContent='Quick Prompt';toggle.className='quick-prompt-toggle';toggle.setAttribute('aria-expanded','false');const panel=document.createElement('section');panel.hidden=true;body=document.createElement('div');status=document.createElement('p');status.setAttribute('role','status');panel.append(body,status);host.append(toggle,panel);document.body.append(host);toggle.onclick=()=>{panel.hidden=!panel.hidden;toggle.setAttribute('aria-expanded',String(!panel.hidden));render();};}render();}};
})();
