(function(){let current;window.SARelayConsole={open(unit,sicId){if(current)return;const b=window.SACombatBridge;let doc=document;try{while(doc.defaultView.frameElement)doc=doc.defaultView.parent.document;}catch{}
 for(const name of ['console-common.css','utility-console.css'])if(!doc.querySelector(`link[href="${name}"]`)){const link=doc.createElement('link');link.rel='stylesheet';link.href=name;doc.head.append(link);}
 const v=current=doc.createElement('dialog');v.className='utility-console lock-console';v.dataset.operatorId=unit.id;v.dataset.sicId=sicId;v.setAttribute('aria-label','Relay Pulse Sub-Triangulator console');
 v.innerHTML='<header><h2>COUNTERFIRE TRIANGULATION</h2><div data-selector></div><button data-close>Combat View</button></header><section class="lock-chart utility-scene" style="position:relative!important;background:url(relay-triangulator-console.webp) center/cover"><div class="relay-sweep" style="position:absolute;inset:25% 30%;border:2px solid #6ef8ec;border-radius:50%;box-shadow:0 0 24px #4ee8d5;animation:shield-map-pulse 3s ease-in-out infinite"></div></section><section class="lock-controls utility-controls"><h3 data-status>PASSIVE COUNTERFIRE RECEIVER</h3><p>Direct incoming weapon fire reveals the firing ship immediately. Incoming missiles do not reveal their launcher.</p><p>Outside sensor range, the position is retained as a Last Known Location.</p><p>Impaired receiver: 50% chance to miss the signal.</p><div data-reports></div></section><section class="utility-seat"><button data-hold>Hold</button><button data-leave>Leave Console</button></section>';
 const get=s=>v.querySelector(s),who=()=>b.state().units.find(u=>u.id===unit.id);function draw(){const a=window.SAStationAccess.access(b.state(),who(),sicId);if(!a){v.close();return;}get('[data-status]').textContent=a.offline?'RECEIVER OFFLINE':a.item.impairmentPoints?'DEGRADED SIGNAL':'PASSIVE COUNTERFIRE RECEIVER';get('[data-reports]').textContent=(a.ship.sensorState?.reports||[]).filter(r=>r.relay).slice(0,5).map(r=>r.text).join('\n');get('[data-hold]').hidden=Boolean(b.state().practice);get('[data-hold]').textContent=who()?.consoleHold?'Resume':'Hold';}
 get('[data-close]').onclick=()=>v.close();get('[data-hold]').onclick=()=>window.SAShipNavigationUI.toggleHold(who());get('[data-leave]').onclick=()=>{v.close();if(!b.state().practice)window.SACombatMap.openMove(who());};window.SAShipNavigationUI.mountSelector(get('[data-selector]'),unit,sicId,()=>v.close());doc.body.append(v);v.showModal();window.SAConsoleCommon.mount(v,unit);draw();const timer=setInterval(draw,400);v.onclose=()=>{clearInterval(timer);current=null;v.remove();b.requestRender();};window.addEventListener('pagehide',()=>v.close(),{once:true});}};})();

(function(){let current;const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));window.SALockSharingConsole={open(unit,sicId){
 if(current)return;const b=window.SACombatBridge;let doc=document;try{while(doc.defaultView.frameElement)doc=doc.defaultView.parent.document;}catch{}
 for(const name of ['console-common.css','utility-console.css'])if(!doc.querySelector(`link[href="${name}"]`)){const l=doc.createElement('link');l.rel='stylesheet';l.href=name;doc.head.append(l);}
 const v=current=doc.createElement('dialog');v.className='utility-console lock-console';v.dataset.operatorId=unit.id;v.dataset.sicId=sicId;v.setAttribute('aria-label','Lock-On Triangulator console');
 v.innerHTML='<header><h2>LOCK SHARING NETWORK</h2><div data-selector></div><button data-close>Combat View</button></header><section class="lock-chart utility-scene" style="background:url(lock-triangulator-console.webp) center/cover"><output data-links style="padding:20px;background:#041820da;color:#9ffff0"></output></section><section class="lock-controls utility-controls"><h3>Recipients</h3><p>Linked ships receive locks after 12 active seconds. The originator pays normal Lock-On upkeep. Recipient Lock-On grade must be equal or higher.</p><div data-recipients></div><button data-save data-utility-control>Save Recipients</button><p role="status"></p></section><section class="utility-seat"><button data-hold>Hold</button><button data-leave>Leave Console</button></section>';
 const get=s=>v.querySelector(s),who=()=>b.state().units.find(u=>u.id===unit.id);let signature='',dirty=false,busy=false;
 function draw(){const state=b.state(),a=window.SAStationAccess.access(state,who(),sicId);if(!a){v.close();return;}const ships=state.starships.filter(s=>s.id!==a.ship.id&&!s.isMissile&&(!state.practice||s.controlType==='pc')),key=ships.map(s=>s.id).join('|');if(signature!==key){const checked=dirty?[...get('[data-recipients]').querySelectorAll('input:checked')].map(i=>i.value):a.ship.ship.triangulatorState?.recipients||[];get('[data-recipients]').innerHTML=ships.map(s=>`<label style="display:flex;gap:8px"><input type="checkbox" data-utility-control value="${esc(s.id)}" ${checked.includes(s.id)?'checked':''}>${esc(s.title)}</label>`).join('')||'No other available ships.';signature=key;}get('[data-links]').textContent=(a.ship.lockState?.targets||[]).filter(l=>!l.sharedFrom).length+' maintained source locks';get('[data-save]').disabled=busy||a.blocked||(!state.practice&&state.activeId!==unit.id);get('[data-hold]').hidden=Boolean(state.practice);}
 get('[data-recipients]').onchange=()=>{dirty=true;};get('[data-save]').onclick=async()=>{busy=true;try{await b.utilityAction({id:unit.id,starshipId:window.SAStationAccess.access(b.state(),who(),sicId).ship.id,sicId,kind:'share-locks',receipt:crypto.randomUUID(),recipients:[...get('[data-recipients]').querySelectorAll('input:checked')].map(i=>i.value)});dirty=false;get('[role=status]').textContent='Recipients saved.';}catch(e){get('[role=status]').textContent=e.message;}finally{busy=false;draw();}};
 get('[data-close]').onclick=()=>v.close();get('[data-hold]').onclick=()=>window.SAShipNavigationUI.toggleHold(who());get('[data-leave]').onclick=()=>{v.close();if(!b.state().practice)window.SACombatMap.openMove(who());};doc.body.append(v);v.showModal();window.SAShipNavigationUI.mountSelector(get('[data-selector]'),unit,sicId,()=>v.close());window.SAConsoleCommon.mount(v,unit);draw();const timer=setInterval(draw,400);v.onclose=()=>{clearInterval(timer);current=null;v.remove();b.requestRender();};window.addEventListener('pagehide',()=>v.close(),{once:true});
}};})();

(function(){let current;const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));window.SARemoteConsole={open(unit,sicId){
 if(current)return;const b=window.SACombatBridge;let doc=document;try{while(doc.defaultView.frameElement)doc=doc.defaultView.parent.document;}catch{}
 for(const name of ['console-common.css','utility-console.css'])if(!doc.querySelector(`link[href="${name}"]`)){const l=doc.createElement('link');l.rel='stylesheet';l.href=name;doc.head.append(l);}
 const v=current=doc.createElement('dialog');v.className='utility-console lock-console remote-console';v.dataset.operatorId=unit.id;v.dataset.sicId=sicId;v.setAttribute('aria-label','Remote control console');
 v.innerHTML='<header><h2>REMOTE COMMAND LINK</h2><div data-selector></div><button data-close>Combat View</button></header><section class="lock-chart utility-scene" style="background:url(remote-console.webp) center/cover"><output data-reports style="white-space:pre-line;padding:18px;background:#071722dc"></output></section><section class="lock-controls utility-controls"><h3 data-title></h3><p>Full Bridge access within 10 hexes. Local crew may cancel orders. One transmission per 12 active seconds. Additional receivers try the same command for 4 AU each from the Controller ship; each pays its own weapon or movement costs.</p><label>Linked receiver<select data-target data-utility-control></select></label><div style="display:grid;gap:10px"><button data-kind="remote-select" data-utility-control>Connect to Bridge</button><button data-kind="remote-disconnect" data-utility-control>Disconnect</button><button data-kind="remote-take" data-utility-control>Take Remote (Size C)</button><button data-kind="remote-link" data-utility-control>Link Carried Remote</button><button data-kind="remote-unlink" data-utility-control>Unlink Receiver</button><button data-kind="remote-cancel" data-utility-control>Cancel Remote Orders (Local Override)</button></div><p role="status"></p></section><section class="utility-seat"><button data-hold>Hold</button><button data-leave>Leave Console</button></section>';
 const get=s=>v.querySelector(s),who=()=>b.state().units.find(u=>u.id===unit.id);let signature='',busy=false;
 function draw(){const state=b.state(),a=window.SAStationAccess.access(state,who(),sicId);if(!a){v.close();return;}const receiver=a.definition.remoteReceiver,remote=window.SAStationAccess.remotes(state,who()).find(r=>r.item.id===sicId),links=remote?.links||[],key=links.map(s=>s.id+s.title).join('|');get('[data-title]').textContent=receiver?'RECEIVER / LOCAL AUTHORITY':'CONTROLLER / FLEET LINKS';get('[data-target]').closest('label').hidden=receiver;if(signature!==key){const old=get('[data-target]').value;get('[data-target]').innerHTML=links.map(s=>`<option value="${esc(s.id)}">${esc(s.title)}</option>`).join('')||'<option value="">No receiver in range</option>';if(links.some(s=>s.id===old))get('[data-target]').value=old;signature=key;}
 for(const button of v.querySelectorAll('[data-kind]')){button.hidden=receiver?['remote-select','remote-disconnect','remote-take'].includes(button.dataset.kind):['remote-link','remote-unlink','remote-cancel'].includes(button.dataset.kind);button.disabled=busy||a.offline;}
 get('[data-reports]').textContent=(who()?.remoteReports||[]).join('\n');get('[data-hold]').hidden=Boolean(state.practice);
 }
 for(const button of v.querySelectorAll('[data-kind]'))button.onclick=async()=>{busy=true;try{const a=window.SAStationAccess.access(b.state(),who(),sicId);await b.utilityAction({id:unit.id,starshipId:a.ship.id,sicId,kind:button.dataset.kind,targetId:get('[data-target]').value,receipt:crypto.randomUUID()});get('[role=status]').textContent=button.dataset.kind==='remote-select'?'Connected. Choose the remote ship’s console from the selector above.':'Remote settings updated.';}catch(e){get('[role=status]').textContent=e.message;}finally{busy=false;draw();}};
 get('[data-close]').onclick=()=>v.close();get('[data-hold]').onclick=()=>window.SAShipNavigationUI.toggleHold(who());get('[data-leave]').onclick=()=>{v.close();if(!b.state().practice)window.SACombatMap.openMove(who());};doc.body.append(v);v.showModal();window.SAShipNavigationUI.mountSelector(get('[data-selector]'),unit,sicId,()=>v.close());window.SAConsoleCommon.mount(v,unit);draw();const timer=setInterval(draw,400);v.onclose=()=>{clearInterval(timer);current=null;v.remove();b.requestRender();};window.addEventListener('pagehide',()=>v.close(),{once:true});
}};})();
