(() => {
  'use strict';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const roomKey=code=>'sa-room-player-'+code;
  async function api(action,body){const response=await fetch('/api/campaign/v03/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||'Room request failed.');return data;}
  function input(title,label,initial='') {return new Promise(resolve=>{
    const dialog=document.createElement('dialog');dialog.className='v03-dialog';dialog.innerHTML=`<form method="dialog"><h2>${esc(title)}</h2><label>${esc(label)}<input type="text" autocomplete="off"></label><button value="cancel">Cancel</button><button value="ok">Continue</button></form>`;
    dialog.querySelector('input').value=initial;document.body.append(dialog);dialog.addEventListener('close',()=>{const value=dialog.returnValue==='ok'?dialog.querySelector('input').value:null;dialog.remove();resolve(value);},{once:true});dialog.showModal();dialog.querySelector('input').focus();
  });}
  function confirmRoomAction(title,message,actionLabel){return new Promise(resolve=>{
    const dialog=document.createElement('dialog');dialog.className='v03-dialog';dialog.setAttribute('aria-label',title);
    const heading=document.createElement('h2');heading.textContent=title;const detail=document.createElement('p');detail.textContent=message;
    const form=document.createElement('form');form.method='dialog';
    for(const [value,label]of [['cancel','Cancel'],['confirm',actionLabel]]){const button=document.createElement('button');button.type='submit';button.value=value;button.textContent=label;form.append(button);}
    dialog.append(heading,detail,form);document.body.append(dialog);
    dialog.addEventListener('close',()=>{const accepted=dialog.returnValue==='confirm';dialog.remove();resolve(accepted);},{once:true});
    dialog.showModal();form.firstElementChild.focus();
  });}
  function shipApprovalChoice(request,state){return new Promise(resolve=>{
    const cost=Math.max(0,Number(request.data?.constructionCost)||0),balance=Number(state.shipCredits)||0;
    const dialog=document.createElement('dialog');dialog.className='v03-dialog';dialog.setAttribute('aria-label','Approve Starship');
    const heading=document.createElement('h2');heading.textContent='Approve '+(request.data?.title||'Starship');
    const summary=document.createElement('p');summary.textContent='Ship cost: '+cost.toLocaleString()+' Group Credits. Current balance: '+balance.toLocaleString()+'.';
    const detail=document.createElement('p');detail.textContent='Purchasing leaves '+(balance-cost).toLocaleString()+' Group Credits. Approving free adds the ship without changing the balance.';
    const form=document.createElement('form');form.method='dialog';
    for(const [value,label]of [['paid','Purchase with Group Credits'],['free','Approve Free'],['cancel','Cancel']]){const button=document.createElement('button');button.type='submit';button.value=value;button.textContent=label;form.append(button);}
    dialog.append(heading,summary,detail,form);document.body.append(dialog);
    dialog.addEventListener('close',()=>{const choice=dialog.returnValue;dialog.remove();resolve(choice==='paid'?true:choice==='free'?false:null);},{once:true});
    dialog.showModal();form.lastElementChild.focus();
  });}
  function file(accept='.json,.sa2campaign,.sa2character,.sa2char,.sa2ship'){return new Promise(resolve=>{const el=document.createElement('input');el.type='file';el.accept=accept;el.addEventListener('change',async()=>{try{resolve(JSON.parse(await el.files[0].text()));}catch{resolve(null);}}, {once:true});el.addEventListener('cancel',()=>resolve(null),{once:true});el.click();});}
  function gmOpen(data){localStorage.setItem('sa-gm-token-'+data.campaign.code,data.token);localStorage.setItem('sa-current-campaign-code',data.campaign.code);location.href='gm.html?campaign='+data.campaign.code;}
  function openCharacter(state,token){const id=state.ownCharacterId;if(!id)return;localStorage.setItem(`sa-character-token-${state.code}-${id}`,token);location.href=`character.html?campaign=${state.code}&character=${encodeURIComponent(id)}`;}
  async function loadFile(backup,choice){let data=await api('load',{backup,choice});if(data.requiresChoice){const dialog=document.createElement('dialog');dialog.className='v03-dialog';dialog.innerHTML='<h2>This room is already running</h2><p>Update its state using the loaded file, or enter the current room?</p><form method="dialog"><button value="join">Enter Current Room</button><button value="replace">Update Room from File</button><button value="cancel">Cancel</button></form>';document.body.append(dialog);dialog.showModal();const answer=await new Promise(resolve=>dialog.addEventListener('close',()=>resolve(dialog.returnValue),{once:true}));dialog.remove();if(!['join','replace'].includes(answer))return;data=await api('load',{backup,choice:answer});}gmOpen(data);}
  function menu(){const welcome=document.getElementById('welcomePanel');if(!welcome)return;
    if(!new URLSearchParams(location.search).has('embedded')&&!new URLSearchParams(location.search).has('room'))localStorage.setItem('sa-atb-mode','welcome');
    const host=document.createElement('section');host.className='v03-menu';host.innerHTML=`<form class="v03-join"><h1>Join Active Room</h1><label>Enter room code <input name="code" maxlength="4" required autocomplete="off" placeholder="ROOM"></label><button type="submit">Join Room</button></form><div class="v03-actions"><button data-load>Load Campaign</button><button data-new>Create New</button><a href="showcase.html">Tutorial / Explore Features</a></div><label><input type="checkbox" data-tutorial> Show tutorial prompts in Explore Features</label><p class="v03-status" role="status"></p>`;welcome.append(host);const version=document.createElement('small');version.className='v03-version';version.textContent='v0.3';welcome.append(version);
    const status=host.querySelector('[role=status]');const run=fn=>async event=>{event.preventDefault();try{await fn(event);}catch(error){status.textContent=error.message;}};
    host.querySelector('form').addEventListener('submit',run(async()=>{const code=host.querySelector('[name=code]').value.trim().toUpperCase();const existing=localStorage.getItem(roomKey(code));if(existing){const r=await fetch('/api/campaign/state?code='+code+'&token='+encodeURIComponent(existing));const saved=await r.json();if(r.ok&&saved.roomOpen){location.href='room.html?campaign='+code;return;}}const name=await input('Join Active Room','Your first name',localStorage.getItem('sa-first-name')||'');if(name===null)return;const data=await api('join',{code,name});localStorage.setItem('sa-first-name',name);localStorage.setItem(roomKey(code),data.token);location.href='room.html?campaign='+code;}));
    host.querySelector('[data-load]').addEventListener('click',run(async()=>{const backup=await file();if(backup)await loadFile(backup);}));
    host.querySelector('[data-new]').addEventListener('click',run(async()=>{const dialog=document.createElement('dialog');dialog.className='v03-dialog';dialog.innerHTML='<h2>Create New</h2><form method="dialog"><button value="campaign">Campaign</button><button value="character">Character</button><button value="ship">Starship</button><button value="cancel">Cancel</button></form>';document.body.append(dialog);dialog.showModal();const kind=await new Promise(resolve=>dialog.addEventListener('close',()=>resolve(dialog.returnValue),{once:true}));dialog.remove();if(kind==='campaign'){const name=await input('Create Campaign','Campaign name');if(name!==null)gmOpen(await api('create',{name}));}else if(kind==='character')location.href='character.html?library=1&new=1';else if(kind==='ship')location.href='starship.html?new=1';}));
    const tutorial=host.querySelector('[data-tutorial]');tutorial.checked=window.localStorage.getItem('sa-tutorial')==='on';tutorial.onchange=()=>window.localStorage.setItem('sa-tutorial',tutorial.checked?'on':'off');
  }
  async function lobby(){const title=document.getElementById('roomTitle');if(!title)return;const code=new URLSearchParams(location.search).get('campaign')||'';const token=localStorage.getItem(roomKey(code))||'';const status=document.getElementById('roomStatus');let state,events,lastRoster='';
    const run=fn=>async()=>{try{await fn();}catch(error){status.textContent=error.message;}};
    async function action(kind,body={}){const result=await api(kind,{code,token,...body});render(result.campaign);return result;}
    function render(next){state=next;if(moveRoom(state))return;if(state.roomOpen===false){status.textContent='The GM has closed this room.';events?.close();document.getElementById('roomActions').replaceChildren();document.querySelector('#v03SpectatorFrame')?.remove();return;}
      title.textContent=`${state.name} — ${code}`;const actions=document.getElementById('roomActions');actions.replaceChildren();const button=(label,fn)=>{const b=document.createElement('button');b.textContent=label;b.onclick=run(fn);b.dataset.action=label.toLowerCase().replace(/\s+/g,'-');actions.append(b);};
      if(state.ownCharacterId){button('Open My Character',()=>openCharacter(state,token));button('Abandon Character',()=>action('abandon'));}
      else {button('Create Character',()=>{location.href=`character.html?new=1&library=1&roomCreate=${code}`;});button('Choose Saved Character',async()=>{let entries=[];try{entries=JSON.parse(localStorage.getItem('sa2e-character-library-v1')||'[]');}catch{}if(!entries.length)throw Error('No characters are saved in this browser. Choose Import Character File to use an exported file.');const d=document.createElement('dialog');d.className='v03-dialog';d.innerHTML='<h2>Send a saved character for GM approval</h2><div data-list></div><button data-cancel>Cancel</button>';d.querySelector('[data-cancel]').onclick=()=>d.close();for(const c of entries){const b=document.createElement('button');b.textContent=c.identity?.characterName||'Unnamed';b.onclick=run(async()=>{await action('import',{kind:'character',data:c});d.close();});d.querySelector('[data-list]').append(b);}d.onclose=()=>d.remove();document.body.append(d);d.showModal();});button('Import Character File',async()=>{const data=await file();if(data)await action('import',{kind:'character',data});});}
      button('Leave Campaign',async()=>{if(!await confirmRoomAction('Leave Campaign','Leave this campaign and release your character link? Your character remains saved in the campaign.','Leave Campaign'))return;await api('leave',{code,token});localStorage.removeItem(roomKey(code));location.href='index.html';});
      button('Watch Combat',()=>{let frame=document.getElementById('v03SpectatorFrame');if(!frame){frame=document.createElement('iframe');frame.id='v03SpectatorFrame';frame.className='v03-spectator';frame.title='Combined PC combat view';frame.src='index.html?embedded=spectator&campaign='+code;document.getElementById('roomSpectator').append(frame);}frame.scrollIntoView({block:'start'});});
      button('Create Starship',()=>{location.href='starship.html?new=1&roomCreate='+encodeURIComponent(code);});
      button('Import Starship',async()=>{const data=await file();if(data)await action('import',{kind:'ship',data});});
      const roster=document.getElementById('roomRoster');const signature=JSON.stringify([state.ownCharacterId,state.characters.map(c=>[c.id,c.claimed,c.character.identity?.characterName])]);if(signature!==lastRoster){lastRoster=signature;roster.replaceChildren();for(const c of state.characters){const card=document.createElement('article');card.className='v03-panel';card.innerHTML=`<h2>${esc(c.character.identity?.characterName||'Unnamed Character')}</h2><button ${c.claimed||state.ownCharacterId?'disabled':''}>${c.claimed?'Linked to a player':'Link Character'}</button>`;card.querySelector('button').onclick=run(async()=>{const password=await input('Link '+(c.character.identity?.characterName||'Character'),'Character password');if(password!==null){await action('claim',{characterId:c.id,password});openCharacter(state,token);}});const view=document.createElement('button');view.textContent='View Character';view.onclick=()=>showReference('character.html?campaign='+code+'&character='+encodeURIComponent(c.id)+'&campaignView=1&embedded=1');card.append(view);roster.append(card);}}
      if(!state.characters.length){const empty=document.createElement('p');empty.className='v03-empty';empty.textContent='No characters yet. Create Character starts a new sheet in this campaign; saved characters need the GM’s approval.';roster.replaceChildren(empty);}
      const imports=document.getElementById('roomImports');imports.replaceChildren();if(state.imports?.length){const h=document.createElement('h2');h.textContent='Your Submissions';imports.append(h);}for(const request of state.imports||[]){const row=document.createElement('p');row.className='v03-panel';const isCharacter=request.kind==='character';const message=request.status==='pending'?'Waiting for GM approval in the GM’s Inbox.':request.status==='approved'?(isCharacter?'Approved! Choose a password to start playing.':'Approved! The ship is now in the PC fleet. The GM can assign its crew.'):request.status==='rejected'?'The GM declined this submission. You can revise it and submit again.':request.status;row.textContent=`${request.data?.identity?.characterName||request.data?.title||request.kind}: ${message} `;if(isCharacter&&request.status==='approved'&&!state.ownCharacterId){const b=document.createElement('button');b.textContent='Set Password and Play';b.onclick=run(async()=>{const password=await input('Imported Character','Choose a character password');if(password!==null){await action('import/finish',{requestId:request.id,password});openCharacter(state,token);}});row.append(b);}imports.append(row);}
      const fleet=document.getElementById('roomSpectator');if(!fleet.querySelector('h2')){const h=document.createElement('h2');h.textContent='PC Fleet';fleet.prepend(h);}const ships=state.starships||[];for(const row of fleet.querySelectorAll('[data-ship]'))if(!ships.some(ship=>ship.id===row.dataset.ship))row.remove();fleet.querySelector('.v03-empty')?.remove();if(!ships.length){const empty=document.createElement('p');empty.className='v03-empty';empty.textContent='No starships yet. Create or import a ship to send it to the GM for approval. Crew assignments are managed by the GM.';fleet.append(empty);}for(const ship of ships){let row=fleet.querySelector(`[data-ship="${CSS.escape(ship.id)}"]`);if(!row){row=document.createElement('article');row.className='v03-panel';row.dataset.ship=ship.id;fleet.append(row);}row.textContent=`${ship.title} — Crew: ${(ship.crewCharacterIds||[]).map(id=>state.characters.find(c=>c.id===id)?.character.identity?.characterName||'Crew').join(', ')||'None assigned'}`;const view=document.createElement('button');view.textContent='View Ship';view.onclick=()=>showReference('starship.html?campaign='+code+'&ship='+encodeURIComponent(ship.id)+'&details=1&view=1');row.append(view);}
    }
    try{const response=await fetch(`/api/campaign/state?code=${code}&token=${encodeURIComponent(token)}`);const data=await response.json();if(!response.ok)throw Error(data.error);render(data);events=new EventSource(`/campaign-events?code=${code}&token=${encodeURIComponent(token)}`);events.addEventListener('campaign',e=>render(JSON.parse(e.data)));events.onerror=()=>{status.textContent='Connection interrupted. Reconnecting…';};events.onopen=()=>{status.textContent='Connected';};}catch(error){status.textContent=error.message;}
  }
  function showReference(url){const dialog=document.createElement('dialog');dialog.className='v03-reference';const close=document.createElement('button');close.textContent='Close';close.onclick=()=>dialog.close();const frame=document.createElement('iframe');frame.src=url;frame.title='Campaign reference';dialog.append(close,frame);document.body.append(dialog);dialog.onclose=()=>dialog.remove();dialog.showModal();}
  function gmControls(state,token){if(state.interfaceVersion!=='0.3')return;
    document.getElementById('v03ImportNotice')?.remove();window.SACampaignRecovery?.update(state,token);let host=document.getElementById('v03GmManagement');if(!host){host=document.createElement('section');host.id='v03GmManagement';host.className='v03-management';(document.querySelector('[data-tab-panel="settings"]')||document.getElementById('gmWorkspace')).append(host);}const signature=JSON.stringify([state.players,state.imports,state.characters.map(c=>[c.id,c.pcCode])]);if(host.dataset.signature===signature)return;host.dataset.signature=signature;
    const unlinkedPlayers=(state.players||[]).filter(p=>!p.characterId),unclaimedCharacters=state.characters.filter(c=>!c.claimed);
    host.innerHTML=`<h2>Room and Players</h2><button data-close>Close Room</button><button data-code>Change Room Code</button><h3>Link a Player</h3><label>Unlinked player<select data-player>${unlinkedPlayers.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')||'<option value="">No unlinked players</option>'}</select></label><label>Available character<select data-character>${unclaimedCharacters.map(c=>`<option value="${esc(c.id)}">${esc(c.character.identity?.characterName)}</option>`).join('')||'<option value="">No unclaimed characters</option>'}</select></label><button data-assign ${unlinkedPlayers.length&&unclaimedCharacters.length?'':'disabled'}>Link Character</button><p>${!unlinkedPlayers.length?'All players are already linked. A new player can join using the room code.':!unclaimedCharacters.length?'Every character is already claimed. Create or approve another character before linking a player.':'Assign a character to the selected player without entering its password.'}</p><h3>Character Passwords</h3>${state.characters.map(c=>`<p>${esc(c.character.identity?.characterName)}: <strong>${esc(c.pcCode)}</strong></p>`).join('')}<p role="status"></p>`;
    const run=(fn)=>async()=>{try{await fn();}catch(error){host.querySelector('[role=status]').textContent=error.message;}};const send=(action,body={})=>api(action,{code:state.code,token,...body});
    host.querySelector('[data-close]').onclick=run(async()=>{if(await confirmRoomAction('Close Room','Close the room for everyone? Saved campaign data will remain.','Close Room for Everyone')){await send('close');location.href='index.html';}});
    host.querySelector('[data-code]').onclick=run(async()=>{if(await confirmRoomAction('Change Room Code','Change the room code? Players will need the new code.','Change Room Code')){const result=await send('change-code');gmOpen(result);}});
    host.querySelector('[data-assign]').onclick=run(()=>send('assign',{playerId:host.querySelector('[data-player]').value,characterId:host.querySelector('[data-character]').value}));
    let imports=document.getElementById('v03InboxImports');if(!imports){imports=document.createElement('section');imports.id='v03InboxImports';(document.querySelector('[data-tab-panel="inbox"]')||document.getElementById('gmInboxList')?.parentElement||host).prepend(imports);}imports.replaceChildren();
    for(const request of state.imports||[]){if(request.status!=='pending')continue;const row=document.createElement('div');row.innerHTML=`<strong>${esc(request.kind)}: ${esc(request.data?.identity?.characterName||request.data?.title||'Unnamed')}</strong> ${request.kind==='character'&&request.data?.phase!=='finalized'?'<small>Saved draft: approval accepts the current stats as playable.</small>':''} <button data-review>Review Data</button> <button data-yes>Approve</button><button data-no>Reject</button>`;row.querySelector('[data-review]').onclick=()=>{const d=document.createElement('dialog');d.className='v03-dialog';const heading=document.createElement('h2');heading.textContent='Submitted '+request.kind;const details=document.createElement('div');details.style.cssText='max-height:60vh;overflow:auto';const ignored=new Set(['id','campaignLink','access','receipts','config','pendingRoll','purchaseOrder','resourceReceipts','version','phase','advancementOpen','importedDraft','creation','session','buildRevision','updatedAt','lastSavedAt']);const describe=(value,parent)=>{for(const [key,item]of Object.entries(value||{})){if(ignored.has(key)||item===null)continue;if(key==='floorplanSnapshot'){if(/^data:image\/webp;base64,/.test(item.data||'')){const img=document.createElement('img');img.src=item.data;img.alt='Submitted floorplan';img.style.maxWidth='100%';parent.append(img);}continue;}const label=key.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/^./,c=>c.toUpperCase());if(typeof item==='object'){const group=document.createElement('details'),heading=document.createElement('summary');heading.textContent=label;group.append(heading);describe(item,group);parent.append(group);}else{const line=document.createElement('p');line.textContent=label+': '+item;parent.append(line);}}};describe(request.data,details);const close=document.createElement('button');close.textContent='Close Review';close.onclick=()=>d.close();d.append(heading,details,close);d.onclose=()=>d.remove();document.body.append(d);d.showModal();};row.querySelector('[data-yes]').onclick=run(async()=>{let useGroupCredits;if(request.kind==='ship'){useGroupCredits=await shipApprovalChoice(request,state);if(useGroupCredits===null)return;}return send('import/respond',{requestId:request.id,approve:true,useGroupCredits});});row.querySelector('[data-no]').onclick=run(()=>send('import/respond',{requestId:request.id,approve:false}));imports.append(row);}
  }
  function moveRoom(state){if(!state.redirectCode)return false;const old=state.code,next=state.redirectCode;for(const key of Object.keys(localStorage)){if(key.startsWith('sa-')&&key.includes(old))localStorage.setItem(key.replace(old,next),localStorage.getItem(key));}const url=new URL(location.href);url.searchParams.set('campaign',next);location.replace(url.href);return true;}
  async function importIntoRoom(code,kind,data){
    code=String(code).trim().toUpperCase();
    let token=localStorage.getItem(roomKey(code));
    const response=await fetch('/api/campaign/state?code='+encodeURIComponent(code)+'&token='+encodeURIComponent(token||''));const room=await response.json();if(response.ok&&room.interfaceVersion!=='0.3')return false;
    if(!response.ok&&response.status!==403)throw Error(room.error||'Room unavailable.');
    if(token){const current=await fetch('/api/campaign/state?code='+code+'&token='+encodeURIComponent(token));const state=await current.json();if(!current.ok||!state.roomOpen)token=null;}
    if(!token){const name=await input('Join Active Room','Your first name',localStorage.getItem('sa-first-name')||'');if(name===null)return true;const joined=await api('join',{code,name});token=joined.token;localStorage.setItem(roomKey(code),token);localStorage.setItem('sa-first-name',name);}
    await api('import',{code,token,kind,data});location.href='room.html?campaign='+code;return true;
  }
  window.SARoomV03={api,input,file,gmControls,roomKey,openCharacter,loadFile,moveRoom,importIntoRoom};
  function tutorialSetting(){const host=document.querySelector('[data-tab-panel="settings"],#settingsPanel,[data-character-panel="settings"],[data-character-tab-panel="settings"]');if(!host||document.getElementById('tutorialSetting'))return;const label=document.createElement('label');label.id='tutorialSetting';label.className='check-field';label.innerHTML='<input type="checkbox"> Show tutorial prompts in Explore Features';const box=label.querySelector('input');box.checked=window.localStorage.getItem('sa-tutorial')==='on';box.onchange=()=>{window.localStorage.setItem('sa-tutorial',box.checked?'on':'off');if(window.parent!==window)window.parent.postMessage({type:'sa-tutorial-setting',enabled:box.checked},location.origin);if(!box.checked)document.querySelectorAll('.v03-tutorial:not(#v03ImportNotice)').forEach(t=>t.remove());};host.append(label);}
  window.addEventListener('message',event=>{if(event.origin===location.origin&&event.data?.type==='sa-tutorial-setting'&&!event.data.enabled)document.querySelectorAll('.v03-tutorial:not(#v03ImportNotice)').forEach(t=>t.remove());});
  tutorialSetting();menu();lobby();
  if(location.pathname.endsWith('/showcase.html')&&window.localStorage.getItem('sa-tutorial')==='on'){const tip=document.createElement('aside');tip.className='v03-tutorial';tip.innerHTML='<strong>Explore Features</strong><p>Switch between GM and Nova above. As GM, prepare ships and crew, then begin combat. As a PC, open Console View to operate a station. The clock pauses for rolls.</p><label style="display:block;font-size:12px"><input type="checkbox"> Disable Tutorial Popups</label><button>Okay</button>';tip.querySelector('button').onclick=()=>{if(tip.querySelector('input').checked)window.localStorage.setItem('sa-tutorial','off');tip.remove();};document.body.append(tip);}
})();
