(function(){
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const duration=s=>{if(s>=86400)return (s/86400).toFixed(2).replace(/\.00$/,'')+' days';if(s>=3600)return (s/3600).toFixed(1)+' hours';if(s>=60)return Math.ceil(s/60)+' minutes';return Math.ceil(s)+' seconds';};
 function mount(dialog,send){const doc=dialog.ownerDocument,root=doc.createElement('section');root.className='science-fabrication';root.innerHTML='<h3>Fabrication & Mineral Processing</h3><label>Installed equipment<select data-utility-control data-fabricator></select></label><p data-fabricator-status></p><div class="science-queue" data-science-queue></div><div class="science-recipes" data-science-recipes></div><p data-science-events role="status"></p>';dialog.querySelector('.crew-room-records').before(root);let info,selected='',key='';
  const select=root.querySelector('select');select.onchange=()=>{selected=select.value;key='';render(info);};
  let confirmation;
  function confirmJob(message){if(confirmation)return Promise.resolve(false);return new Promise(resolve=>{const box=confirmation=doc.createElement('dialog');box.className='science-confirm';box.setAttribute('aria-label','Confirm fabrication');box.innerHTML='<h2>Confirm fabrication</h2><p></p><button data-yes>Confirm</button><button data-no>Cancel</button>';box.querySelector('p').textContent=message;let approved=false;box.querySelector('[data-yes]').onclick=()=>{approved=true;box.close();};box.querySelector('[data-no]').onclick=()=>box.close();box.onclose=()=>{box.remove();confirmation=null;resolve(approved);};doc.body.append(box);box.showModal();});}
  dialog.addEventListener('close',()=>confirmation?.close(),{once:true});
  root.onclick=async e=>{const button=e.target.closest('[data-recipe],[data-cancel-print]');if(!button||button.disabled)return;const machine=info?.fabrication?.systems.find(m=>m.id===select.value);if(!machine)return;if(button.dataset.cancelPrint){if(await confirmJob('Cancel this job? Minerals already consumed will not be refunded.'))await send({kind:'fabricate-cancel',machineId:machine.id,jobId:button.dataset.cancelPrint});return;}const recipe=(machine.type==='3d-printer'?info.fabrication.blueprints:info.fabrication.recipes).find(r=>(r.type||r.name)===button.dataset.recipe);if(recipe&&await confirmJob('Would you like to '+(recipe.type?'craft ':'process 1 ')+recipe.name+'?\n'+Object.entries(recipe.minerals).map(([n,q])=>q+' '+n).join(' + ')+' · '+duration(recipe.seconds)+'\nMinerals are consumed when this job starts.'))await send({kind:'fabricate-add',machineId:machine.id,recipeType:recipe.type||recipe.name});};
  function render(next,busy=false){info=next;if(!info?.fabrication)return;const f=info.fabrication,systems=f.systems;selected=systems.some(s=>s.id===selected)?selected:systems[0]?.id||'';const options=systems.map((s,i)=>'<option value="'+esc(s.id)+'">'+esc(s.name)+' '+(i+1)+'</option>').join('');if(select.innerHTML!==options)select.innerHTML=options;select.value=selected;const machine=systems.find(s=>s.id===selected);root.querySelector('[data-fabricator-status]').textContent=machine?(machine.reason||'Online')+' · '+machine.queue.length+'/6 queue slots':'Install a 3D Printer or Mineral Processor inside this Science Lab.';
   const queue=root.querySelector('[data-science-queue]');queue.innerHTML=(machine?.queue||[]).map((j,i)=>'<article><strong>'+esc(j.name)+'</strong><progress aria-label="'+esc(j.name)+' progress" max="'+j.seconds+'" value="'+(j.seconds-j.remaining)+'"></progress><small>'+esc(j.paused||(j.started?Math.floor((1-j.remaining/j.seconds)*100)+'% · '+duration(j.remaining)+' remaining':'Queued — minerals not consumed'))+'</small><button data-utility-control data-cancel-print="'+esc(j.id)+'">Cancel</button></article>').join('');
   const recipes=machine?(machine.type==='3d-printer'?f.blueprints:f.recipes):[],markup=recipes.map(r=>'<button type="button" data-utility-control data-recipe="'+esc(r.type||r.name)+'" class="science-recipe '+(!r.available?'lacks-minerals':'')+'" '+(busy||!r.available||machine.queue.length>=6?'disabled':'')+'>'+(r.art?'<img src="'+esc(r.art)+'" alt="">':'')+'<strong>'+esc(r.name)+'</strong><small>'+esc(Object.entries(r.minerals).map(([n,q])=>q+' '+n).join(' + '))+'</small><small>'+duration(r.seconds)+'</small>'+(!r.available?'<small>Insufficient minerals</small>':'')+'</button>').join('')||'<p>No blueprints owned. Choose “Buy blueprint” on a craftable SIC in the shop.</p>';if(markup!==key){root.querySelector('[data-science-recipes]').innerHTML=markup;key=markup;}root.querySelector('[data-science-events]').textContent=f.events.slice(-1)[0]?.text||'';for(const b of queue.querySelectorAll('button'))b.disabled=busy;
  }return {render};
 }window.SAScienceConsole={mount};
}());
