(function(root,factory){
  const node=typeof module!=='undefined'&&module.exports;
  const api=factory(node?require('./ship-distances'):root.SAShipDistances);
  if(node)module.exports=api;if(root)root.SAShipTargets=api;
}(typeof window!=='undefined'?window:null,function(distances){
  const flights=room=>(room.starships||[]).flatMap(s=>s.ship?.missileState?.flights||[]);
  function proxy(m){return {id:m.id,title:m.name,isMissile:true,missileHeading:m.heading||0,missileSlot:m.slot||0,missileSalvoSize:m.salvoSize||1,missilePhase:m.phase,missilePosition:m.position,missileSpeed:m.speed,missileEndedAt:m.endedAt,defenseScore:m.masking,currentHullHp:['flying','impact'].includes(m.phase)?1:0,maximumHullHp:1,currentShieldHp:0,maximumShieldHp:0,ship:{gridCells:[],placements:[],sicInventory:[],doorStates:{}},projectile:m};}
  const drones=room=>(room.starships||[]).flatMap(s=>Object.values(s.ship?.droneState?.drones||{})).filter(d=>['repairing','returning'].includes(d.phase));
  function droneProxy(d){return {id:d.id,title:'Repair Drone '+(d.tier||1),droneTier:d.tier||1,droneSprite:d.sprite||'repair-drone-1-sprite.webp',isDrone:true,contactOnly:true,droneOwnerId:d.ownerId,droneTargetId:d.targetId,defenseScore:d.masking??12,currentHullHp:d.threshold??14,maximumHullHp:d.threshold??14,currentShieldHp:0,maximumShieldHp:0,ship:{gridCells:[],placements:[],sicInventory:[],doorStates:{}}};}
  const probes=room=>(room.starships||[]).flatMap(s=>Object.values(s.ship?.probeState?.probes||{})).filter(p=>['flying','holding','returning','recovering','approaching','breaching','attached'].includes(p.phase));
  function probeProxy(p){return {id:p.id,title:p.name,isProbe:true,contactOnly:true,probeOwnerId:p.ownerId,probePosition:p.position,probeTier:p.tier,probeInhibitor:p.inhibitor==='active',defenseScore:p.masking,currentHullHp:p.threshold,maximumHullHp:p.threshold,currentShieldHp:0,maximumShieldHp:0,ship:{gridCells:[],placements:[],sicInventory:[],doorStates:{}}};}
  function all(room){const existing=new Set((room.starships||[]).map(s=>s.id));return [...(room.starships||[]),...probes(room).filter(p=>!existing.has(p.id)).map(probeProxy),...drones(room).filter(d=>!existing.has(d.id)).map(droneProxy),...flights(room).filter(m=>!existing.has(m.id)&&(['flying','impact'].includes(m.phase)||Date.now()-(m.endedAt||0)<6000)).map(m=>({...proxy(m),contactOnly:true}))];}
  function find(room,id){const ship=(room.starships||[]).find(s=>s.id===id);if(ship)return ship;const p=probes(room).find(p=>p.id===id);if(p)return probeProxy(p);const d=drones(room).find(d=>d.id===id);if(d)return droneProxy(d);const m=flights(room).find(m=>m.id===id);return m&&(['flying','impact'].includes(m.phase)||Date.now()-(m.endedAt||0)<6000)?proxy(m):undefined;}
  function point(room,id){const ship=(room.starships||[]).find(s=>s.id===id);if(ship?.probePosition)return ship.probePosition;const probe=probes(room).find(p=>p.id===id);if(probe)return probe.position;if(ship?.missilePosition)return ship.missilePosition;if(ship?.isDrone)return ship.dronePosition||point(room,ship.droneTargetId);const d=drones(room).find(d=>d.id===id);if(d)return point(room,d.targetId);const m=!ship&&flights(room).find(m=>m.id===id);return m?.position||distances.positions(room.starships||[],room.shipPositions||[]).find(p=>p.id===id);}
  function hit(room,id,damage){if(probes(room).some(p=>p.id===id))return require('./ship-probes').hit(room,id,damage);if(drones(room).some(d=>d.id===id))return require('./ship-drones').hit(room,id,damage);const m=flights(room).find(m=>m.id===id);if(!m||!['flying','impact'].includes(m.phase)||damage<1)return false;m.phase='destroyed';m.endedAt=Date.now();return true;}
  return {probes,probeProxy,flights,drones,droneProxy,proxy,all,find,point,hit};
}));
