(function(root,factory){const api=factory(typeof module==='object'?require('./ship-map-core'):root.SAShipMap);if(typeof module==='object')module.exports=api;else root.SAShipDoors=api;})(typeof window==='object'?window:null,function(maps){
 const broken=(ship,key)=>(ship.ship||ship).doorDamage?.[key]>=3;
 function list(ship){const l=maps.buildLayout(ship.ship||ship),keys=new Set();for(const sq of l.hull)for(const side of l.sides){const e=l.boundary(sq,side.name);if(e.kind==='door')keys.add(e.key);}return [...keys];}
 function roomKey(ship,square,layout){const l=layout||maps.buildLayout(ship.ship||ship),c=l.footprint.get(Number(square));if(c)return c.sicId;const seen=new Set([Number(square)]),queue=[Number(square)];for(const s of queue)for(const side of l.sides){const n=s+side.offset;if(side.valid(s)&&l.hull.has(n)&&!seen.has(n)&&!l.footprint.has(n)&&l.edge(s,n).kind==='none'){seen.add(n);queue.push(n);}}return 'corridor:'+Math.min(...seen);}
 function targets(room,unit,melee=false){const ship=room.starships.find(s=>s.id===unit.location?.starshipId);if(!ship)return [];const l=maps.buildLayout(ship.ship),loc=unit.location,origin=roomKey(ship,loc.square),xy=p=>({x:(p.square%l.columns)*3+(p.mesh%3),y:Math.floor(p.square/l.columns)*3+Math.floor(p.mesh/3)}),p=xy(loc);return list(ship).filter(k=>!broken(ship,k)).flatMap(key=>{const squares=key.split(':').map(Number),near=squares.filter(s=>l.hull.has(s)&&roomKey(ship,s)===origin);if(!near.length)return [];const sq=near[0],other=squares.find(s=>s!==sq),mesh=other===sq+1?5:other===sq-1?3:other>sq?7:1,q=xy({square:sq,mesh}),distance=Math.max(1,Math.ceil(Math.hypot(q.x-p.x,q.y-p.y)));if(melee&&distance>1)return [];return [{id:'door:'+ship.id+':'+key,characterName:'Door '+key+' ('+((ship.ship.doorDamage||{})[key]||0)+'/3 hits)',team:'door',doorTarget:{shipId:ship.id,key},distance,location:{starshipId:ship.id,square:sq,mesh},damageReduction:0}];});}
 function find(room,id){if(!String(id).startsWith('door:'))return null;for(const ship of room.starships||[])for(const key of list(ship))if(id==='door:'+ship.id+':'+key)return {id,characterName:'Door '+key,team:'door',doorTarget:{shipId:ship.id,key},damageReduction:0};return null;}
 function threshold(ship,key){const s=ship.ship||ship,l=maps.buildLayout(s);return key.split(':').some(n=>l.footprint.get(Number(n))?.type==='brig')?40:10;}
 function canOperate(ship,unit,key){if(!unit?.location||unit.location.starshipId!==ship.id)return false;const l=maps.buildLayout(ship.ship||ship),cell=l.footprint.get(unit.location.square);return !!(unit.currentHp>0&&unit.location.stationed&&cell&&unit.location.sicId===cell.sicId&&cell.stations.some(p=>p.x===cell.column&&p.y===cell.row&&p.mesh===Number(unit.location.mesh))&&maps.definition(cell.type).bridge&&maps.operational(cell.item))||key.split(':').map(Number).includes(unit.location.square);}
 function hit(room,target,damage){const ship=room.starships.find(s=>s.id===target.shipId);if(!ship||!list(ship).includes(target.key))throw Error('Door is no longer present.');ship.ship.doorDamage||={};let hits=ship.ship.doorDamage[target.key]||0;if(damage>=threshold(ship,target.key))hits=Math.min(3,hits+1);ship.ship.doorDamage[target.key]=hits;if(hits>=3){ship.ship.doorStates||={};ship.ship.doorStates[target.key]='open';}return hits;}
 return {broken,list,roomKey,targets,find,hit,threshold,canOperate};
});
