(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.SASkillCatalog=api;}(typeof globalThis!=='undefined'?globalThis:this,function(){
const attributes = Object.freeze({
  "Computer Systems":"intellect", "Engineering":"intellect", "Hacking":"intellect", "Pilot/Helm":"dexterity", "Sensor Systems":"perception", "Weapon Systems":"dexterity",
  "Acting/Lie": "charisma",
  "Anatomy/First Aid": "intellect",
  "Architecture": "intellect",
  "Art/Music": "charisma",
  "Astronomy": "intellect",
  "Athletics/Endurance": "health",
  "Awareness": "perception",
  "Break Free/Escape": "strength",
  "Caretaking/Nurture": "charisma",
  "Catch/Throw": "dexterity",
  "Climb": "strength",
  "Common Knowledge": "intellect",
  "Cooking": "intellect",
  "Demolitions": "intellect",
  "Disguise/Mimic": "charisma",
  "Dodge/Block": "dexterity",
  "Drive/Small Vehicle": "dexterity",
  "Fashion/Etiquette": "charisma",
  "Forgotten Languages": "intellect",
  "Gambling": "luck",
  "History/Lore": "intellect",
  "Identify Taste/Smell": "perception",
  "Initiative": "intellect",
  "Intimidate/Taunt": "charisma",
  "Intuition/Empathy": "perception",
  "Jump": "strength",
  "Law/Politics": "intellect",
  "Leadership": "charisma",
  "Lift/Push/Pull": "strength",
  "Lock-picking": "dexterity",
  "Mathematics": "intellect",
  "Melee": "strength",
  "Navigate": "perception",
  "Negotiation/Persuade": "charisma",
  "Occult": "intellect",
  "Pickpocket": "dexterity",
  "Projectile": "dexterity",
  "Psychology": "intellect",
  "Religion": "intellect",
  "Research": "intellect",
  "Resist Distress": "willpower",
  "Science/Physics": "intellect",
  "Self-Control": "willpower",
  "Showmanship": "charisma",
  "Stealth/Hide": "dexterity",
  "Survival/Tracking": "perception",
  "Swim": "strength",
  "Tame Animal": "charisma",
  "Teaching": "charisma",
  "Technology": "intellect",
  "Vehicle Mechanics": "intellect",
  "Weapon Mechanics": "intellect",
  "Wrestle/Disarm": "strength",
  "Writing": "intellect",
});
const groups=Object.freeze(['strength','health','perception','dexterity','luck','charisma','intellect','willpower'].map(key=>({key,label:key[0].toUpperCase()+key.slice(1)})));
return Object.freeze({attributes,groups,names:Object.freeze(Object.keys(attributes))});
}));
