(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let openView;
 // Arrival selection must use information earned by this ship's sensors, never
 // the live target layout present in the GM's room state.
 function arrivalLayout(source,targetId){return window.SAShipSensors.analysis(source,targetId)?.layout||null;}
 window.SATransporterConsole={open(unit,sicId){
  if(openView)return;const b=window.SACombatBridge;let doc=document;try{while(doc.defaultView.frameElement&&!doc.defaultView.frameElement.hasAttribute('data-explore-perspective'))doc=doc.defaultView.parent.document;}catch{}
  const initial=window.SAStationAccess.access(b.state(),unit,sicId);if(!initial)return;
  const d=doc.createElement('dialog');openView=d;d.className='transporter-console';d.setAttribute('aria-label','Transporter console');d.dataset.sicId=sicId;d.dataset.operatorId=unit.id;d.dataset.standaloneConsole='true';d.style.cssText='position:fixed;inset:10px;width:calc(100vw - 20px);height:calc(100dvh - 20px);max-width:none;max-height:none;margin:0;overflow:auto;background:#071a24;color:#e3f9ff;border:1px solid #61e6ff;padding:16px;box-sizing:border-box';
  d.innerHTML=`<style>
   .transporter-console>header{display:flex;align-items:center;flex-wrap:wrap;gap:12px;margin-bottom:12px}.transporter-console h2{margin:4px 0}.transporter-console [data-selector]{margin-left:auto}
   .transporter-console .transport-panels{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(300px,1fr);gap:20px}.transporter-console section{min-width:0}.transporter-console .transport-scene{width:100%;height:clamp(220px,40dvh,490px);object-fit:cover;border:1px solid #6c8aa9;border-radius:4px}
   .transporter-console label:not([data-passengers] label){display:block;margin:10px 0}.transporter-console select{width:100%;min-width:0}.transporter-console .transport-status{min-height:2.5em;color:#ffdd94}.transporter-console [data-person]{width:20px;height:20px;min-height:20px;display:inline-block;margin-right:8px;vertical-align:middle}.transporter-console [data-passengers] label{display:block;padding:6px}
   .transporter-console [data-map-focus]{display:block;width:100%;margin:10px 0;padding:12px;background:#164a65;color:#fff}.transporter-console details{margin:10px 0}.transporter-console .transport-seat{display:flex;align-items:center;justify-content:flex-end;gap:12px;margin-top:16px}.transporter-console [data-hold]{flex:0 0 72px;width:72px;height:72px;min-width:72px;max-width:72px}
   @media(max-width:720px){.transporter-console .transport-panels{grid-template-columns:1fr}.transporter-console .transport-scene{height:220px}}
  </style><header><div><small>${esc(unit.characterName)} / ENGINEERING</small><h2>TRANSPORTER</h2></div><div data-selector></div><button data-sound aria-label="Toggle sound">${b.soundIcon()}</button><button data-close>Combat View</button></header><div class="transport-panels"><section><img class="transport-scene" src="transport-scrambler-console-scene.webp" alt="Transport field control chamber"><p>Four stations · Up to five passengers · 8 Units · Both shields down</p><p>Passengers must be inside this room. Reusable transponders are issued automatically. Boarding another ship needs Lock-On and Systems Analysis.</p><fieldset><legend>Passengers (maximum five)</legend><div data-passengers></div></fieldset></section><section><h3>Transport Destination</h3><label>Destination <select data-target aria-label="Transport destination"></select></label><div data-arrival><button data-map-focus>Choose Arrival on Ship Map</button><output data-location role="status">Complete Systems Analysis to choose an arrival location.</output><details><summary>Choose by room and coordinates</summary><label>Arrival square <select data-square aria-label="Arrival square"></select></label></details></div><p data-risk></p><p data-phase></p><p data-blocked class="transport-status" role="status"></p><button data-send style="background:#165f52;color:white;padding:16px;width:100%">Energize / 12 active seconds</button><output data-status role="status" style="display:block;margin:12px 0;color:#ffdd94"></output><div class="transport-seat"><button data-hold>Hold</button><button data-leave>Leave Console</button></div></section></div>`;
  const get=s=>d.querySelector(s),person=()=>b.state()?.units?.find(u=>u.id===unit.id),selected=()=>[...d.querySelectorAll('[data-person]:checked')].map(e=>e.value);
  let busy=false,signature='',targetSignature='',layoutSignature='',arrivalView=null;const passengerChoices=new Map(),arrivalChoices=new Map();
  function squares(a){
   const targetId=get('[data-target]').value,target=b.state()?.starships?.find(s=>s.id===targetId),known=target?window.SAShipSensors.analysis(a.ship,targetId):null,layout=target?arrivalLayout(a.ship,targetId):null,key=JSON.stringify([targetId,known?.at,!!layout]);
   get('[data-arrival]').hidden=!target;get('[data-map-focus]').disabled=!layout;get('[data-map-focus]').title=layout?'Choose a floor square on the analyzed ship.':'Complete Systems Analysis first.';
   if(key===layoutSignature)return;layoutSignature=key;get('[data-square]').replaceChildren();
   if(!layout){get('[data-location]').textContent='Complete Systems Analysis to choose an arrival location.';return;}
   const l=window.SAShipMap.buildLayout(layout);get('[data-square]').innerHTML='<option value="">Choose an arrival location…</option>'+[...l.hull].filter(s=>!l.footprint.get(s)?.blocked).map(s=>{const cell=l.footprint.get(s),hidden=layout.screenedRooms?.find(r=>r.cells.includes(s));return `<option value="${s}">${esc(hidden?.name||(cell?window.SAShipMap.definition(cell.type).name:'Corridor'))} — row ${Math.floor(s/l.columns)+1}, column ${s%l.columns+1}</option>`;}).join('');
   const remembered=arrivalChoices.get(targetId);if(remembered!==undefined&&[...get('[data-square]').options].some(o=>o.value===remembered))get('[data-square]').value=remembered;locationSummary();
  }
  function locationSummary(){const select=get('[data-square]');get('[data-location]').textContent=select.value!==''?select.selectedOptions[0]?.textContent:'No arrival location chosen. Select one on the map.';}
  function redraw(){
   const room=b.state(),p=person(),a=window.SAStationAccess.access(room,p,sicId);if(!p||!a){d.close();return;}
   const l=window.SAShipMap.buildLayout(a.ship.ship),people=room.units.filter(u=>u.currentHp>0&&!u.shipAi&&u.location?.starshipId===a.ship.id&&l.footprint.get(u.location.square)?.sicId===sicId),sig=JSON.stringify(people.map(u=>[u.id,u.characterName]));
   if(sig!==signature){get('[data-passengers]').innerHTML=people.map(u=>{if(!passengerChoices.has(u.id))passengerChoices.set(u.id,Boolean(u.location.stationed));return `<label><input type="checkbox" data-person value="${esc(u.id)}" ${passengerChoices.get(u.id)?'checked':''}> ${esc(u.characterName)}</label>`;}).join('')||'Move passengers into this Transporter room first.';signature=sig;}
   const targets=[...room.starships.filter(s=>s.id!==a.ship.id&&!s.destroyedAt&&!s.escapedAt&&!s.isProbe&&!s.isDrone&&!s.isMissile).map(s=>({id:s.id,name:s.title})),...(room.spaceObjects||[]).filter(o=>o.kind==='planet'&&!o.destroyed&&!o.destroyedAt).map(o=>({id:o.id,name:o.name+' / surface'}))],ts=JSON.stringify(targets);
   if(ts!==targetSignature){const old=get('[data-target]').value;get('[data-target]').innerHTML=targets.map(t=>`<option value="${esc(t.id)}">${esc(t.name)}</option>`).join('');if(targets.some(t=>t.id===old))get('[data-target]').value=old;targetSignature=ts;}
   squares(a);
   const risk=Number(a.item.impairmentPoints)||(a.item.impaired?1:0);get('[data-risk]').textContent=risk?`WARNING: ${Math.min(100,risk*10)}% fatality risk per passenger. One standard D10 per selected passenger, in listed order.`:'Transporter integrity nominal.';get('[data-risk]').style.color=risk?'#ff7272':'#90edd6';
   const pending=p.delayedAction,targetId=get('[data-target]').value,target=room.starships.find(s=>s.id===targetId),positions=window.SAShipDistances.positions(room.starships,room.shipPositions),from=positions.find(s=>s.id===a.ship.id),to=target?positions.find(s=>s.id===targetId):room.spaceObjects?.find(o=>o.id===targetId),distance=from&&to?window.SAShipDistances.hexDistance(from,to):null,ids=selected();
   get('[data-phase]').textContent=pending?.transporterOrder?'Transport sequence: '+Math.ceil(pending.remaining/pending.rate)+' active seconds remaining.':distance!==null?'Destination range: '+Number(distance.toFixed(1))+' / 8 units.':'';
   const reason=room.practice?'Prepare an encounter to use the Transporter.':a.blocked?'Restore local control and power before transporting.':a.controlled?'Transporter requires a local station or your own Bridge.':pending||p.timedAction||p.delayTimer?'Finish the current action.':p.consoleHold?'Resume your turn to energize.':room.activeId!==p.id?'Wait for your turn.':!ids.length?'Select one to five passengers.':ids.length>5?'Maximum five passengers.':!targetId?'No ship or planet is available.':a.ship.currentShieldHp>0?'Lower your ship’s shields first.':distance!==null&&distance>8+1e-7?'Destination is beyond the 8-unit transport range.':target&&!arrivalLayout(a.ship,targetId)?'Complete Systems Analysis of the destination ship first.':target&&!window.SAShipLocks.locked(room,a.ship,targetId)?'Lock-On to the destination ship first.':target?.currentShieldHp>0?'Lower the destination ship’s shields first.':target&&get('[data-square]').value===''?'Choose an arrival location on the map.':people.some(u=>ids.includes(u.id)&&(u.carriedBy||u.carryingId||u.timedAction||u.id!==p.id&&(u.delayedAction||u.delayTimer)))?'Passengers must finish their actions and cannot carry a patient.':'';
   get('[data-blocked]').textContent=reason||'Ready to transport selected passengers.';get('[data-send]').disabled=busy||Boolean(reason);get('[data-leave]').disabled=busy||Boolean(pending||p.timedAction||p.delayTimer);get('[data-hold]').hidden=Boolean(room.practice);get('[data-hold]').disabled=busy||(!p.consoleHold&&(room.activeId!==p.id||Boolean(pending||p.timedAction||p.delayTimer)));
  }
  get('[data-target]').onchange=()=>{get('[data-status]').textContent='';redraw();};get('[data-square]').onchange=()=>{arrivalChoices.set(get('[data-target]').value,get('[data-square]').value);locationSummary();redraw();};
  get('[data-passengers]').onchange=e=>{if(e.target.matches('[data-person]'))passengerChoices.set(e.target.value,e.target.checked);redraw();};
  get('[data-map-focus]').onclick=()=>{const p=person(),a=window.SAStationAccess.access(b.state(),p,sicId),targetId=get('[data-target]').value,target=b.state()?.starships?.find(s=>s.id===targetId),layout=a&&arrivalLayout(a.ship,targetId);if(!layout||!target)return;arrivalView=window.SASensorSnapshot.open({title:target.title,layout},{selectedSquare:get('[data-square]').value===''?null:Number(get('[data-square]').value),onSelect:square=>{if(get('[data-target]').value!==targetId)return;get('[data-square]').value=String(square);get('[data-square]').dispatchEvent(new Event('change',{bubbles:true}));}});};
  get('[data-send]').onclick=async()=>{redraw();if(busy||get('[data-send]').disabled)return;if(!b.confirmGmPlayerAction(person(),'transport'))return;busy=true;const body={id:unit.id,sicId,kind:'transport',targetId:get('[data-target]').value,square:Number(get('[data-square]').value),passengerIds:selected(),receipt:crypto.randomUUID()};redraw();try{await b.utilityAction(body);get('[data-status]').textContent='Transport sequence started.';}catch(e){get('[data-status]').textContent=e.message;}finally{busy=false;redraw();}};
  get('[data-close]').onclick=()=>d.close();get('[data-sound]').onclick=()=>b.toggleSound();get('[data-leave]').onclick=()=>{const p=person();if(!p||!b.confirmGmPlayerAction(p,'leaveStation'))return;d.close();if(!b.state()?.practice)window.SACombatMap.openMove(p);};get('[data-hold]').onclick=()=>window.SAShipNavigationUI.toggleHold(person()).catch(e=>get('[data-status]').textContent=e.message);
  window.SAShipNavigationUI.mountSelector(get('[data-selector]'),unit,sicId,()=>d.close());
  doc.body.append(d);d.showModal();redraw();window.SAConsoleCommon.mount(d,unit);const timer=setInterval(redraw,250),close=()=>d.close();window.addEventListener('pagehide',close,{once:true});d.addEventListener('close',()=>{clearInterval(timer);window.removeEventListener('pagehide',close);arrivalView?.close();d.remove();openView=null;b.requestRender();},{once:true});
 }};
})();
