(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let openView;
 window.SATransporterConsole={open(unit,sicId){if(openView)return;const b=window.SACombatBridge;let doc=document;try{while(doc.defaultView.frameElement)doc=doc.defaultView.parent.document;}catch{}
 const initial=window.SAStationAccess.access(b.state(),unit,sicId);if(!initial)return;const d=doc.createElement('dialog');openView=d;d.className='transporter-console';d.setAttribute('aria-label','Transporter console');d.style.cssText='width:min(1100px,96vw);max-height:94dvh;background:#071a24;color:#e3f9ff;border:1px solid #61e6ff;padding:20px;box-sizing:border-box';
 d.innerHTML=`<header style="display:flex;align-items:center;justify-content:space-between;gap:20px"><div><small>${esc(unit.characterName)} / ENGINEERING</small><h2>TRANSPORTER</h2></div><button data-close>Combat View</button></header><div style="display:grid;grid-template-columns:minmax(0,1fr) minmax(260px,1fr);gap:20px"><section><img src="sic-art-transporter.webp" alt="Transporter chamber" style="width:100%;max-height:36vh;object-fit:cover"><p>Four stations · Up to five passengers · 8 Units · Both shields down</p><p>Passengers must be inside this room. Reusable transponders are issued automatically from the fifty included. Boarding needs Lock-On and Systems Analysis.</p><fieldset><legend>Passengers (maximum five)</legend><div data-passengers></div></fieldset></section><section><label>Destination <select data-target aria-label="Transport destination" style="width:100%"></select></label><label data-square-label>Arrival square <select data-square aria-label="Arrival square" style="width:100%"></select></label><p data-risk></p><p data-phase></p><p data-blocked style="color:#ffdd94"></p><button data-send style="background:#165f52;color:white;padding:16px;width:100%">Energize / 12 active seconds</button><output data-status role="status" style="display:block;margin:12px 0;color:#ffdd94"></output><button data-leave>Leave Console</button><button data-hold>Hold</button></section></div>`;
 const get=s=>d.querySelector(s);let busy=false,signature='',targetSignature='';const selected=()=>[...d.querySelectorAll('[data-person]:checked')].map(e=>e.value);
 function squares(){const target=b.state().starships.find(s=>s.id===get('[data-target]').value);get('[data-square-label]').hidden=!target;if(!target)return;const l=window.SAShipMap.buildLayout(target.ship),old=get('[data-square]').value;get('[data-square]').innerHTML=[...l.hull].filter(s=>!l.footprint.get(s)?.blocked).map(s=>`<option value="${s}">${s+1} — ${esc(l.footprint.get(s)?.label||'Corridor')}</option>`).join('');if([...get('[data-square]').options].some(o=>o.value===old))get('[data-square]').value=old;}
 function redraw(){const room=b.state(),person=room.units.find(u=>u.id===unit.id),a=window.SAStationAccess.access(room,person,sicId);if(!person||!a){d.close();return;}const l=window.SAShipMap.buildLayout(a.ship.ship),people=room.units.filter(u=>u.currentHp>0&&!u.shipAi&&u.location?.starshipId===a.ship.id&&l.footprint.get(u.location.square)?.sicId===sicId),sig=JSON.stringify(people.map(u=>[u.id,u.characterName]));if(sig!==signature){const ids=selected();get('[data-passengers]').innerHTML=people.map(u=>`<label style="display:block;padding:6px"><input type="checkbox" style="width:20px;height:20px;min-height:20px;display:inline-block;margin-right:8px;vertical-align:middle" data-person value="${esc(u.id)}" ${ids.includes(u.id)||u.location.stationed?'checked':''}> ${esc(u.characterName)}</label>`).join('')||'Move passengers into this Transporter room first.';signature=sig;}
 const targets=[...room.starships.filter(s=>s.id!==a.ship.id&&s.ship?.gridCells?.length&&!s.destroyedAt&&!s.isProbe&&!s.isDrone&&!s.isMissile).map(s=>({id:s.id,name:s.title})),...(room.spaceObjects||[]).filter(o=>o.kind==='planet'&&!o.destroyed).map(o=>({id:o.id,name:o.name+' / surface'}))],ts=JSON.stringify(targets);if(ts!==targetSignature){const old=get('[data-target]').value;get('[data-target]').innerHTML=targets.map(t=>`<option value="${esc(t.id)}">${esc(t.name)}</option>`).join('');if(targets.some(t=>t.id===old))get('[data-target]').value=old;targetSignature=ts;squares();}
 const risk=Number(a.item.impairmentPoints)||(a.item.impaired?1:0);get('[data-risk]').textContent=risk?`WARNING: ${Math.min(100,risk*10)}% fatality risk per passenger. One standard D10 per selected passenger, in listed order.`:'Transporter integrity nominal.';get('[data-risk]').style.color=risk?'#ff7272':'#90edd6';const pending=person.delayedAction;get('[data-phase]').textContent=pending?.transporterOrder?'Transport sequence: '+Math.ceil(pending.remaining/pending.rate)+' active seconds remaining.':room.practice?'Console preview: prepare an encounter to transport.':'';const ids=selected();get('[data-blocked]').textContent=room.practice?'Prepare an encounter to use the Transporter.':pending?'Sequence in progress.':room.activeId!==person.id?'Wait for your turn.':!ids.length?'Select one to five passengers.':ids.length>5?'Maximum five passengers.':!get('[data-target]').value?'No analyzed ship or planet is available.':'';get('[data-send]').disabled=busy||room.practice||room.activeId!==person.id||!!pending||!ids.length||ids.length>5||!get('[data-target]').value;get('[data-leave]').disabled=busy;}
 get('[data-target]').onchange=squares;get('[data-passengers]').onchange=redraw;get('[data-send]').onclick=async()=>{busy=true;const body={id:unit.id,sicId,kind:'transport',targetId:get('[data-target]').value,square:Number(get('[data-square]').value),passengerIds:selected(),receipt:crypto.randomUUID()};redraw();try{await b.utilityAction(body);get('[data-status]').textContent='Transport sequence started.';}catch(e){get('[data-status]').textContent=e.message;}finally{busy=false;redraw();}};
 get('[data-close]').onclick=()=>{window.SAShipNavigationUI.remember(unit);d.close();};get('[data-leave]').onclick=()=>{d.close();if(!b.state().practice)window.SACombatMap.openMove(unit);};get('[data-hold]').onclick=()=>window.SAShipNavigationUI.toggleHold(unit).catch(e=>get('[data-status]').textContent=e.message);const timer=setInterval(redraw,250);d.onclose=()=>{clearInterval(timer);d.remove();openView=null;b.requestRender();};doc.body.append(d);d.showModal();redraw();d.dataset.sicId=sicId;d.dataset.operatorId=unit.id;d.dataset.standaloneConsole='true';window.SAConsoleCommon.mount(d,unit);
 }};
})();
