(function(){
  const bridge=()=>window.SACombatBridge;
  function roomKey(ship,square){return window.SAShipDoors.roomKey(ship,square);}
  function available(unit,state){const ship=state?.starships?.find(s=>s.id===unit?.location?.starshipId);if(!ship)return {};
    return {ship,airlock:ship.ship.airlocks?.find(a=>a.square===unit.location.square),holes:Object.values(ship.ship.breachState?.holes||{}).filter(h=>!h.sealed&&roomKey(ship,h.square)===roomKey(ship,unit.location.square))};
  }
  async function airlock(unit,ship,a,doc=document){const open=!!ship.ship.airlockStates?.[a.id]?.open;if(!open&&!doc.defaultView.confirm('Open the airlock? This vents the room and may suck everyone inside into space.'))return;
    await bridge().action({action:'operateAirlock',id:unit.id,starshipId:ship.id,airlockId:a.id,confirmed:!open},'resolve',{throwOnError:true});
  }
  async function action(kind,unit){try{const info=available(unit,bridge().state());if(kind==='airlock'&&info.airlock)await airlock(unit,info.ship,info.airlock);else if(kind==='breachRepair'&&info.holes?.length){let h=info.holes[0];if(info.holes.length>1){const n=Number(prompt('Repair which breach? '+info.holes.map((h,i)=>`${i+1}: square ${h.square+1}`).join('; ')));h=info.holes[n-1];if(!h)return;}await bridge().action({action:'repairHullBreach',id:unit.id,hazardId:h.id},'resolve',{throwOnError:true});}}catch(e){alert(e.message);}}
  function doors(unit){let doc=document;try{while(doc.defaultView.frameElement&&!doc.defaultView.frameElement.hasAttribute('data-explore-perspective'))doc=doc.defaultView.parent.document;}catch{}
    const shipId=unit.location.starshipId,view=doc.createElement('dialog');view.className='airlock-door-map';view.style.cssText='width:96vw;max-width:none;height:92vh;max-height:none;padding:14px;box-sizing:border-box;background:#07151e;color:#e9faff;border:1px solid #71dbed';
    view.innerHTML='<header style="display:flex;gap:12px;align-items:center"><h2 style="margin:0;flex:1">Door Adjustment</h2><button data-minus>−</button><button data-plus>+</button><button data-fit>Fit Ship</button><button data-close>Close</button></header><p>Click doors or airlocks to open / close. Drag blank space to pan.</p><div data-viewport style="overflow:auto;height:calc(100% - 110px);position:relative"><div data-grid style="display:grid;position:relative;margin:auto"></div></div><p role="status"></p>';
    const style=doc.createElement('style');style.textContent='.airlock-door-map header button{min-width:38px;min-height:36px;background:#163744;color:#fff;border:1px solid #7ca8b8}.airlock-door-map .sa-map-door{min-width:10px!important;min-height:10px!important;z-index:30!important}.airlock-door-map .sa-map-door.is-open{outline:1px solid #7affb5}.airlock-door-map .sa-room-oxygen{display:none}';view.append(style);const link=doc.createElement('link');link.rel='stylesheet';link.href=new URL('ship-map-presentation.css',location.href).href;view.append(link);
    const viewport=view.querySelector('[data-viewport]'),grid=view.querySelector('[data-grid]'),status=view.querySelector('[role=status]');let size=64,last='',bounds;
    const redraw=()=>{const s=bridge().state().starships.find(s=>s.id===shipId);if(!s){view.close();return;}const key=JSON.stringify([s.ship.gridCells,s.ship.placements,s.ship.doorStates,s.ship.doorDamage,s.ship.airlocks,s.ship.airlockStates,s.ship.breachState,size]);if(key===last)return;last=key;
      const l=window.SAShipMap.buildLayout(s.ship),cells=[...l.hull],xs=cells.map(k=>k%l.columns),ys=cells.map(k=>Math.floor(k/l.columns));bounds={minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)};const w=bounds.maxX-bounds.minX+1;grid.style.gridTemplateColumns=`repeat(${w},${size}px)`;grid.style.width=`${w*size}px`;grid.innerHTML='';
      for(let y=bounds.minY;y<=bounds.maxY;y++)for(let x=bounds.minX;x<=bounds.maxX;x++){const sq=y*l.columns+x,cell=doc.createElement('div');cell.className='combat-map-square';cell.style.cssText=`position:relative;width:${size}px;height:${size}px;box-sizing:border-box;${l.hull.has(sq)?'background:#17313c;border:1px solid #34505b':''}`;if(l.hull.has(sq)){const art=l.footprint.get(sq);if(art)cell.style.cssText+=';'+window.SAShipMap.floorplanStyle(art.type,art.column,art.row,art);cell.innerHTML=window.SAShipMap.surfaceMarkup(l,sq)+window.SAShipMap.boundaryMarkup(l,sq,{isOpen:key=>s.ship.doorStates?.[key]==='open',doorAttributes:key=>({'data-door':key})});const a=s.ship.airlocks?.find(a=>a.square===sq);if(a){const b=doc.createElement('button');b.dataset.airlock=a.id;b.textContent=s.ship.airlockStates?.[a.id]?.open?'Close airlock':'Open airlock';b.style.cssText='position:absolute;inset:4%;z-index:25;font-size:11px;background:#102c38bb;color:#fff;border:1px solid #ffe08b';cell.append(b);}else {const label=doc.createElement('span');const part=l.footprint.get(sq);label.textContent=part&&part.column===Math.floor(part.width/2)&&part.row===Math.floor(part.height/2)?part.label:'';label.style.cssText='position:absolute;inset:25% 5%;font-size:10px;color:#ffe9a8;text-shadow:0 1px 2px #000;pointer-events:none';cell.append(label);}}grid.append(cell);}
    };
    const fit=()=>{if(!bounds)return;size=Math.max(18,Math.min(88,Math.floor(Math.min(viewport.clientWidth/(bounds.maxX-bounds.minX+1),viewport.clientHeight/(bounds.maxY-bounds.minY+1)))));redraw();viewport.scrollTop=viewport.scrollLeft=0;};
    view.onclick=async e=>{try{const s=bridge().state().starships.find(s=>s.id===shipId);if(e.target.closest('[data-close]'))view.close();else if(e.target.closest('[data-fit]'))fit();else if(e.target.closest('[data-plus]')){size=Math.min(160,size*1.2);redraw();}else if(e.target.closest('[data-minus]')){size=Math.max(12,size/1.2);redraw();}else if(e.target.closest('[data-airlock]'))await airlock(unit,s,s.ship.airlocks.find(a=>a.id===e.target.closest('[data-airlock]').dataset.airlock),doc);else if(e.target.closest('[data-door]'))await bridge().action({action:'operateCombatDoor',id:unit.id,starshipId:shipId,doorKey:e.target.closest('[data-door]').dataset.door},'resolve',{throwOnError:true});redraw();}catch(error){status.textContent=error.message;}};
    let pan;viewport.onpointerdown=e=>{if(e.target.closest('button,[data-door],[data-airlock],input'))return;pan={x:e.clientX,y:e.clientY,l:viewport.scrollLeft,t:viewport.scrollTop};viewport.setPointerCapture(e.pointerId);};viewport.onpointermove=e=>{if(pan){viewport.scrollLeft=pan.l+pan.x-e.clientX;viewport.scrollTop=pan.t+pan.y-e.clientY;}};viewport.onpointerup=viewport.onpointercancel=()=>pan=null;
    const timer=setInterval(redraw,250);view.onclose=()=>{clearInterval(timer);view.remove();};doc.body.append(view);view.showModal();redraw();fit();
  }
  function animateEjections(previous,next){
    for(const u of next?.units||[]){if(!u.vacuum||previous?.units?.find(p=>p.id===u.id)?.vacuum)continue;
      if(bridge().mode()==='gm'||bridge().myUnitId()===u.id)setTimeout(()=>alert(u.characterName+' has been sucked into the vacuum of space! An operational Manipulation Arm can retrieve them by entering their hex.'),750);
      const token=[...document.querySelectorAll('.combat-token')].find(t=>t.title===u.characterName),host=token?.closest('[data-inline-ship-map]')||document,cell=host.querySelector(`[data-map-square="${u.vacuum.holeSquare}"]`);
      if(token&&cell){const start=token.getBoundingClientRect(),end=cell.getBoundingClientRect(),copy=token.cloneNode(true);copy.style.cssText+=`;position:fixed;left:${start.x}px;top:${start.y}px;width:${start.width}px;height:${start.height}px;z-index:2147483647;pointer-events:none`;document.body.append(copy);const a=copy.animate([{transform:'translate(0,0) scale(1)',opacity:1},{transform:`translate(${end.x+end.width/2-start.x}px,${end.y+end.height/2-start.y}px) scale(.05)`,opacity:0}],{duration:700,easing:'ease-in'});a.onfinish=()=>copy.remove();}
    }
  }
  window.SAVacuumUI={available,action,doors,animateEjections};
}());
