const test=require('node:test'),assert=require('node:assert/strict');
const gravity=require('../ship-black-holes'),nav=require('../ship-navigation'),maps=require('../ship-map-core'),power=require('../ship-power'),objects=require('../space-objects');
test('black holes pull every scenery kind and consume its center, retaining partial cadence through saves',()=>{
 for(const kind of ['mineral','asteroid','object','planet']){
  const {room}=fixture(30);room.spaceObjects.push({id:'object-cargo',kind,name:'Cargo',quantity:1,mineral:'Iron',q:2,r:0});
  nav.advance(room,2.5);assert.ok(Math.abs(room.spaceObjects[1].q-1.5)<1e-8);
  room.spaceObjects=objects.normalize(room.spaceObjects.map(o=>({...o,name:o.name||'Hole',quantity:1})));
  nav.advance(room,2.5);assert.ok(Math.abs(room.spaceObjects[1].q-1)<1e-8);
  nav.advance(room,2.5);assert.equal(room.spaceObjects.length,1);assert.equal(room.spaceObjects[0].kind,'black-hole');
 }
});
test('invalid elapsed time cannot trap navigation in an endless gravity loop',()=>{const {room}=fixture();nav.advance(room,Infinity);nav.advance(room,NaN);assert.equal(room.shipPositions[0].q,2);});
function fixture(q=2,intensity=3){const ship={id:'s',title:'Test ship',currentHullHp:100,currentShieldHp:100,ship:{gridCells:[0],placements:[],sicInventory:[],mapHeading:83}};return {ship,room:{starships:[ship],shipPositions:[{id:'s',q,r:0}],spaceObjects:[{id:'object-hole',kind:'black-hole',intensity,q:0,r:0}],units:[]}};}
test('black hole normalization retains and validates intensity',()=>{const o={id:'object-test',kind:'black-hole',name:'Hole',quantity:1,q:0,r:0,intensity:15};assert.equal(objects.normalize([o])[0].intensity,15);assert.throws(()=>objects.normalize([{...o,intensity:0}]),/intensity/);});
test('clarified strength is intensity minus hex distance',()=>{const {room}=fixture(3,15);assert.equal(gravity.strength(room.spaceObjects[0],room.shipPositions[0]),12);assert.equal(gravity.strength({...room.spaceObjects[0],intensity:3},room.shipPositions[0]),0);});
test('pull spreads across five active seconds, strengthens next cycle, ignores shields and preserves heading',()=>{const {room,ship}=fixture();nav.advance(room,2.5);assert.ok(Math.abs(room.shipPositions[0].q-1.5)<1e-8);nav.advance(room,2.5);assert.ok(Math.abs(room.shipPositions[0].q-1)<1e-8);assert.equal(ship.ship.mapHeading,83);nav.advance(room,12);assert.equal(room.shipPositions[0].q,0);assert.equal(ship.currentHullHp,0);assert.equal(ship.currentShieldHp,100);});
test('large pull stops at center and never overshoots',()=>{const {room,ship}=fixture(3,15);nav.advance(room,12);assert.equal(room.shipPositions[0].q,0);assert.equal(ship.currentHullHp,0);});
test('movement penalty is applied without exposing a changed vector or speed',()=>{const {room,ship}=fixture();ship.navigation={phase:'powered',baseSpeed:3,speed:3,boosts:[],traveled:0,direction:{q:1,r:0},target:{q:30,r:0},remaining:100};nav.advance(room,1);assert.ok(room.shipPositions[0].q>2&&room.shipPositions[0].q<2.3);assert.equal(ship.navigation.speed,3);assert.deepEqual(ship.navigation.direction,{q:1,r:0});});
test('powered field permits entering center; impairment removes immunity',()=>{const {room,ship}=fixture(0);ship.ship.sicInventory=[{id:'g',type:'gravity-absolution-field'},{id:'s',type:'shield-1'},{id:'a',type:'au-engine-6'},{id:'e',type:'en-engine-6'}];ship.ship.placements=ship.ship.sicInventory.map((i,n)=>({sicId:i.id,cell:n}));ship.ship.gravityFieldState={sicId:'g',active:true,remaining:12,receipts:[]};power.refresh(room,{reset:true});nav.advance(room,1);assert.equal(ship.currentHullHp,100);ship.ship.sicInventory[0].impaired=true;nav.advance(room,1);assert.equal(ship.currentHullHp,0);});
test('SIC data and Menace placements are complete, unique and within their intended hull',()=>{assert.equal(maps.definition('gravity-absolution-field').cardNumber,'B-78');assert.equal(maps.definition('land-wheels').cardNumber,'B-72');const s=require('../showcase-menace')().ship,used=new Set();assert.equal(s.gridCells.length,343);for(const p of s.placements){const i=s.sicInventory.find(i=>i.id===p.sicId);for(const n of maps.placementSquares(s,i,p)){assert.ok(!used.has(n),i.type+' overlaps');used.add(n);}}assert.equal(maps.exteriorError(s),'');});
function fieldFixture(){const ship=require('../showcase-menace')();ship.currentHullHp=343;ship.maximumHullHp=343;const g=ship.ship.sicInventory.find(i=>maps.definition(i.type).gravityField),p=ship.ship.placements.find(p=>p.sicId===g.id),seat=maps.componentDefinition(g).stations[0];const unit={id:'pilot',characterId:'pc',currentHp:20,atb:100,location:{starshipId:ship.id,square:p.cell+seat.y*maps.gridColumns(ship.ship)+seat.x,mesh:seat.mesh,sicId:g.id,stationed:true}};const room={activeId:unit.id,units:[unit],starships:[ship],shipPositions:[{id:ship.id,q:10,r:0}],spaceObjects:[]};power.refresh(room,{reset:true});require('../ship-shields').refresh(room,{reset:true});return{room,ship,unit,g};}
test('field activation is receipt-safe, drains AU and suspends shield protection without erasing layers',()=>{const {room,ship,unit,g}=fieldFixture(),shields=require('../ship-shields'),health=require('../health-display');const before=ship.auState.available,body={sicId:g.id,enabled:true,receipt:'gravity-activation'};assert.equal(gravity.command(room,unit,body).ok,true);assert.equal(ship.auState.available,before-3);assert.equal(gravity.command(room,unit,body).duplicate,true);assert.equal(ship.auState.available,before-3);const hp=Object.values(ship.shieldSystems).map(s=>s.hp);shields.refresh(room);assert.equal(ship.currentShieldHp,0);assert.ok(health.shieldLayers(ship).every(s=>s.current===0));shields.damage(room,ship.id,5);assert.equal(ship.currentHullHp,338);assert.deepEqual(Object.values(ship.shieldSystems).map(s=>s.hp),hp);gravity.advance(room,12,[],false);assert.equal(ship.auState.available,before-6);assert.equal(gravity.command(room,unit,{...body,enabled:false,receipt:'gravity-deactivation'}).ok,true);shields.refresh(room);assert.ok(ship.currentShieldHp>0);});
test('cloak grants 50 stationary, 25 moving and 10 with shields, then charges its twelve-second upkeep',()=>{const {room,ship}=fieldFixture(),cloak=ship.ship.sicInventory.find(i=>maps.definition(i.type).cloaking);ship.currentShieldHp=0;const base=maps.masking(ship);ship.ship.cloakState={active:true,sicId:cloak.id,remaining:12,receipts:[]};assert.equal(maps.masking(ship)-base,50);ship.navigation={phase:'powered',speed:3};assert.equal(maps.masking(ship)-base,25);ship.navigation.phase='drift';assert.equal(maps.masking(ship)-base,25);ship.currentShieldHp=10;assert.equal(maps.masking(ship)-base,10);assert.ok(require('../health-display').shieldLayers(ship).some(l=>l.current>0));const before=ship.auState.available;power.advance(room,12);assert.equal(ship.auState.available,before-12);ship.auState.current=0;ship.auState.available=0;power.advance(room,12);assert.equal(ship.ship.cloakState.active,false);});
test('Land Wheels accept four distinct exterior mounts and reject duplicate mounts',()=>{const s={zoneColumns:40,zoneRows:40,gridCells:[82,83,122,123],sicInventory:[{id:'w',type:'land-wheels'}],placements:[{sicId:'w',cell:42,mountCells:[42,43,162,163]}]};assert.equal(maps.exteriorError(s),'');s.placements[0].mountCells[3]=162;assert.match(maps.exteriorError(s),/four separate exterior mounts/);});

test('gravity sampling survives save/load and different tick partitions',()=>{const a=fixture(8,10),b=fixture(8,10);nav.advance(a.room,20);for(let n=0;n<20;n++){nav.advance(b.room,1);b.room=JSON.parse(JSON.stringify(b.room));}assert.ok(Math.abs(a.room.shipPositions[0].q-b.room.shipPositions[0].q)<1e-8);});
test('gravity bends travel without moving the commanded destination',()=>{const {room,ship}=fixture(2,3);ship.navigation={phase:'powered',baseSpeed:3,speed:3,boosts:[],traveled:0,direction:{q:0,r:1},target:{q:2,r:10},remaining:100};nav.advance(room,2);assert.deepEqual(ship.navigation.target,{q:2,r:10});assert.ok(room.shipPositions[0].q<2);});

test('five-second field is stronger and still uses active simulation time',()=>{const {room,ship}=fixture();let elapsed=0,atb=0,actions=0;while(ship.currentHullHp>0&&elapsed<60){nav.advance(room,.1);elapsed+=.1;atb+=.5;if(atb>=100-1e-7){actions++;atb-=100;}}assert.ok(elapsed>=6.2&&elapsed<=6.5);assert.equal(actions,0);const before=structuredClone(room.shipPositions);nav.advance(room,0);assert.deepEqual(room.shipPositions,before);});


test('travel into gravity speeds toward center instead of applying a universal speed reduction',()=>{const {room,ship}=fixture(2,3);ship.navigation={phase:'powered',baseSpeed:3,speed:3,boosts:[],traveled:0,direction:{q:-1,r:0},target:{q:-10,r:0},remaining:100};nav.advance(room,1);assert.ok(room.shipPositions[0].q<1.7);assert.equal(ship.navigation.speed,3);});
test('saved old gravity cadence restarts with a five-second sample',()=>{const {room,ship}=fixture();ship.ship.gravityFieldState={active:false,pullCycle:{remaining:23,fields:[{id:'object-hole',amount:1}]}};nav.advance(room,2.5);assert.ok(Math.abs(room.shipPositions[0].q-1.5)<1e-8);assert.equal(ship.ship.gravityFieldState.pullCycle.period,5);});
