const test=require('node:test'),assert=require('node:assert/strict'),gun=require('../ship-black-hole-gun'),navigation=require('../ship-navigation'),maps=require('../ship-map-core'),objects=require('../space-objects');
function fixture(){const f=require('./helpers/devastation-fixture.cjs')();f.ship.ship.sicInventory.find(i=>i.id==='gun').type='black-hole-gun';f.ship.ship.placements.find(p=>p.sicId==='gun').exteriorCell=46;f.ship.ship.minerals={'Dark Phazon':3};f.room.spaceObjects=[];f.room.shipPositions[1].q=20;f.body={sicId:'gun',kind:'black-hole-launch',receipt:'black-hole-test-001',q:5,r:0,intensity:3};return f;}
test('Black Hole Gun has complete build, crafting, cost and impairment metadata',()=>{const f=fixture(),d=maps.definition('black-hole-gun');assert.equal(maps.exteriorError(f.ship.ship),'');assert.equal(d.energyCost,4);assert.equal(d.threshold,17);assert.equal(require('../ship-fabrication').recipe('black-hole-gun').seconds,21*86400);assert.deepEqual([1,2,3,4].map(gun.cost),[1,3,6,10]);});
test('launch consumes exact resources once, rejects receipt reuse and locks cooldown',()=>{const f=fixture(),before=f.ship.auState.current;assert.equal(gun.command(f.room,f.unit,f.body).ok,true);assert.equal(f.ship.auState.current,before-6);assert.equal(f.ship.ship.minerals['Dark Phazon'],2);assert.equal(gun.command(f.room,f.unit,f.body).duplicate,true);assert.equal(f.room.spaceObjects.length,1);assert.equal(gun.command(f.room,f.unit,{...f.body,q:4}).ok,false);assert.match(gun.command(f.room,f.unit,{...f.body,receipt:'black-hole-second'}).error,/cooling/);});
test('orb travels 1 hex per 12 active seconds, then decays after each full fifteen-second interval',()=>{const f=fixture();gun.command(f.room,f.unit,f.body);navigation.advance(f.room,12);assert.ok(Math.abs(f.room.spaceObjects[0].q-1)<1e-7);navigation.advance(f.room,47.9);assert.ok(f.room.spaceObjects[0].gunOrb);navigation.advance(f.room,.1);assert.equal(f.room.spaceObjects[0].kind,'black-hole');assert.equal(f.room.spaceObjects[0].intensity,3);navigation.advance(f.room,14.9);assert.equal(f.room.spaceObjects[0].intensity,3);navigation.advance(f.room,.1);assert.equal(f.room.spaceObjects[0].intensity,2);navigation.advance(f.room,30);assert.equal(f.room.spaceObjects.length,0);});
test('formed black hole threatens its firing ship without a friendly exception',()=>{const f=fixture();f.body.q=0;f.body.intensity=1;gun.command(f.room,f.unit,f.body);navigation.advance(f.room,.25);assert.equal(f.ship.currentHullHp,0);});
test('normalization preserves orb progress and temporary decay, stationary holes do not decay',()=>{const f=fixture();gun.command(f.room,f.unit,f.body);navigation.advance(f.room,12);f.room.spaceObjects=objects.normalize(JSON.parse(JSON.stringify(f.room.spaceObjects)));assert.ok(f.room.spaceObjects[0].gunOrb);navigation.advance(f.room,48);f.room.spaceObjects=objects.normalize(f.room.spaceObjects);assert.equal(f.room.spaceObjects[0].gunDecay.remaining,15);f.room.spaceObjects.push({id:'object-permanent',kind:'black-hole',q:100,r:0,intensity:10});navigation.advance(f.room,45);assert.equal(f.room.spaceObjects.length,1);assert.equal(f.room.spaceObjects[0].intensity,10);});
test('launch rejects invalid range, fractional AU intensity, missing minerals and Ship AI',()=>{for(const change of [{q:6},{intensity:1.5},{intensity:0}]){const f=fixture();assert.equal(gun.command(f.room,f.unit,{...f.body,...change}).ok,false);assert.equal(f.ship.ship.minerals['Dark Phazon'],3);}const f=fixture();f.unit.shipAi=true;assert.match(gun.command(f.room,f.unit,f.body).error,/never spends/);f.unit.shipAi=false;f.ship.ship.minerals={};assert.match(gun.command(f.room,f.unit,f.body).error,/Dark Phazon/);});

test('gun time pauses and survives reload without losing flight, cost or cooldown',()=>{const f=fixture();gun.command(f.room,f.unit,f.body);gun.advance(f.room,6);const saved=JSON.parse(JSON.stringify(f.room));saved.hardPaused=true;gun.advance(saved,90);assert.equal(saved.spaceObjects[0].gunOrb.remaining,54);assert.equal(saved.starships[0].ship.blackHoleGunState.cooldowns.gun,354);saved.hardPaused=false;gun.advance(saved,6);assert.equal(saved.spaceObjects[0].gunOrb.remaining,48);assert.equal(saved.starships[0].ship.minerals['Dark Phazon'],2);});
test('Gravity Absolution protects against the gun center while an unprotected ship dies',()=>{const f=fixture();f.body.q=0;f.ship.ship.sicInventory.push({id:'field',type:'gravity-absolution-field'},{id:'shield',type:'shield-1'});f.ship.ship.placements.push({sicId:'field',cell:152},{sicId:'shield',cell:153});f.ship.ship.gravityFieldState={active:true,sicId:'field',remaining:12,receipts:[]};gun.command(f.room,f.unit,f.body);gun.advance(f.room,.25);assert.equal(f.ship.currentHullHp,100);});
test('captured gun spends the captured ship resources and can fire back at itself',()=>{const f=fixture(),origin={id:'hack-ship',ship:{gridCells:[0],sicInventory:[{id:'cp',type:'cockpit-1'}],placements:[{sicId:'cp',cell:0}]}};f.room.starships.push(origin);f.unit.location={starshipId:origin.id,square:0,mesh:0,stationed:true,sicId:'cp'};f.room.hackingGrants=[{unitId:f.unit.id,targetId:f.ship.id,sicId:'gun'}];f.body.q=0;const result=gun.command(f.room,f.unit,f.body);assert.equal(result.ok,true,result.error);assert.equal(f.ship.ship.minerals['Dark Phazon'],2);gun.advance(f.room,.25);assert.equal(f.ship.currentHullHp,0);});

test('gun exterior uses bounded weapon art rather than a thruster assembly',()=>{const f=fixture(),layout=maps.buildLayout(f.ship.ship),square=[...layout.footprint].find(([,c])=>c.sicId==='gun'&&c.exterior&&c.offset===0)[0],html=maps.surfaceMarkup(layout,square);assert.match(html,/sa-exterior-weapon/);assert.doesNotMatch(html,/sa-exterior-thruster/);const shift=Number(html.match(/--art-shift-y:([-\d.]+)/)[1]);assert.ok(Math.abs(shift)<=.51,'Barrel must remain inside its exterior footprint');});
