const test=require('node:test'),assert=require('node:assert/strict');
const {CampaignApi}=require('../campaign-api');
function fixture(){const records=new Map();const store={get:async code=>structuredClone(records.get(code)||null),create:async c=>{if(records.has(c.code))return false;records.set(c.code,structuredClone(c));return true;},save:async c=>records.set(c.code,structuredClone(c)),findByName:async()=>[]};let api=new CampaignApi({store,storageMode:'test'});
const call=async(path,body={},status=200)=>{let result;await api.handle({method:'POST'},{},new URL('http://test/api/campaign/'+path),async()=>body,(_,code,value)=>{assert.equal(code,status,JSON.stringify(value));result=value;});return result;};
return{call,restart:()=>{api=new CampaignApi({store,storageMode:'test'});},api:()=>api,records};}

test('Explore galaxy edits use authenticated temporary rooms without opening other v0.3 actions',async()=>{
 const f=fixture(),room=await f.call('showcase/start'),code=room.code,token=room.gmToken,c=await f.api().campaign(code),mapId=c.starmaps.maps[0].id;
 assert.equal(c.shipCredits,9999999);
 const edit=await f.call('v03/starmap',{code,token,kind:'star',receipt:'add-star',mapId,name:'Mouse Test',q:2,r:3,lore:'Saved through the real Explore route'});
 const star=edit.campaign.starmaps.maps[0].stars.find(s=>s.name==='Mouse Test');assert.ok(star);assert.equal(star.q,2);
 await f.call('v03/starmap',{code,token,kind:'star',receipt:'move-star',mapId,starId:star.id,name:'Mouse Test',q:4,r:1});assert.equal((await f.api().campaign(code)).starmaps.maps[0].stars.find(s=>s.id===star.id).q,4);
 await f.call('v03/starmap',{code,kind:'create',name:'No session'},403);
 await f.call('v03/starmap',{code,token:room.players[0].token,kind:'create',receipt:'forbidden',name:'PC cannot edit'},400);
 await f.call('v03/import',{code,token,kind:'ship',data:{}},404);
 assert.equal(f.records.size,0,'Explore edits must remain disposable');
 const roadTrip=c.starships.find(s=>s.title==='Road Trip');
 roadTrip.ship.warpState={phase:'activating',remaining:60,targetLY:3.26,traveledLY:0,plan:['large private plan']};
 f.api().session(token,code).compactShowcase=true;
 const brief=f.api().state(c,token).starships.find(s=>s.id===roadTrip.id);
 assert.equal(brief.lazyLayout,true);assert.deepEqual(brief.ship.warpState,{phase:'activating',remaining:60,targetLY:3.26,traveledLY:0});assert.equal(brief.ship.sicInventory.length,0);
});
test('v0.3 file-owned rooms keep exclusive player links through refresh/restart and portable saves omit sessions',async()=>{
 const f=fixture(),room=await f.call('v03/create',{name:'Fresh room'},201),code=room.campaign.code,gm=room.token;
 const a=await f.call('v03/join',{code,name:'Jason'}),b=await f.call('v03/join',{code,name:'Alex'});
 const created=await f.call('v03/character/create',{code,token:a.token,password:'',character:{phase:'finalized',identity:{characterName:'Nova'},resources:{},statistics:{experienceEarned:12}}});const cid=created.campaign.ownCharacterId;
 assert.equal(created.campaign.characters[0].character.identity.playerName,'Jason');assert.equal(created.campaign.role,'character');
 await f.call('v03/claim',{code,token:b.token,characterId:cid,password:''},400);
 await f.call('v03/character/create',{code,token:a.token,character:{}},400);
 await f.call('v03/import',{code,token:a.token,kind:'character',data:{phase:'finalized'}},400);
 f.restart();const current=await f.api().campaign(code);assert.equal(f.api().session(a.token,code).characterId,cid);assert.ok(f.api().gmSession(gm,code));
 await f.call('v03/abandon',{code,token:a.token});const claimed=await f.call('v03/claim',{code,token:b.token,characterId:cid,password:''});assert.equal(claimed.campaign.ownCharacterId,cid);
 const other=await f.call('v03/join',{code,name:'Sam'});await f.call('v03/import',{code,token:other.token,kind:'character',data:{phase:'finalized',identity:{characterName:'Visitor'},attributes:{intellect:[1]},access:{pcCode:'DO NOT COPY'},campaignLink:{roomCode:'OTHER'},statistics:{experienceEarned:24}}});
 let state=f.api().state(await f.api().campaign(code),gm);const request=state.imports[0];assert.equal(request.data.access,undefined);assert.equal(request.data.campaignLink,undefined);
 await f.call('v03/import/respond',{code,token:other.token,requestId:request.id,approve:true},403);
 await f.call('v03/import/respond',{code,token:gm,requestId:request.id,approve:true});const imported=await f.call('v03/import/finish',{code,token:other.token,requestId:request.id,password:'a a'});assert.equal(imported.campaign.characters.find(c=>c.id===imported.campaign.ownCharacterId).character.statistics.experienceEarned,24);
 let backup;await f.api().handle({method:'GET'},{},new URL(`http://test/api/campaign/backup?code=${code}&token=${gm}`),async()=>{},(_,status,data)=>{assert.equal(status,200);backup=data;});
 assert.equal(backup.campaign.interfaceVersion,'0.3');assert.equal(backup.campaign.runtimeSessions,undefined);assert.equal(backup.campaign.players,undefined);
 const choice=await f.call('v03/load',{backup});assert.equal(choice.requiresChoice,true);
 const joined=await f.call('v03/load',{backup,choice:'join'});assert.equal(joined.campaign.role,'gm');
 await f.call('v03/close',{code,token:joined.token});await f.call('v03/join',{code,name:'Late'},410);
 const loaded=await f.call('v03/load',{backup});assert.equal(loaded.campaign.code,code);assert.equal(loaded.campaign.roomOpen,true);
});
test('v0.3 room actions reject missing identities and invalid imports',async()=>{
const f=fixture();await f.call('v03/create',{name:''},400);const room=await f.call('v03/create',{name:'Test'},201),code=room.campaign.code;
await f.call('v03/join',{code,name:''},400);await f.call('v03/abandon',{code},403);await f.call('v03/load',{backup:{format:'wrong'}},400);
const p=await f.call('v03/join',{code,name:'Player'});await f.call('v03/import',{code,token:p.token,data:{phase:'draft'}},400);
await f.call('starship/crew',{code,token:p.token},403);
});

test('quick prompts persist independent columns and reverence clicks are receipt-safe',async()=>{const f=fixture(),created=await f.call('v03/create',{name:'Prompts'},201),code=created.campaign.code,gm=created.token,p=await f.call('v03/join',{code,name:'Pat'});const c=await f.call('v03/character/create',{code,token:p.token,password:'',character:{phase:'finalized',identity:{characterName:'Pat'},resources:{reverence:9}}});const id=c.campaign.ownCharacterId,preset={name:'Awareness',attribute:'Perception',skill:'Awareness',difficulty:12};
await f.call('quick-prompts',{code,token:p.token,column:id,presets:[preset]},403);await f.call('quick-prompts',{code,token:gm,column:id,presets:[preset]});await f.call('quick-prompts',{code,token:gm,column:'everyone',presets:[]});await f.call('quick-prompts',{code,token:gm,column:id,presets:[{...preset,difficulty:1.5}]},400);
await f.call('quick-prompts',{code,token:gm,column:id,kind:'reverence',receipt:'a'});await f.call('quick-prompts',{code,token:gm,column:id,kind:'reverence',receipt:'a'});f.restart();const current=await f.api().campaign(code);assert.equal(current.quickPrompts[id][0].difficulty,12);assert.deepEqual(current.quickPrompts.everyone,[]);assert.equal(current.characters[0].character.resources.reverence,9);const reward=current.privateNotes.find(n=>n.rewardResource==='reverence'&&n.rewardStatus==='pending');assert.ok(reward);await f.call('award/claim',{code,token:p.token,characterId:id,noteId:reward.id});await f.call('award/claim',{code,token:p.token,characterId:id,noteId:reward.id});const claimed=await f.api().campaign(code);assert.equal(claimed.characters[0].character.resources.reverence,10);assert.equal(claimed.characters[0].character.statistics.reverenceEarned,1);
await f.call('statistics/roll',{code,token:p.token,characterId:id,skill:'Awareness',score:18.5,receipt:'first'});await f.call('statistics/roll',{code,token:p.token,characterId:id,skill:'Awareness',score:18.5,receipt:'first'});assert.equal((await f.api().campaign(code)).characters[0].character.statistics.skills.Awareness.count,1);
});

test('v0.3 shared ship confirmation rejects stale edits and preserves the accepted layout',async()=>{const f=fixture(),created=await f.call('v03/create',{name:'Ship concurrency'},201),code=created.campaign.code,gm=created.token;const source=require('./helpers/crew-room-fixture.cjs')().ship;source.crewCharacterIds=[];source.buildRevision=0;const campaign=await f.api().campaign(code);campaign.starships=[source];await f.api().save(campaign);const ship={...structuredClone(source.ship),title:'Confirmed New Name'};const result=await f.call('starship/save',{code,token:gm,starship:ship,buildRevision:0});assert.equal(result.starship.buildRevision,1);await f.call('starship/save',{code,token:gm,starship:{...ship,title:'Stale Name'},buildRevision:0},409);assert.equal((await f.api().campaign(code)).starships[0].title,'Confirmed New Name');});

test('changing room code preserves sleeping player sessions through a server restart',async()=>{const f=fixture(),created=await f.call('v03/create',{name:'Persistent links'},201),code=created.campaign.code,p=await f.call('v03/join',{code,name:'Sleeper'});f.restart();await f.api().campaign(code);const moved=await f.call('v03/change-code',{code,token:created.token});assert.notEqual(moved.code,code);f.restart();await f.api().campaign(moved.code);assert.equal(f.api().session(p.token,moved.code).role,'viewer');assert.equal((await f.api().campaign(code)).redirectCode,moved.code);});

test('campaign presence includes connected character streams before any encounter exists',async()=>{const f=fixture(),created=await f.call('v03/create',{name:'Presence'},201),code=created.campaign.code,joined=await f.call('v03/join',{code,name:'QA'});const pc=await f.call('v03/character/create',{code,token:joined.token,password:'',character:{phase:'finalized',identity:{characterName:'Nova'}}});const api=f.api(),campaign=await api.campaign(code);api.clients.set(code,new Set([{token:joined.token}]));assert.equal(api.state(campaign,created.token).characters[0].connected,true);assert.deepEqual(api.connectedCharacterIds(code),[pc.campaign.ownCharacterId]);api.clients.get(code).clear();assert.equal(api.state(campaign,created.token).characters[0].connected,false);});
test('a saved draft can be reviewed, approved as-is, linked and then left without a stale session',async()=>{const f=fixture(),created=await f.call('v03/create',{name:'Draft import'},201),code=created.campaign.code,p=await f.call('v03/join',{code,name:'Tester'});await f.call('v03/import',{code,token:p.token,kind:'character',data:{phase:'skills',identity:{characterName:'Saved traveler'},attributes:{intellect:[6,6]},skills:[],pendingRoll:{old:true}}});const request=(await f.api().campaign(code)).imports[0];await f.call('v03/import/respond',{code,token:created.token,requestId:request.id,approve:true});const result=await f.call('v03/import/finish',{code,token:p.token,requestId:request.id,password:''});assert.ok(result.campaign.ownCharacterId);const imported=(await f.api().campaign(code)).characters[0].character;assert.equal(imported.phase,'finalized');assert.equal(imported.pendingRoll,null);await f.call('v03/leave',{code,token:p.token});assert.ok(!f.api().session(p.token,code));f.restart();await f.api().campaign(code);assert.ok(!f.api().session(p.token,code));});

test('Galaxy Maps persist through campaign backup and hide GM notes from players',async()=>{const f=fixture(),r=await f.call('v03/create',{name:'Galaxy permissions'},201),code=r.campaign.code,token=r.token,p=await f.call('v03/join',{code,name:'Observer'});assert.equal(r.campaign.shipCredits,100000);const command=b=>f.call('v03/starmap',{code,token,receipt:require('node:crypto').randomUUID(),...b});await command({kind:'create',name:'Sector'});const map=(await f.api().campaign(code)).starmaps.maps[0];await command({kind:'scale',mapId:map.id,scale:.01});await command({kind:'star',mapId:map.id,name:'Sol',q:0,r:0,gmNotes:'secret',lore:'public'});await f.call('v03/starmap',{code,token:p.token,kind:'create',name:'Unauthorized',receipt:'unauthorized-map'},400);const pc=f.api().state(await f.api().campaign(code),p.token);assert.equal(pc.starmaps.maps[0].stars[0].gmNotes,undefined);assert.equal(pc.starmaps.maps[0].stars[0].lore,'public');let backup;await f.api().handle({method:'GET'},{},new URL(`http://test/api/campaign/backup?code=${code}&token=${token}`),async()=>{},(_,status,data)=>{assert.equal(status,200);backup=data;});await f.call('v03/close',{code,token});f.restart();const loaded=await f.call('v03/load',{backup});assert.equal(loaded.campaign.starmaps.maps[0].lightYearsPerHex,.01);assert.equal(loaded.campaign.starmaps.maps[0].stars[0].gmNotes,'secret');});

test('ship imports offer authoritative purchase cost and paid/free approval spends once',async()=>{for(const paid of [true,false]){const f=fixture(),r=await f.call('v03/create',{name:'Ship credits '+paid},201),code=r.campaign.code,token=r.token,p=await f.call('v03/join',{code,name:'Builder'}),source=structuredClone(require('./helpers/crew-room-fixture.cjs')().ship.ship);source.confirmedOnce=true;source.constructionCost=1;await f.call('v03/import',{code,token:p.token,kind:'ship',data:source});let c=await f.api().campaign(code),request=c.imports[0];const price=require('../ship-budget').cost(source);assert.equal(request.data.constructionCost,price);await f.call('v03/import/respond',{code,token,requestId:request.id,approve:true,useGroupCredits:paid});c=await f.api().campaign(code);assert.equal(c.shipCredits,paid?100000-price:100000);const before=c.shipCredits;await f.call('v03/import/respond',{code,token,requestId:request.id,approve:true,useGroupCredits:paid},400);assert.equal((await f.api().campaign(code)).shipCredits,before);f.restart();c=await f.api().campaign(code);assert.equal(c.starships.length,1);assert.equal(c.shipCredits,before);}});

test('construction sales refund half while destruction does not and Session0 permits debt',()=>{const budget=require('../ship-budget'),before={gridCells:[1],sicInventory:[{id:'x',type:'life-support'}]},after={gridCells:[1],sicInventory:[]};assert.equal(budget.buildDelta(before,after),-750);assert.equal(budget.buildDelta(before,after,['x']),0);const c={shipCredits:100000,sessionNumber:0};budget.spend(c,120000);assert.equal(c.shipCredits,-20000);c.sessionNumber=1;assert.throws(()=>budget.spend(c,1),/Group Credits/);});

test('freshly deployed live NPC can be assigned and survives the saved roster',async()=>{const f=fixture(),r=await f.call('v03/create',{name:'NPC assignment'},201),code=r.campaign.code,token=r.token,c=await f.api().campaign(code),ship=require('./helpers/crew-room-fixture.cjs')().ship;ship.controlType='gm';ship.crewCharacterIds=[];c.starships=[ship];await f.api().save(c);const live={units:[{id:'new-npc',team:'npc',characterName:'New Crew'}],starships:[structuredClone(ship)]};f.api().liveEncounter=()=>live;const result=await f.call('starship/crew',{code,token,starshipId:ship.id,crewCharacterIds:[],crewNpcUnitIds:['new-npc']});assert.deepEqual(result.starship.crewNpcUnitIds,['new-npc']);assert.deepEqual(live.starships[0].crewNpcUnitIds,['new-npc']);f.restart();assert.equal((await f.api().campaign(code)).npcRoster[0].id,'new-npc');});

test('Session0 applies the twenty percent adjustment to both positive and negative Group Credits',async()=>{for(const credits of [20000,-20000]){const f=fixture(),r=await f.call('v03/create',{name:'Credit adjustment'},201),code=r.campaign.code,c=await f.api().campaign(code);c.shipCredits=credits;await f.api().save(c);await f.call('session/end',{code,token:r.token});assert.equal((await f.api().campaign(code)).shipCredits,credits*1.2);await f.call('session/end',{code,token:r.token});assert.equal((await f.api().campaign(code)).shipCredits,credits*1.2);}});
