const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process'),{once}=require('node:events');
test('cloak activation consumes normal and surplus NPC ATB, retries cannot charge twice',{timeout:30000},async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sa-cloak-http-')),child=spawn(process.execPath,['server.js'],{cwd:path.resolve(__dirname,'..'),windowsHide:true,env:{...process.env,PORT:'0',DATABASE_URL:'',SA_LOCAL_DATA_DIR:dir},stdio:['ignore','pipe','pipe']});t.after(async()=>{if(child.exitCode===null){const done=once(child,'exit');child.kill();await done;}});
 const base=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('startup timeout')),10000);child.stdout.on('data',c=>{const url=String(c).match(/Local:\s+(http:\/\/127\.0\.0\.1:\d+)/)?.[1];if(url){clearTimeout(timer);resolve(url);}});});
 const post=async(p,b,status=200)=>{const r=await fetch(base+'/api/'+p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}),d=await r.json();assert.equal(r.status,status,JSON.stringify(d));return d;};
 const demo=await post('campaign/showcase/start',{}),backup=await fetch(`${base}/api/campaign/backup?code=${demo.code}&token=${demo.gmToken}`).then(r=>r.json()),e=backup.campaign.encounter,npc=e.units.find(u=>u.team==='npc'),pc=e.units.find(u=>u.team==='pc'),menace=structuredClone(backup.campaign.starships.find(s=>s.id==='showcase-gm-menace')),maps=require('../ship-map-core');
 const bridge=menace.ship.sicInventory.find(i=>maps.definition(i.type).bridge),sic=menace.ship.sicInventory.find(i=>maps.definition(i.type).cloaking);npc.location={starshipId:menace.id,sicId:bridge.id,square:menace.ship.placements.find(p=>p.sicId===bridge.id).cell,mesh:0,stationed:true};pc.atb=0;
 e.starships=[e.starships.find(s=>s.id===pc.location.starshipId),menace];e.shipPositions=e.starships.map((s,i)=>({id:s.id,q:i*10,r:0}));Object.assign(e,{hasEngagedClock:true,encounterEndedAt:null,pausedForTurn:true,running:false,hardPaused:true,resumeAfterTurn:false});
 const act=b=>post('action',{roomCode:demo.code,gmToken:demo.gmToken,id:npc.id,...b});
 for(const initial of [100,205]){npc.atb=initial;e.activeId=npc.id;menace.ship.cloakState=null;await post('campaign/restore',{code:demo.code,token:demo.gmToken,backup});const request={action:'utilityCommand',sicId:sic.id,kind:'cloak',enabled:true,receipt:'cloak-test-'+initial};let s=await act(request);assert.equal(s.units.find(u=>u.id===npc.id).atb,0);assert.notEqual(s.activeId,npc.id);assert.equal(s.starships.find(r=>r.id===menace.id).ship.cloakState.active,true);const au=s.starships.find(r=>r.id===menace.id).auState.current;s=await act(request);assert.equal(s.starships.find(r=>r.id===menace.id).auState.current,au);assert.equal(s.units.find(u=>u.id===npc.id).atb,0);await post('action',{roomCode:demo.code,gmToken:demo.gmToken,id:npc.id,...request,enabled:false,receipt:'new-cloak-'+initial},409);}
});
