const test=require('node:test'),assert=require('node:assert/strict'),maps=require('../ship-map-core');
test('thrusters reject corner contact but accept a complete straight hull edge',()=>{const ship={gridCells:[147],sicInventory:[{id:'t',type:'exhaust-thruster-5'}],placements:[{sicId:'t',cell:107}]};assert.equal(maps.exteriorPlacement(ship,'exhaust-thruster-5',107,'t'),false);ship.gridCells=[147,148,149,150];assert.equal(maps.exteriorPlacement(ship,'exhaust-thruster-5',107,'t'),true);});
test('compact preparation records retain sensors and map scale without floorplans',()=>{const ship=require('../showcase-variants')().find(s=>s.title==='Scout'),summary={id:ship.id,lazyLayout:true,hullCount:ship.ship.gridCells.length,sensorSummary:maps.sensorStats(ship),ship:{gridCells:[]}};assert.equal(maps.sensorStats(summary).range,maps.sensorStats(ship).range);assert.equal(maps.scaleRank(summary),maps.scaleRank(ship));});
test('damage indicators wait for the firing presentation without changing game HP',()=>{const health=require('../health-display'),real=Date.now;let now=10000;Date.now=()=>now;try{const ship={id:'visual-test',currentHullHp:100,maximumHullHp:100,currentShieldHp:12,shieldSystems:{a:{hp:12}},ship:{}};health.presentation(ship);ship.currentHullHp=80;ship.currentShieldHp=0;ship.shieldSystems.a.hp=0;ship.weaponState={reports:[{id:'hit',targetId:ship.id,impact:true,at:new Date(now).toISOString()}]};assert.equal(health.presentation(ship).currentHullHp,100);assert.equal(health.presentation(ship).shieldSystems.a.hp,12);assert.equal(ship.currentHullHp,80);now+=3001;assert.equal(health.presentation(ship).currentHullHp,80);assert.equal(health.presentation(ship).shieldSystems.a.hp,0);}finally{Date.now=real;}});

test('offline consoles remain inspectable in browser while server operations stay blocked',()=>{
 const fs=require('node:fs'),vm=require('node:vm'),window={SAShipMap:maps};vm.runInNewContext(fs.readFileSync(require.resolve('../station-access'),'utf8'),{window});
 const ship={id:'off-test',ship:{gridCells:[21,22],sicInventory:[{id:'shield',type:'shield-1',status:'offline'}],placements:[{sicId:'shield',cell:21}]}};
 const unit={id:'operator',currentHp:10,location:{starshipId:ship.id,sicId:'shield',square:21,mesh:0,stationed:true}},room={starships:[ship],units:[unit]};
 const view=window.SAStationAccess.access(room,unit,'shield');assert.ok(view);assert.equal(view.offline,true);assert.equal(view.blocked,true);assert.equal(require('../station-access').access(room,unit,'shield'),null);
 ship.ship.sicInventory[0].status='installed';assert.equal(window.SAStationAccess.access(room,unit,'shield').blocked,false);assert.ok(require('../station-access').access(room,unit,'shield'));
});
