const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process'),{once}=require('node:events');
test('defensive alert animation is private, authenticated, idempotent and survives saved state',{timeout:30000},async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sa-counter-http-')),child=spawn(process.execPath,['server.js'],{cwd:path.resolve(__dirname,'..'),windowsHide:true,env:{...process.env,PORT:'0',DATABASE_URL:'',SA_LOCAL_DATA_DIR:dir},stdio:['ignore','pipe','pipe']});t.after(async()=>{if(child.exitCode===null){const done=once(child,'exit');child.kill();await done;}});
 const base=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('startup timeout')),10000);child.stdout.on('data',c=>{const url=String(c).match(/Local:\s+(http:\/\/127\.0\.0\.1:\d+)/)?.[1];if(url){clearTimeout(timer);resolve(url);}});});
 const post=async(p,b,status=200)=>{const r=await fetch(base+'/api/'+p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}),d=await r.json();assert.equal(r.status,status,JSON.stringify(d));return d;};
 const demo=await post('campaign/showcase/start',{}),backup=await fetch(`${base}/api/campaign/backup?code=${demo.code}&token=${demo.gmToken}`).then(r=>r.json()),e=backup.campaign.encounter,pc=demo.players[0],unit=e.units.find(u=>u.characterId===pc.id),enemy=e.starships.find(s=>s.id!==unit.location.starshipId),own=e.starships.find(s=>s.id===unit.location.starshipId);
 const roll={id:'private-alert-check',sicId:enemy.ship.sicInventory[0].id,label:'Hack Alert',sides:[4],values:[4],score:4,phase:'rolling'};enemy.ship.fieldState||={};enemy.ship.fieldState.hackAlertRolls=[roll];own.ship.fieldState||={};own.ship.fieldState.hackAlertRolls=[{...roll,id:'own-alert-check',sicId:own.ship.sicInventory[0].id}];
 await post('campaign/restore',{code:demo.code,token:demo.gmToken,backup});const state=token=>fetch(`${base}/api/state?room=${demo.code}&token=${token}`).then(r=>r.json());let s=await state(pc.token);assert.equal(s.hackingDice.length,1);assert.equal(s.hackingDice[0].automationPresentation.id,'own-alert-check');assert.equal(JSON.stringify(s).includes('private-alert-check'),false);assert.equal((await state(demo.gmToken)).hackingDice.length,2);
 await post('action',{roomCode:demo.code,characterId:pc.id,characterToken:pc.token,action:'hackAlertAnimationComplete',starshipId:enemy.id,rollId:roll.id},403);
 const action={roomCode:demo.code,gmToken:demo.gmToken,action:'hackAlertAnimationComplete',starshipId:enemy.id,rollId:roll.id};await post('action',action);await post('action',action);s=await state(demo.gmToken);assert.equal(s.starships.find(x=>x.id===enemy.id).sensorState.reports.filter(r=>r.id===roll.id).length,1);assert.match(s.starships.find(x=>x.id===enemy.id).sensorState.reports.find(r=>r.id===roll.id).text,/HACK ALERT/);
 const saved=await fetch(`${base}/api/campaign/backup?code=${demo.code}&token=${demo.gmToken}`).then(r=>r.json());assert.equal(saved.campaign.encounter.starships.find(s=>s.id===enemy.id).ship.fieldState.hackAlertRolls[0].phase,'complete');
 const next=saved.campaign.encounter,liveOwn=next.starships.find(s=>s.id===own.id),liveUnit=next.units.find(u=>u.characterId===pc.id),f=require('./helpers/devastation-fixture.cjs')();f.ship.ship.sicInventory[0].type='ionic-force-displacers';liveOwn.ship=f.ship.ship;liveUnit.location={starshipId:own.id,sicId:'bridge',square:147,mesh:0,stationed:true};saved.campaign.starships.find(s=>s.id===own.id).ship=structuredClone(liveOwn.ship);saved.campaign.starships.find(s=>s.id===own.id).characterLocations={[pc.id]:structuredClone(liveUnit.location)};Object.assign(next,{hasEngagedClock:false,activeId:null,running:false,hardPaused:true});await post('campaign/restore',{code:demo.code,token:demo.gmToken,backup:saved});await state(demo.gmToken);const inspected=await post('campaign/starship/field-utility',{code:demo.code,token:pc.token,characterId:pc.id,starshipId:own.id,sicId:'gun',kind:'inspect'});assert.equal(inspected.result.report,'Utility ready.');

});
