const test=require('node:test'),assert=require('node:assert/strict'),x=require('../ship-extraction'),maps=require('../ship-map-core');
function fixture(type='mining-laser') {const f=require('./helpers/crew-room-fixture.cjs')();f.ship.ship.sicInventory.find(i=>i.id==='engine').type='en-engine-6';f.ship.ship.sicInventory.push({id:'extract',type});f.ship.ship.placements.push({sicId:'extract',cell:81});f.room.outsideCombat=true;f.room.shipPositions=[{id:f.ship.id,q:0,r:0}];f.room.spaceObjects=[{id:'object-asteroid',name:'Asteroid',kind:'asteroid',q:1,r:0,quantity:2,miningTarget:6}];return f;}
function start(f,targetId='object-asteroid'){return x.command(f.room,f.ship,f.unit,{kind:'extract-start',sicId:'extract',targetId,requestId:crypto.randomUUID()},f.campaign);}
function roll(f,values){const j=x.state(f.ship).jobs.extract;return x.resolve(f.room,f.ship,j,j.phase,values,f.campaign);}
test('mining spends four active hours per attempt and resolves the full chart into storage',()=>{const f=fixture();start(f);x.advance(f.room,f.campaign,14399);assert.equal(x.state(f.ship).jobs.extract.phase,'working');x.advance(f.room,f.campaign,1);assert.equal(f.room.spaceObjects[0].quantity,1);roll(f,[5]);roll(f,[8,10]);assert.equal(x.state(f.ship).jobs.extract.mineral,'Iron');roll(f,[12,12]);assert.equal(f.ship.ship.minerals.Iron,720);assert.equal(x.state(f.ship).jobs.extract.phase,'complete');assert.throws(()=>roll(f,[12,12]));});
test('strict-under failure still consumes an attempt and the last attempt removes the asteroid',()=>{const f=fixture();f.room.spaceObjects[0].quantity=1;start(f);x.advance(f.room,f.campaign,14400);assert.equal(f.room.spaceObjects.length,0);roll(f,[6]);assert.equal(x.state(f.ship).jobs.extract.phase,'complete');assert.equal(f.ship.ship.minerals.Iron,undefined);});
test('mining pauses outside range and on power loss without burning attempts',()=>{const f=fixture();start(f);f.room.shipPositions[0].q=10;x.advance(f.room,f.campaign,14400);assert.equal(x.state(f.ship).jobs.extract.remaining,14400);f.room.shipPositions[0].q=0;f.ship.ship.sicInventory.find(i=>i.id==='extract').disabled=true;x.advance(f.room,f.campaign,14400);assert.equal(f.room.spaceObjects[0].quantity,2);f.ship.ship.sicInventory.find(i=>i.id==='extract').disabled=false;x.advance(f.room,f.campaign,14400);assert.equal(x.state(f.ship).jobs.extract.phase,'success');});
test('mythic Aethion quantity uses the ordinary D4 as an unbiased D2 minus one',()=>{const f=fixture();start(f);x.advance(f.room,f.campaign,14400);roll(f,[1]);roll(f,[10,1]);assert.equal(x.spec(x.state(f.ship).jobs.extract).sides[0],6);roll(f,[1]);roll(f,[2]);assert.equal(f.ship.ship.minerals.Aethion,0);});
test('combat mining queues standard manual rolls and carries the next chart step',()=>{const f=fixture();f.room.outsideCombat=false;start(f);x.advance(f.room,f.campaign,14400);assert.equal(f.unit.pendingShipRolls.length,1);assert.deepEqual(f.unit.pendingShipRolls[0].rollSpec.sides,[10]);roll(f,[1]);assert.equal(f.unit.pendingShipRolls.length,1);assert.deepEqual(f.unit.pendingShipRolls[0].rollSpec.sides,[10,10]);});
function salvage(){const f=fixture('vulture-drone');f.ship.ship.sicInventory.push({id:'sensors',type:'sensors-1'});f.ship.ship.placements.push({sicId:'sensors',cell:85});const wreck={id:'wreck',title:'Wreck',currentHullHp:0,destroyedAt:new Date().toISOString(),ship:{gridCells:[21,22],sicInventory:[{id:'bad',type:'life-support',impairmentPoints:1},{id:'good',type:'sensors-1'}],placements:[{sicId:'bad',cell:21},{sicId:'good',cell:22}]}};f.room.starships.push(wreck);f.room.shipPositions.push({id:'wreck',q:1,r:0});return {...f,wreck};}
test('Vulture recovers one undamaged installed SIC then exhausts the wreck',()=>{const f=salvage();start(f,'wreck');x.advance(f.room,f.campaign,239);assert.equal(x.state(f.ship).jobs.extract.phase,'working');x.advance(f.room,f.campaign,1);roll(f,[10,10,10]);const item=f.ship.ship.sicInventory.find(i=>i.salvaged);assert.equal(item.type,'sensors-1');assert.equal(item.storage,true);assert.ok(f.wreck.ship.salvagedAt);assert.deepEqual(x.targets(f.room,f.ship,'vulture-drone'),[]);});
test('Vulture interruption pauses on control loss and cancels on drone impairment',()=>{const f=salvage();start(f,'wreck');f.ship.hackedSystems=[{sicId:'extract'}];x.advance(f.room,f.campaign,240);assert.equal(x.state(f.ship).jobs.extract.remaining,240);f.ship.hackedSystems=[];x.advance(f.room,f.campaign,120);f.ship.ship.sicInventory.find(i=>i.id==='extract').impairmentPoints=1;x.advance(f.room,f.campaign,120);assert.equal(x.state(f.ship).jobs.extract.phase,'cancelled');assert.equal(f.wreck.ship.salvagedAt,undefined);});
test('save/reload retains progress and duplicate receipts cannot launch twice',()=>{const f=fixture(),body={kind:'extract-start',sicId:'extract',targetId:'object-asteroid',requestId:crypto.randomUUID()};x.command(f.room,f.ship,f.unit,body,f.campaign);x.advance(f.room,f.campaign,100);assert.equal(x.command(f.room,f.ship,f.unit,body,f.campaign).duplicate,true);const reloaded=JSON.parse(JSON.stringify(f.room));x.advance(reloaded,f.campaign,14300);assert.equal(x.state(reloaded.starships[0]).jobs.extract.phase,'success');});
test('asteroid settings reject excess and preserve the GM cutoff',()=>{const objects=require('../space-objects'),base={id:'object-rock',kind:'asteroid',name:'Rock',quantity:50,miningTarget:8,q:0,r:0};assert.equal(objects.normalize([base])[0].miningTarget,8);assert.throws(()=>objects.normalize([{...base,quantity:51}]));});
test('Vulture is a target with threshold 25 and destruction cancels its job',()=>{const f=salvage();start(f,'wreck');const targets=require('../ship-targets'),drone=targets.all(f.room).find(s=>s.isSalvageDrone);assert.equal(drone.defenseScore,10);assert.equal(targets.hit(f.room,drone.id,24),false);assert.equal(targets.hit(f.room,drone.id,25),true);assert.equal(x.state(f.ship).jobs.extract.phase,'cancelled');assert.equal(targets.find(f.room,drone.id),undefined);});
test('gravity displaces and destroys a salvage drone without granting salvage',()=>{const f=salvage();start(f,'wreck');f.room.spaceObjects=[{id:'hole',kind:'black-hole',q:1,r:0,intensity:3}];require('../ship-black-holes').advance(f.room,1);assert.equal(x.state(f.ship).jobs.extract.phase,'cancelled');assert.equal(f.wreck.ship.salvagedAt,undefined);});
test('a wreck disappearing during pending recovery clears the roll safely',()=>{const f=salvage();f.room.outsideCombat=false;start(f,'wreck');x.advance(f.room,f.campaign,240);assert.equal(f.unit.pendingShipRolls.length,1);f.wreck.ship.salvagedAt=Date.now();x.advance(f.room,f.campaign,0);assert.equal(f.unit.pendingShipRolls.length,0);assert.equal(x.state(f.ship).jobs.extract.phase,'cancelled');});
