const test=require('node:test'),assert=require('node:assert/strict');
const maps=require('../ship-map-core'),air=require('../ship-atmosphere'),cloak=require('../ship-cloaking'),power=require('../ship-power'),transit=require('../ship-transit'),field=require('../ship-field-utilities');
const fixture=require('./helpers/field-utility-fixture.cjs');
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
function extras(){const f=fixture();f.ship.ship.sicInventory.find(i=>i.id==='engine').type='en-engine-6';f.ship.ship.sicInventory.find(i=>i.id==='au').type='au-engine-6';for(const [id,type,cell] of [['cloak','cloaking-device',190],['ew','ew-ftl-drive',195]]){f.ship.ship.sicInventory.push({id,type});f.ship.ship.placements.push({sicId:id,cell});}power.refresh(f.room,{reset:true});return f;}
test('scale ranks preserve every normal hull boundary',()=>{for(const [n,r] of [[4,1],[26,1],[27,2],[50,2],[51,3],[100,3],[101,4],[200,4],[201,5]])assert.equal(maps.scaleRank({gridCells:Array(n).fill(0),triangleCells:[9,10]}),r);});
test('bay vents connected rooms while closed doors isolate; sealed air refills',()=>{const f=fixture(),s=f.ship;s.ship.sicInventory.push({id:'life',type:'life-support'});s.ship.placements.push({sicId:'life',cell:211});s.ship.doorStates={};const l=maps.buildLayout(s.ship);s.ship.fieldState={systems:{bay:{doorOpen:true}}};air.advance(s,165);close(air.at(s,{square:89}),10);close(air.at(s,{square:81}),100);for(const k of l.hull)for(const side of l.sides){const e=l.boundary(k,side.name);if(e.kind==='door')s.ship.doorStates[e.key]='open';}air.advance(s,165);assert.ok(air.at(s,{square:81})<=10+1e-7);s.ship.fieldState.systems.bay.doorOpen=false;air.advance(s,100);close(air.at(s,{square:81}),100);});
test('atmospheric shield prevents venting and air state survives restart',()=>{const f=fixture();f.ship.ship.sicInventory.push({id:'life',type:'life-support'});f.ship.ship.placements.push({sicId:'life',cell:211});f.ship.ship.fieldState={systems:{bay:{doorOpen:true,shield:true}}};air.advance(f.ship,400);close(air.at(f.ship,{square:89}),100);const saved=structuredClone(f.ship);assert.deepEqual(air.sync(saved),f.ship.ship.atmosphereState);});
test('cloak spends 12 AU once, adds 10 masking with shields and permits AU use',()=>{const f=extras(),base=maps.masking(f.ship),au=f.ship.auState.current;f.ship.currentShieldHp=20;f.ship.shieldSystems={s:{hp:20}};const body={sicId:'cloak',enabled:true,receipt:'cloak-activation-1'};assert.equal(cloak.command(f.room,f.unit,body).ok,true);assert.equal(f.ship.auState.current,au-12);assert.equal(maps.masking(f.ship),base+10);assert.equal(f.ship.currentShieldHp,20);assert.equal(power.spend(f.room,f.ship.id,1),true);assert.equal(cloak.command(f.room,f.unit,body).duplicate,true);assert.equal(cloak.command(f.room,f.unit,{...body,enabled:false,receipt:'cloak-disable-1'}).ok,true);assert.equal(maps.masking(f.ship),base);});
test('impaired cloak cannot activate or retain its masking bonus',()=>{const f=extras();f.ship.ship.sicInventory.find(i=>i.id==='cloak').impairmentPoints=1;assert.equal(cloak.command(f.room,f.unit,{sicId:'cloak',enabled:true,receipt:'impaired-cloak'}).ok,false);f.ship.ship.cloakState={active:true,sicId:'cloak'};assert.equal(maps.cloaked(f.ship),false);});
test('EW-FTL spends two S cells and all AU once; jumps at 120 seconds',()=>{const f=extras();f.ship.ship.warpFuel={S:3};const body={kind:'warpStart',sicId:'ew',shipId:f.ship.id,distanceLY:4000,requestId:'ew-start-receipt'};const result=transit.command(f.room,f.unit,body);assert.equal(result.ok,true,result.error);assert.equal(f.ship.ship.warpFuel.S,1);assert.equal(f.ship.auState.current,0);assert.equal(transit.command(f.room,f.unit,body).duplicate,true);transit.advance(f.room,119);assert.equal(f.ship.ship.warpState.phase,'activating');const events=transit.advance(f.room,1);assert.equal(f.ship.ship.warpState.phase,'arrived');assert.equal(f.ship.ship.warpState.traveledLY,4000);assert.ok(events.some(e=>e.kind==='warpDeparted'));});
test('impaired EW-FTL demands a confirmed D8 and explodes on a tie',()=>{const f=extras();f.ship.ship.warpFuel={S:2};f.ship.ship.sicInventory.find(i=>i.id==='ew').impairmentPoints=2;const body={kind:'warpStart',sicId:'ew',shipId:f.ship.id,distanceLY:40,requestId:'ew-fault-receipt'};assert.equal(transit.command(f.room,f.unit,body).ok,false);assert.equal(f.ship.ship.warpFuel.S,2);const r=transit.command(f.room,f.unit,{...body,diceResults:[2]});assert.equal(r.ok,true,r.error);assert.equal(f.ship.currentHullHp,0);assert.equal(f.ship.ship.warpState.phase,'exploded');});
test('uncaptured bay cannot force dock; opening preserves half-hull capacity',()=>{const f=fixture();f.room.shipPositions[1]={id:f.target.id,q:0,r:0};const body={starshipId:f.ship.id,sicId:'bay',receipt:'open-bay-receipt',kind:'bay-open'};assert.equal(field.command(f.room,f.unit,body).ok,true);assert.equal(f.ship.ship.fieldState.systems.bay.doorOpen,true);const forced=field.command(f.room,f.unit,{...body,receipt:'forced-attempt-1',kind:'force-dock',targetId:f.target.id});assert.equal(forced.ok,false);assert.match(forced.error,/Capture/);assert.equal(field.bayCapacity(f.room,f.ship,'bay').maximum,98);});
test('fog and low resolution labels share room oxygen',()=>{const f=fixture();air.sync(f.ship);f.ship.ship.atmosphereState.cells[89]=10;const html=maps.surfaceMarkup(maps.buildLayout(f.ship.ship),89);assert.match(html,/10%/);assert.match(html,/sa-room-fog/);assert.match(html,/is-critical/);});

test('captured bay can force dock the attacker and renders its rank and glow',()=>{
 const f=fixture(),u=f.room.units[1];f.target.ship.sicInventory=[{id:'enemy-cockpit',type:'cockpit-1'}];f.target.ship.placements=[{sicId:'enemy-cockpit',cell:42}];u.location={starshipId:f.target.id,sicId:'enemy-cockpit',square:42,mesh:0,stationed:true};f.room.activeId=u.id;f.room.shipPositions[1].q=0;
 f.room.hackingGrants=[{unitId:u.id,sourceId:f.target.id,targetId:f.ship.id,sicId:'bay'}];
 const command=(kind,receipt)=>field.command(f.room,u,{starshipId:f.ship.id,sicId:'bay',kind,receipt,targetId:f.target.id});
 assert.equal(command('bay-open','hacked-bay-open').ok,true);
 const result=command('force-dock','hacked-bay-force');assert.equal(result.ok,true,result.error);
 assert.equal(f.target.ship.fieldState.dockedIn.shipId,f.ship.id);assert.equal(f.ship.ship.fieldState.systems.bay.dockedShips[0].rank,1);
 assert.match(maps.surfaceMarkup(maps.buildLayout(f.ship.ship),89),/sic-art-starship-rank-1/);
});

test('loss of cloak power cancels activation until paid for again',()=>{
 const f=extras();assert.equal(cloak.command(f.room,f.unit,{sicId:'cloak',enabled:true,receipt:'power-loss-cloak'}).ok,true);
 f.ship.ship.sicInventory.find(i=>i.id==='engine').disabled=true;power.refresh(f.room);assert.equal(f.ship.ship.cloakState.active,false);
 f.ship.ship.sicInventory.find(i=>i.id==='engine').disabled=false;power.refresh(f.room);assert.equal(maps.cloaked(f.ship),false);
});
