const test=require('node:test'),assert=require('node:assert/strict');
const maps=require('../ship-map-core'),breaches=require('../ship-breaches'),air=require('../ship-atmosphere'),doors=require('../ship-doors');
function fixture(){const ship={id:'ship',title:'Test',currentHullHp:100,ship:{gridCells:[21,22,23,41,42,43,61,62,63],sicInventory:[{id:'lab',type:'science-lab',impairmentPoints:4}],placements:[{sicId:'lab',cell:22}],doorStates:{}}};maps.ensureAirlocks(ship);const unit={id:'pc',characterName:'Tester',currentHp:20,dexterityDice:[8,6],location:{starshipId:'ship',square:22,mesh:4},atb:100};return {starships:[ship],units:[unit],shipPositions:[{id:'ship',q:0,r:0}],activeId:'pc',threshold:100};}
test('airlock occupies blank outer hull, survives edits, and rejects a ship without room',()=>{const r=fixture(),s=r.starships[0].ship;assert.equal(s.airlocks.length,1);assert.equal(s.airlocks[0].square,21);assert.equal(maps.ensureAirlocks({gridCells:[21],sicInventory:[{id:'b',type:'cockpit-1'}],placements:[{sicId:'b',cell:21}]}).length>0,true);const moved=maps.resizeZone(s,30,30,2,2);assert.equal(moved.airlocks[0].square,maps.remapSquare(21,s,moved));});
test('four impairments create one persistent breach and one standard dice request per occupant',()=>{const r=fixture();breaches.reconcile(r,null,()=>0);const h=Object.values(r.starships[0].ship.breachState.holes)[0],u=r.units[0];assert.equal(h.square,22);assert.equal(u.pendingShipRolls.length,1);assert.deepEqual(u.pendingShipRolls[0].rollSpec.sides,[8,6]);assert.equal(u.pendingShipRolls[0].rollSpec.difficulty,16);breaches.reconcile(r,null,()=>0);assert.equal(u.pendingShipRolls.length,1);h.sealed=true;breaches.reconcile(r,null,()=>0);assert.equal(Object.keys(r.starships[0].ship.breachState.holes).length,1);});
test('failed suction ejects at least one hex, pauses at zero elapsed time and damages/drifts on active intervals',()=>{const r=fixture(),u=r.units[0];breaches.reconcile(r,null,()=>0);breaches.resolveCheck(r,u,u.pendingShipRolls[0],0);assert.equal(u.location,null);assert.equal(require('../ship-distances').hexDistance({q:0,r:0},u.vacuum.position),1);const start={...u.vacuum.position};breaches.advance(r,0);assert.equal(u.currentHp,20);breaches.advance(r,1);assert.equal(u.currentHp,20);breaches.advance(r,1);assert.equal(u.currentHp,19);breaches.advance(r,10);assert.equal(u.currentHp,14);assert.equal(require('../ship-distances').hexDistance(start,u.vacuum.position),1);});
test('same-hex operational arm rescues beside an airlock, not from the launch hex',()=>{const r=fixture(),s=r.starships[0],u=r.units[0];s.ship.sicInventory.push({id:'arm',type:'manipulation-arm'});s.ship.placements.push({sicId:'arm',cell:61,exteriorCell:81});breaches.reconcile(r,null,()=>0);breaches.resolveCheck(r,u,u.pendingShipRolls[0],0);breaches.advance(r,.1);assert.ok(u.vacuum);r.shipPositions[0]={id:'ship',...u.vacuum.position};breaches.advance(r,.1);assert.equal(u.vacuum,null);assert.equal(u.location.starshipId,'ship');assert.equal(u.location.stationed,false);});
test('repair difficulty falls across attempts and a sealed destroyed SIC does not reopen',()=>{const r=fixture(),s=r.starships[0],u=r.units[0];breaches.reconcile(r,null,()=>0);const h=Object.values(s.ship.breachState.holes)[0];u.pendingShipRolls=[];breaches.queueRepair(r,u,{hazardId:h.id});assert.equal(u.delayedAction.rate,100/6);assert.equal(u.delayedAction.rollSpec.difficulty,20);let roll=()=>1;roll.submittedScore=0;breaches.resolveRepair(r,u,roll);breaches.queueRepair(r,u,{hazardId:h.id});assert.equal(u.delayedAction.rollSpec.difficulty,19);roll.submittedScore=30;breaches.resolveRepair(r,u,roll);assert.ok(h.sealed);breaches.reconcile(r,null,()=>0);assert.equal(Object.values(s.ship.breachState.holes).filter(h=>!h.sealed).length,0);});
test('airlock opening needs confirmation and physical or Bridge access; closing needs no roll',()=>{const r=fixture(),s=r.starships[0],u=r.units[0],a=s.ship.airlocks[0];assert.throws(()=>breaches.operate(r,u,{starshipId:s.id,airlockId:a.id,confirmed:true}));u.location.square=a.square;assert.throws(()=>breaches.operate(r,u,{starshipId:s.id,airlockId:a.id}));breaches.operate(r,u,{starshipId:s.id,airlockId:a.id,confirmed:true});assert.equal(s.ship.airlockStates[a.id].open,true);breaches.operate(r,u,{starshipId:s.id,airlockId:a.id});assert.equal(s.ship.airlockStates[a.id].open,false);});
test('an isolated breached room vents from 100 to 0 in 24 seconds',()=>{const r=fixture(),s=r.starships[0];breaches.reconcile(r,null,()=>0);air.advance(s,12);assert.equal(air.at(s,{square:22}),50);air.advance(s,12);assert.equal(air.at(s,{square:22}),0);});
test('Brig doors ignore hits below 40 and break on the third qualifying hit',()=>{const s={id:'s',ship:{gridCells:[21,22,41,42],sicInventory:[{id:'b',type:'brig'}],placements:[{sicId:'b',cell:21}],doorStates:{}}},key=doors.list(s)[0];assert.ok(key);const r={starships:[s]};assert.equal(doors.threshold(s,key),40);assert.equal(doors.hit(r,{shipId:'s',key},39),0);assert.equal(doors.hit(r,{shipId:'s',key},40),1);doors.hit(r,{shipId:'s',key},100);assert.equal(doors.hit(r,{shipId:'s',key},40),3);assert.equal(s.ship.doorStates[key],'open');});
