const test=require('node:test'),assert=require('node:assert/strict');
const maps=require('../ship-map-core'),illusions=require('../ship-illusions'),droids=require('../ship-security-droids'),rules=require('../combat-rules'),sensors=require('../ship-sensors');
function fixture(){const ship={id:'a',title:'Test',controlType:'pc',crewCharacterIds:['pc'],crewNpcUnitIds:['crew'],currentHullHp:100,ship:{gridCells:Array.from({length:100},(_,i)=>Math.floor(i/10)*20+i%10),sicInventory:[{id:'cp',type:'cockpit-1'},{id:'en',type:'en-engine-6'},{id:'sn',type:'sensors-8'},{id:'lure',type:'sensor-lure'},{id:'droid',type:'security-droid'}],placements:[{sicId:'cp',cell:0},{sicId:'en',cell:24},{sicId:'sn',cell:1},{sicId:'lure',cell:2},{sicId:'droid',cell:0}],doorStates:{}}};const unit={id:'u',characterId:'pc',team:'pc',currentHp:30,atb:100,location:{starshipId:'a',sicId:'cp',square:0,mesh:0,stationed:true}};return {ship,unit,room:{starships:[ship],units:[unit],shipPositions:[{id:'a',q:0,r:0}],activeId:'u',threshold:100,log:[]}};}
test('range uses completed bands and Max weapons remain unmodified inside range',()=>{for(const [distance,penalty]of [[0,0],[4.99,0],[5,1],[9.99,1],[10,2]]){const p=rules.attackPlan({range:'5',damage:'3D8'}, {distance});assert.equal(p.attackRangeModifier,-penalty||0);assert.equal(p.defenseRangeModifier,penalty);}const p=rules.attackPlan({range:'5 Max',damage:'1D8'},{distance:5});assert.equal(p.defenseRangeModifier,0);assert.equal(rules.attackPlan({range:'5 Max'},{distance:5.01}).allowed,false);});
test('shipboard distance comes from positions, unrelated ships require manual distance',()=>{const f=fixture(),target={location:{starshipId:'a',square:1,mesh:2}};assert.equal(rules.mappedDistance(f.room,f.unit,target),5);target.location.starshipId='b';assert.equal(rules.mappedDistance(f.room,f.unit,target),null);});
test('illusion requires normal rolls, hides difficulty, reveals only on fifth scan per observer',()=>{const f=fixture();assert.equal(illusions.command(f.room,f.unit,{sicId:'lure',kind:'project',appearance:'Planet',receipt:'illusion-test'}).ok,true);const p=illusions.entries(f.room)[0].p,order={shipId:'a',kind:'hex',hex:{q:1,r:0}};assert.equal(sensors.automaticScan(f.room,f.unit,order),null);assert.deepEqual(sensors.scanChecks(f.room,order),[]);for(let n=0;n<4;n++)illusions.resolveScan(f.room,f.ship,order);assert.equal(p.revealed.a,undefined);illusions.resolveScan(f.room,f.ship,order);assert.equal(p.revealed.a,true);assert.equal(p.revealed.b,undefined);assert.match(f.ship.sensorState.reports[0].text,/is an illusion/);});
test('illusion movement stays bounded; planets stay fixed; impairment and same-hex contact reveal',()=>{const f=fixture();illusions.command(f.room,f.unit,{sicId:'lure',kind:'project',appearance:'Galactic Monster',receipt:'illusion-wander'});const p=illusions.entries(f.room)[0].p;illusions.advance(f.room,1200,()=>.99);assert.ok(require('../ship-distances').hexDistance(p.position,p.origin)<=2);f.room.shipPositions[0]={id:'a',...p.position};illusions.advance(f.room,0);assert.equal(p.revealed.a,true);f.ship.ship.sicInventory.find(i=>i.id==='lure').disabled=true;assert.equal(illusions.entries(f.room).length,0);});
test('Droid exempts only registered crew; guest exemption rejected; warning and enable independent',()=>{const f=fixture();droids.sync(f.room,s=>({...s,id:'temporary',atb:0}));assert.equal(f.room.units.length,2);assert.equal(droids.command(f.room,f.unit,{sicId:'droid',kind:'exempt',crewId:'guest',enabled:true,receipt:'droid-guest'}).ok,false);assert.equal(droids.command(f.room,f.unit,{sicId:'droid',kind:'exempt',crewId:'pc',enabled:false,receipt:'droid-crew'}).ok,true);assert.equal(f.ship.ship.securityDroidState.droids.droid.exemptions.pc,false);droids.command(f.room,f.unit,{sicId:'droid',kind:'enabled',enabled:false,receipt:'droid-disable'});droids.sync(f.room,s=>s);assert.equal(f.room.units[1].speed,0);assert.equal(f.ship.ship.securityDroidState.droids.droid.warning,true);});
test('Droid damage persists; diagnostics restores it and power returns without resetting HP',()=>{const f=fixture();droids.sync(f.room,s=>({...s,atb:0}));const u=f.room.units[1];u.currentHp=7;droids.sync(f.room,s=>s);assert.equal(u.currentHp,7);const item=f.ship.ship.sicInventory.find(i=>i.id==='droid');item.disabled=true;droids.sync(f.room,s=>s);assert.equal(u.speed,0);item.disabled=false;droids.sync(f.room,s=>s);assert.equal(u.currentHp,7);droids.repair(f.ship);droids.sync(f.room,s=>s);assert.equal(u.currentHp,50);});
test('Warning mode observes current move without firing; subsequent action authorizes fire',()=>{const f=fixture();droids.sync(f.room,s=>({...s,atb:0}));const u=f.room.units[1];u.location={starshipId:'a',square:180,mesh:4};const target={id:'guest',team:'pc',currentHp:20,location:{starshipId:'a',square:180,mesh:5},securityActionSerial:1,timedAction:{kind:'move'}};f.room.units.push(target);droids.observe(f.room);assert.equal(droids.candidates(f.room,u).some(c=>c.kind==='fire'),false);droids.action(f.room,target);assert.equal(droids.candidates(f.room,u)[0].kind,'fire');});
test('illusory objects never enter physical gravity objects or weapon target lists',()=>{const f=fixture();illusions.command(f.room,f.unit,{sicId:'lure',kind:'project',appearance:'Planet',receipt:'illusion-physical'});const p=illusions.entries(f.room)[0].p;assert.equal(require('../ship-targets').find(f.room,p.id),undefined);assert.equal(f.room.spaceObjects,undefined);assert.equal(illusions.objects(f.room,[f.ship])[0].kind,'projection');});
test('hacked Droid console receives only authorized settings and registered crew names',()=>{const f=fixture(),enemy=structuredClone(f.ship);enemy.id='b';enemy.crewCharacterIds=['other'];enemy.crewNpcUnitIds=[];enemy.ship.securityDroidState={droids:{droid:{enabled:true,warning:true,exemptions:{other:false}},secret:{enabled:true}}};f.room.starships.push(enemy);f.room.units.push({id:'enemy-crew',characterId:'other',characterName:'Registered Rival'});f.room.hackingGrants=[{unitId:'u',targetId:'b',sicId:'droid',sourceId:'a'}];const result=illusions.project(structuredClone(f.room),f.room,{characterId:'pc'}),shown=result.starships.find(s=>s.id==='b').ship.securityDroidState;assert.deepEqual(Object.keys(shown.droids),['droid']);assert.equal(shown.crewRoster[0].name,'Registered Rival');assert.equal(enemy.ship.securityDroidState.droids.secret.enabled,true);});

test('new SIC state survives authenticated campaign export and restore without enemy disclosure',{timeout:35000},async t=>{
 const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process'),{once}=require('node:events');
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sa-illusion-droid-')),child=spawn(process.execPath,['server.js'],{cwd:path.resolve(__dirname,'..'),windowsHide:true,env:{...process.env,PORT:'0',DATABASE_URL:'',SA_LOCAL_DATA_DIR:dir},stdio:['ignore','pipe','pipe']});
 t.after(async()=>{if(child.exitCode===null){const done=once(child,'exit');child.kill();await done;}});
 const base=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('startup timeout')),10000);child.stdout.on('data',c=>{const url=String(c).match(/Local:\s+(http:\/\/127\.0\.0\.1:\d+)/)?.[1];if(url){clearTimeout(timer);resolve(url);}});});
 const post=async(p,b)=>{const r=await fetch(base+'/api/'+p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}),d=await r.json();assert.equal(r.status,200,JSON.stringify(d));return d;};
 const demo=await post('campaign/showcase/start',{}),getBackup=()=>fetch(`${base}/api/campaign/backup?code=${demo.code}&token=${demo.gmToken}`).then(r=>r.json());
 let backup=await getBackup();const e=backup.campaign.encounter,nova=e.units.find(u=>u.characterId===demo.players[0].id),source=e.starships.find(s=>s.id===nova.location.starshipId),f=fixture();
 source.ship=structuredClone(f.ship.ship);source.crewCharacterIds=[nova.characterId];source.crewNpcUnitIds=[];nova.location={...f.unit.location,starshipId:source.id};
 Object.assign(e,{activeId:nova.id,hasEngagedClock:true,running:false,hardPaused:true,pausedForTurn:true});
 const local={...e,starships:[source],units:[nova]};droids.sync(local,s=>({...s,atb:0}));const drone=local.units.find(u=>u.securityDroid);drone.currentHp=17;droids.sync(local,s=>s);e.units.push(drone);
 source.ship.illusionState={projectors:{lure:{id:'test-projection',active:true,appearance:'Planet',variant:'ocean',origin:{q:1,r:0},position:{q:1,r:0},scans:{},revealed:{},elapsed:0}},receipts:[]};
 e.shipPositions=[{id:source.id,q:0,r:0}];
 await post('campaign/restore',{code:demo.code,token:demo.gmToken,backup});
 const state=token=>fetch(`${base}/api/state?room=${demo.code}&token=${token}`).then(r=>r.json());
 let s=await state(demo.gmToken);assert.equal(s.units.find(u=>u.id===drone.id).currentHp,17);assert.ok(s.spaceObjects.some(o=>o.id==='test-projection'));
 backup=await getBackup();await post('campaign/restore',{code:demo.code,token:demo.gmToken,backup});s=await state(demo.gmToken);assert.equal(s.units.find(u=>u.id===drone.id).currentHp,17);
 s=await state(demo.players[0].token);assert.ok(s.starships.find(x=>x.id===source.id).ship.securityDroidState);
 const pc=demo.players[0];s=await post('action',{roomCode:demo.code,characterId:pc.id,characterToken:pc.token,id:nova.id,action:'utilityCommand',sicId:'droid',kind:'warning',enabled:false,receipt:'http-warning-toggle'});
 assert.equal(s.starships.find(x=>x.id===source.id).ship.securityDroidState.droids.droid.warning,false);
 const rejected=await fetch(base+'/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomCode:demo.code,characterId:pc.id,characterToken:pc.token,id:nova.id,action:'utilityCommand',sicId:'droid',kind:'exempt',crewId:'unregistered-guest',enabled:true,receipt:'http-guest-rejected'})});
 assert.equal(rejected.status,409);assert.match((await rejected.json()).error,/registered crew/);
 for(const ship of s.starships.filter(x=>x.id!==source.id)){assert.equal(ship.ship?.securityDroidState,undefined);assert.equal(ship.ship?.illusionState,undefined);}
});
