const test=require('node:test'),assert=require('node:assert/strict');
const mines=require('../ship-mines'),missiles=require('../ship-missiles'),targets=require('../ship-targets'),ammo=require('../missile-ammunition'),maps=require('../ship-map-core'),nav=require('../ship-navigation');
function fixture(){const a={id:'a',title:'Owner',currentHullHp:100,ship:{sicInventory:[{id:'l',type:'mine-launcher'}],placements:[{sicId:'l',cell:0}],gridCells:[0,20],missileAmmo:{l:{'space-mine-1':8}},missileStorage:{'magnetic-seeker':1},missileState:{flights:[],cooldowns:{}}}},b={id:'b',title:'Visitor',currentHullHp:100,ship:{sicInventory:[],placements:[],gridCells:[0]}};return {room:{starships:[a,b],units:[],log:[],shipPositions:[{id:'a',q:0,r:0},{id:'b',q:5,r:0}]},a,b};}
function lay(f,n=1,kind='space-mine-1',seeker=false){f.a.ship.missileAmmo.l[kind]=8;assert.equal(mines.deploy(f.room,f.a,{id:'u',characterId:'pc'},{id:'lay-'+n,missileOrder:{sicId:'l',seeker}},ammo.catalog[kind]),true);return targets.flights(f.room).at(-1);}
test('mine ammunition fills only a mine launcher; surplus and seekers stay in storage',()=>{const {a}=fixture();a.ship.groupCredits=10000;a.ship.missileAmmo={};a.ship.sicInventory.push({id:'m',type:'missile-launcher-1'});a.ship.placements.push({sicId:'m',cell:1});ammo.purchase(a,'space-mine-1',10,maps.definition);assert.equal(ammo.used(a,'l'),4);assert.equal(ammo.used(a,'m'),0);assert.equal(ammo.storage(a)['space-mine-1'],6);ammo.purchase(a,'missile-1',5,maps.definition);assert.equal(ammo.used(a,'m'),3);assert.equal(ammo.used(a,'l'),4);ammo.purchase(a,'magnetic-seeker',2,maps.definition);assert.equal(ammo.storage(a)['magnetic-seeker'],3);});
test('owner does not trigger; crossing the mined hex queues manual damage, even for a detected mine',()=>{const f=fixture(),m=lay(f);mines.advance(f.room,1);assert.equal(m.phase,'mine');const before=structuredClone(f.room.shipPositions);before[1].q=-2;f.room.shipPositions[1].q=2;f.b.sensorState={contacts:{[m.id]:{level:'detected'}}};mines.advance(f.room,.25,before);assert.equal(m.phase,'exploded');assert.equal(missiles.pending(f.room),true);assert.equal(f.b.currentHullHp,100);const roll=targets.flights(f.room).find(m=>m.phase==='impact');assert.equal(missiles.resolveDamage(f.room,roll.id,10).ok,true);assert.equal(f.b.currentHullHp,50);});
test('a single hit must reach threshold; three mines maximum per deployment hex',()=>{const f=fixture(),m=lay(f);lay(f,2);lay(f,3);assert.equal(mines.deploy(f.room,f.a,{id:'u'},{id:'four',missileOrder:{sicId:'l'}},ammo.catalog['space-mine-1']),false);assert.equal(targets.hit(f.room,m.id,7),false);assert.equal(targets.hit(f.room,m.id,7),false);assert.equal(targets.hit(f.room,m.id,8),true);assert.equal(mines.count(f.room,{q:0,r:0}),2);});
test('mines follow smooth gravity and vanish at black-hole center',()=>{const f=fixture(),m=lay(f);f.room.spaceObjects=[{id:'object-hole',kind:'black-hole',q:2,r:0,intensity:3}];nav.advance(f.room,2.5);assert.ok(Math.abs(m.position.q-.5)<1e-7);nav.advance(f.room,5);assert.equal(m.phase,'expired');assert.equal(missiles.pending(f.room),false);});
test('seeker consumes one upgrade and pursues within five units, excluding owner',()=>{const f=fixture(),m=lay(f,1,'space-mine-1',true);mines.advance(f.room,6);assert.equal(m.position.q,1);assert.equal(ammo.storage(f.a)['magnetic-seeker'],0);assert.equal(m.phase,'mine');});
test('electron web opens after twelve seconds, lasts 120 and does no damage',()=>{const f=fixture(),m=lay(f,1,'static-electron-web');mines.advance(f.room,11);assert.equal(m.phase,'mine');mines.advance(f.room,1);assert.equal(m.phase,'web');mines.advance(f.room,119);assert.equal(m.phase,'web');mines.advance(f.room,1);assert.equal(m.phase,'expired');assert.equal(f.b.currentHullHp,100);});

test('three stacked mines request three separate manual hits and discard each shield overflow',()=>{const f=fixture();for(let n=1;n<=3;n++)lay(f,n);f.b.ship.sicInventory=[{id:'s1',type:'shield-1'},{id:'s2',type:'shield-1'}];f.b.ship.placements=[{sicId:'s1',cell:0},{sicId:'s2',cell:1}];const shields=require('../ship-shields');shields.refresh(f.room,{reset:true});for(const layer of Object.values(f.b.shieldSystems))layer.hp=2;shields.refresh(f.room);f.room.shipPositions[1].q=0;mines.advance(f.room,.1);const rolls=targets.flights(f.room).filter(m=>m.phase==='impact');assert.equal(rolls.length,3);missiles.resolveDamage(f.room,rolls[0].id,16);assert.equal(f.b.currentHullHp,100);missiles.resolveDamage(f.room,rolls[1].id,16);assert.equal(f.b.currentHullHp,100);missiles.resolveDamage(f.room,rolls[2].id,16);assert.equal(f.b.currentHullHp,20);});
test('enemy projection does not disclose undetected mine identity or exact position',()=>{const f=fixture(),m=lay(f),sensors=require('../ship-sensors');f.b.ship.sicInventory.push({id:'sn',type:'sensors-1'});f.b.ship.placements.push({sicId:'sn',cell:0});sensors.refresh(f.room);const view=sensors.view(f.room,'b'),contact=view.starships.find(s=>s.id===m.id);assert.ok(!contact||contact.uncertainty);assert.ok(!contact||!contact.isMine);assert.equal(JSON.stringify(view).includes('space-mine-1'),false);});

test('electron web adds twelve masking into or out of its area, six across it',()=>{const f=fixture(),m=lay(f,1,'static-electron-web'),sensors=require('../ship-sensors');m.phase='web';const base=sensors.masking(f.room,f.b);assert.equal(sensors.masking(f.room,f.b,f.a),base+12);f.room.shipPositions[0].q=-4;assert.equal(sensors.masking(f.room,f.b,f.a),base+6);f.room.shipPositions[0].r=5;f.room.shipPositions[1].r=5;assert.equal(sensors.masking(f.room,f.b,f.a),base);});
