const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process'),{once}=require('node:events');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
test('out-of-combat evacuation creates rescue time, preserves exterior location and protects/recover encounters',{timeout:60000},async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sa-october-http-'));let child,base;
 async function start(){child=spawn(process.execPath,['server.js'],{cwd:path.resolve(__dirname,'..'),windowsHide:true,env:{...process.env,PORT:'0',DATABASE_URL:'',SA_LOCAL_DATA_DIR:dir},stdio:['ignore','pipe','pipe']});base=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Startup timeout')),10000);child.stdout.on('data',c=>{const u=String(c).match(/Local:\s+(http:\/\/127\.0\.0\.1:\d+)/)?.[1];if(u){clearTimeout(timer);resolve(u);}});child.stderr.on('data',c=>process.stderr.write(c));});}
 async function stop(){if(child?.exitCode===null){const end=once(child,'exit');child.kill();await end;}}t.after(stop);await start();
 const post=async(route,body,status=200)=>{const r=await fetch(base+'/api/'+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();assert.equal(r.status,status,JSON.stringify(d));return d;},get=p=>fetch(base+'/api/'+p).then(r=>r.json());
 const demo=await post('campaign/showcase/start',{}),created=await post('campaign/create',{name:'Rescue Test',gmCode:'rescue-test'},201),code=created.campaign.code;let token=created.token;
 const saved=await get(`campaign/backup?code=${demo.code}&token=${demo.gmToken}`),c=saved.campaign,f=require('./helpers/field-utility-fixture.cjs')();c.code=code;c.name='Rescue Test';c.showcase=false;
 const person=c.characters[0],source=c.starships.find(s=>s.id==='showcase-pc-ship');source.ship=structuredClone(f.ship.ship);source.ship.id=source.id;source.ship.confirmed=structuredClone(source.ship);source.ship.doorStates={'81:82':'open'};source.characterLocations={[person.id]:{square:131,mesh:0,stationed:true}};source.crewCharacterIds=[person.id];source.crewNpcUnitIds=[];c.npcRoster=[];c.starships=[source];c.encounter=null;
 await post('campaign/restore',{code,token,backup:saved});
 const state=()=>get(`state?room=${code}&token=${token}`),act=(body,status)=>post('action',{roomCode:code,gmToken:token,...body},status);
 await post('campaign/starship/field-utility',{code,token,characterId:person.id,starshipId:source.id,sicId:'pod',kind:'launch-pod',passengers:[person.id],receipt:'rescue-launch'});
 let s=await state();assert.equal(s.hasEngagedClock,true);assert.equal(s.starships.length,1);assert.deepEqual(s.spaceObjects,[]);const unit=s.units.find(u=>u.characterId===person.id);assert.ok(unit.location.escapePodId);assert.equal(unit.location.starshipId,'');assert.equal(unit.location.square,null);assert.equal(s.starships[0].ship.doorStates['81:82'],'open');const original=s.encounterId;
 await act({action:'clearEncounter'},409);assert.equal((await state()).encounterId,original);await act({action:'setHardPaused',paused:true,expectedEncounterId:'stale-encounter'},409);
 await sleep(600);await stop();await start();token=(await post('campaign/open',{name:'Rescue Test',gmCode:'rescue-test'})).token;s=await state();assert.equal(s.encounterId,original);assert.equal(s.units.find(u=>u.characterId===person.id).location.starshipId,'');
 const list=await get(`campaign/checkpoints?code=${code}&token=${token}`);assert.ok(list.checkpoints.length);const checkpoint=list.checkpoints[0];
 await post('campaign/checkpoint/restore',{code,token,checkpointId:checkpoint.id,expectedEncounterId:original,confirmCampaignName:'wrong'},409);
 await post('campaign/checkpoint/restore',{code,token,checkpointId:checkpoint.id,expectedEncounterId:original,confirmCampaignName:'Rescue Test'});s=await state();assert.notEqual(s.encounterId,original);assert.equal(s.hardPaused,true);assert.equal(s.running,false);
 await act({action:'setHardPaused',paused:false,expectedEncounterId:original},409);
 // Opening an airlock outside combat also starts rescue time, after confirmation only.
 let reset=await get(`campaign/backup?code=${code}&token=${token}`),v=reset.campaign.starships[0];v.ship.fieldState={};v.ship.airlockStates={};v.ship.airlocks=[];const maps=require('../ship-map-core');maps.ensureAirlocks(v.ship);const hatch=v.ship.airlocks[0];v.characterLocations={[person.id]:{square:hatch.square,mesh:4,stationed:false}};reset.campaign.encounter=null;
 await post('campaign/restore',{code,token,backup:reset});
 await post('campaign/starship/airlock',{code,token,characterId:person.id,starshipId:v.id,airlockId:hatch.id},409);
 assert.equal((await state()).hasEngagedClock,false);
 await post('campaign/starship/airlock',{code,token,characterId:person.id,starshipId:v.id,airlockId:hatch.id,confirmed:true});s=await state();assert.equal(s.hasEngagedClock,true);assert.equal(s.starships[0].ship.airlockStates[hatch.id].open,true);assert.equal(s.units.find(u=>u.characterId===person.id).pendingShipRolls[0].breachCheck.hazardId,hatch.id);
 // Real server ticks move the interior drone, then wait for the GM's actual repair die.
 reset=await get(`campaign/backup?code=${code}&token=${token}`);v=reset.campaign.starships[0];v.ship={...v.ship,gridCells:[21,22,23,24,25,26],sicInventory:[{id:'bot',type:'hull-breach-repair-drone',status:'installed'}],placements:[{sicId:'bot',cell:21}],airlocks:[{id:'safe',square:26,side:'right'}],airlockStates:{},doorStates:{},breachState:{holes:{hole:{id:'hole',square:23,side:'top',createdAt:1,checked:[]}},processed:{}},breachDroneState:null};
 const actor=reset.campaign.encounter.units.find(u=>u.characterId===person.id);Object.assign(actor,{location:{starshipId:v.id,square:21,mesh:4},pendingShipRolls:[],delayedAction:null,timedAction:null,speed:.01,atb:0,escapedAt:null,defeatedAt:null,vacuum:null});reset.campaign.encounter.units=[actor];reset.campaign.encounter.starships=[structuredClone(v)];Object.assign(reset.campaign.encounter,{activeId:null,activeAction:null,pausedForTurn:false,hardPaused:true,running:false,hasEngagedClock:true,commandRemaining:null});
 await post('campaign/restore',{code,token,backup:reset});await act({action:'setHardPaused',paused:false});await act({action:'setRunning',running:true});await sleep(1200);s=await state();let d=s.starships[0].ship.breachDroneState.drones.bot;assert.equal(d.phase,'moving');assert.ok(d.segment||d.location.mesh!==4);let request;
 for(let i=0;i<200;i++){s=await state();request=s.units[0].pendingShipRolls.find(r=>r.breachDroneRoll);if(request)break;await sleep(100);}assert.ok(request);assert.deepEqual(request.rollSpec.sides,[6]);assert.equal(s.rollPaused,true);d=s.starships[0].ship.breachDroneState.drones.bot;assert.equal(d.location.square,23);
 s=await act({action:'rollShipAction',id:actor.id,rollId:request.id,diceResults:[5]});assert.equal(s.starships[0].ship.breachState.holes.hole.sealed,true);

});
