const test=require('node:test'),assert=require('node:assert/strict');
const shared=require('../ship-state'),sensors=require('../ship-sensors'),rescue=require('../rescue-encounter'),breathing=require('../breathing');
test('ship persistence retains doors, airlocks, impairments, AU and cooldowns and clears old crew copies',()=>{
 const record={id:'a',crewCharacterIds:['pc'],ship:{sicInventory:[{id:'item'}]},characterLocations:{pc:{square:1}}},other={id:'b',characterLocations:{pc:{square:2}},ship:{}};
 const live={id:'a',currentHullHp:9,auState:{current:2},ship:{sicInventory:[{id:'item',impairmentPoints:3,disabled:true}],doorStates:{'1:2':'open'},airlockStates:{a:{open:true}},devastationState:{remaining:10}}};shared.persist(record,live);assert.equal(record.ship.currentHullHp,9);assert.equal(record.ship.sicInventory[0].disabled,true);assert.equal(record.ship.doorStates['1:2'],'open');const next={ship:{sicInventory:[{id:'item'}]}};shared.apply(next,{ship:JSON.parse(JSON.stringify(record.ship))});assert.equal(next.auState.current,2);assert.equal(next.ship.devastationState.remaining,10);
 shared.locations([record,other],[{characterId:'pc',location:{starshipId:'b',square:3,mesh:0}}]);assert.equal(record.characterLocations.pc,undefined);assert.equal(other.characterLocations.pc.square,3);
 shared.locations([record,other],[{characterId:'pc',location:null,vacuum:{sourceShipId:'b'}}]);assert.equal(other.characterLocations.pc.environment,'exterior');
});
test('rescue encounter includes only current occupants of the selected ship, with current locations and character statistics',()=>{
 const c={code:'TEST',characters:[{id:'pc',character:{identity:{characterName:'Nova',raceId:'epoc'},computed:{moveSpeed:7,speed:8,maximumHp:30},health:{current:21},attributes:{dexterity:[1,2]},skills:{Engineering:{tenths:25}}}}],npcRoster:[],starships:[{id:'a',ship:{gridCells:[21,22],sicInventory:[],placements:[],doorStates:{'21:22':'open'}},characterLocations:{pc:{square:22,mesh:0}}},{id:'b',ship:{gridCells:[1],sicInventory:[],placements:[]}}]};const r=rescue.build(c,'a');assert.equal(r.starships.length,1);assert.deepEqual(r.spaceObjects,[]);assert.equal(r.hasEngagedClock,true);assert.equal(r.units[0].location.square,22);assert.equal(r.units[0].location.mesh,0);assert.equal(r.units[0].moveSpeed,7);assert.equal(r.units[0].currentHp,21);assert.equal(r.units[0].engineeringSkill,2.5);assert.deepEqual(r.units[0].dexterityDice,[6,8]);assert.equal(r.starships[0].ship.doorStates['21:22'],'open');
});
test('Android, Epoc and mechanical NPCs do not breathe; ordinary biological races do',()=>{for(const value of [{identity:{raceId:'epoc'}},{identity:{raceId:'android'}},{raceType:'mechanical'},{shipAi:true}])assert.equal(breathing.independent(value),true);assert.equal(breathing.independent({identity:{raceId:'human'}}),false);});
test('analysis after life scan stores a frozen interior; screening hides unknown rooms and preserves older known readings',()=>{
 const ship=id=>({id,title:id,currentHullHp:30,maximumHullHp:40,currentShieldHp:0,maximumShieldHp:0,ship:{gridCells:[21,22,23,41,42,43],sicInventory:[{id:'cockpit',type:'cockpit-1'},{id:'sensor',type:'sensors-1'}],placements:[{sicId:'cockpit',cell:21},{sicId:'sensor',cell:22}],doorStates:{'21:22':'open'},atmosphereState:{cells:{21:85}},breachState:{holes:{h:{id:'h',square:21}}}}});
 const a=ship('a'),b=ship('b'),u={id:'u',queuedEffects:[]},room={starships:[a,b],units:[u,{id:'human',characterName:'Crew',raceId:'human',location:{starshipId:'b',square:21,mesh:4}},{id:'android',raceId:'android',location:{starshipId:'b',square:22,mesh:4}}],shipPositions:[{id:'a',q:0,r:0},{id:'b',q:2,r:0}]},effect={id:'scan',sensorReport:{shipId:'a',targetId:'b'}};
 sensors.resolveReport(room,u,effect);assert.equal(a.sensorState.analyses.b.snapshot,null);a.sensorState.lifeScans={b:{afterAnalysis:true}};sensors.resolveReport(room,u,effect);const snap=a.sensorState.analyses.b.snapshot;assert.equal(snap.crew.length,1);assert.equal(snap.crew[0].id,'human');assert.equal(snap.layout.doorStates['21:22'],'open');b.currentHullHp=12;b.ship.atmosphereState.cells[21]=0;assert.equal(snap.hull.current,30);assert.equal(snap.layout.atmosphereState.cells[21],85);
 b.ship.sicInventory.push({id:'screen',type:'analysis-screening',attachTo:'cockpit'});b.ship.placements.push({sicId:'screen',cell:21});sensors.resolveReport(room,u,effect,()=>1);assert.equal(a.sensorState.analyses.b.lastKnown[0],'cockpit');assert.equal(a.sensorState.analyses.b.snapshot.layout.atmosphereState.cells[21],undefined);assert.equal(a.sensorState.analyses.b.snapshot.crew.length,1);
 delete a.sensorState.analyses.b;a.sensorState.reports=[];sensors.resolveReport(room,u,effect,()=>1);assert.equal(a.sensorState.analyses.b.layout.sicInventory.some(i=>i.id==='cockpit'),false);assert.equal(a.sensorState.analyses.b.layout.screenedRooms[0].name,'Unidentified SIC');
 sensors.resolveReport(room,u,effect,()=>6);assert.equal(a.sensorState.analyses.b.layout.sicInventory.some(i=>i.id==='cockpit'),true);
});
