const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process'),{once}=require('node:events');
const maps=require('../ship-map-core');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
test('oxygen uses private manual checks, survives combat transitions, and releases the natural clock', {timeout:30000},async t=>{
  const directory=fs.mkdtempSync(path.join(os.tmpdir(),'sa-oxygen-http-'));
  const launch=()=>spawn(process.execPath,['server.js'],{cwd:path.resolve(__dirname,'..'),windowsHide:true,env:{...process.env,PORT:'0',DATABASE_URL:'',SA_LOCAL_DATA_DIR:directory},stdio:['ignore','pipe','pipe']});
  let child=launch();
  t.after(async()=>{if(child.exitCode===null){const done=once(child,'exit');child.kill();await done;}});
  const listen=()=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Server timeout')),8000);child.stdout.on('data',c=>{const url=String(c).match(/Local:\s+(http:\/\/127\.0\.0\.1:\d+)/)?.[1];if(url){clearTimeout(timer);resolve(url);}});});
  let base=await listen();
  const post=async(route,body,status=200)=>{const r=await fetch(base+'/api/'+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();assert.equal(r.status,status,JSON.stringify(d));return d;};
  const start=await post('campaign/showcase/start',{});
  const template=await fetch(`${base}/api/campaign/backup?code=${start.code}&token=${start.gmToken}`).then(r=>r.json());
  const created=await post('campaign/create',{name:'Oxygen Persistence',gmCode:'oxygen-test'},201),code=created.campaign.code,token=created.token;
  template.campaign.characters=template.campaign.characters.filter(c=>c.id===start.players[0].id);template.campaign.encounter.units=template.campaign.encounter.units.filter(u=>u.characterId===start.players[0].id||u.id==='unit-showcase-npc-0');
  template.campaign.code=code;template.campaign.name='Oxygen Persistence';
  await post('campaign/restore',{code,token,backup:template});
  const player={...start.players[0],...await post('campaign/character/unlock',{code,characterId:start.players[0].id,pcCode:template.campaign.characters[0].pcCode})};
  const get=route=>fetch(base+'/api/'+route).then(r=>r.json()),campaign=(auth=token)=>get(`campaign/state?code=${code}&token=${auth}`),state=()=>get(`state?room=${code}&token=${token}`),act=body=>post('action',{roomCode:code,gmToken:token,...body});
  const backup=()=>get(`campaign/backup?code=${code}&token=${token}`),restore=backup=>post('campaign/restore',{code,token,backup});
  let c=await campaign();assert.equal(c.combatActive,false,'Explore starts outside combat');
  const ship=c.starships.find(s=>s.crewCharacterIds.includes(player.id)),life=ship.ship.sicInventory.find(i=>i.type==='life-support');assert.ok(life);
  const layout=maps.buildLayout(ship.ship),station=[...layout.footprint].find(([,cell])=>cell.sicId===life.id&&cell.stations.some(s=>s.x===cell.column&&s.y===cell.row));
  const spot=station[1].stations.find(s=>s.x===station[1].column&&s.y===station[1].row);
  await post('campaign/starship/move-character',{code,token,starshipId:ship.id,characterId:player.id,square:station[0],mesh:spot.mesh,stationed:true});
  const switchedAt=Date.now();
  await post('campaign/starship/utility',{code,token:player.token,starshipId:ship.id,characterId:player.id,sicId:life.id,kind:'oxygen',enabled:false});
  c=await campaign();assert.ok(c.oxygen.ships[0].graceRemaining<=165&&c.oxygen.ships[0].graceRemaining>=165-(Date.now()-switchedAt)/1000-.2,'grace timer follows elapsed time rather than HTTP response timing');assert.ok(c.oxygen.ships[0].crew[0].remaining>=0);
  await sleep(1100);assert.ok((await campaign()).oxygen.ships[0].graceRemaining<165);
  const owned=await campaign(player.token);assert.equal(owned.oxygen.ships[0].crew.length,1);assert.equal(owned.oxygen.ships[0].crew[0].id,player.id);
  assert.equal(owned.starships.find(s=>s.id===ship.id).ship.oxygenState,undefined,'raw private state never enters campaign response');
  const jumped=await post('campaign/time/pass',{code,token,amount:10,unit:'minutes',requestId:'oxygen-pass-boundary'});assert.equal(jumped.oxygenInterrupted,true);assert.ok(jumped.advancedMinutes>2&&jumped.advancedMinutes<3);assert.ok(jumped.campaign.oxygen.ships[0].crew[0].request);const replay=await post('campaign/time/pass',{code,token,amount:10,unit:'minutes',requestId:'oxygen-pass-boundary'});assert.equal(replay.advancedMinutes,jumped.advancedMinutes);await post('campaign/time/pass',{code,token,amount:1,unit:'minutes',requestId:'oxygen-pending-block'},400);
  let saved=await backup(),record=saved.campaign.starships.find(s=>s.id===ship.id);record.ship.atmosphereState.cells=Object.fromEntries(Object.keys(record.ship.atmosphereState.cells).map(k=>[k,10]));record.ship.oxygenState.graceRemaining=0;record.ship.oxygenState.crew[player.id].remaining=.05;
  await restore(saved);await sleep(1150);
  c=await campaign();let crew=c.oxygen.ships[0].crew[0],rollId=crew.request?.id;assert.ok(rollId,'real-time clock requests manual dice: '+JSON.stringify(c.oxygen));
  const frozen=structuredClone(c.oxygen);await sleep(1100);assert.deepEqual((await campaign()).oxygen,frozen);
  await post('campaign/oxygen/roll',{code,token:'invalid',actorId:player.id,rollId,score:0},403);
  const current=await state(),units=current.units.map(u=>({...u,preparationUnitId:u.id,speed:.1}));
  units.find(u=>u.characterId===player.id).location={starshipId:ship.id,square:station[0],mesh:spot.mesh,stationed:true,sicId:life.id};
  await act({action:'prepareEncounter',mode:'starship',preparationId:'oxygen-transfer-check',starships:c.starships.filter(s=>current.starships.some(v=>v.id===s.id)),units,shipPositions:current.shipPositions});
  let live=await state();assert.equal(live.rollPaused,true);assert.equal(live.starships.find(s=>s.id===ship.id).ship.oxygenState,undefined);
  assert.equal((await campaign()).oxygen.ships[0].crew[0].request.id,rollId,'preparation retains exact pending request');
  await act({action:'setRunning',running:true});await act({action:'setHardPaused',paused:false});
  const atb=(await state()).units.map(u=>u.atb);await sleep(500);assert.deepEqual((await state()).units.map(u=>u.atb),atb);
  await post('action',{roomCode:code,gmToken:token,action:'playerCombatAction',id:live.units.find(u=>u.characterId===player.id).id,kind:'wait'},409);
  await post('campaign/oxygen/roll',{code,token:player.token,actorId:player.id,rollId,score:100});
  live=await state();assert.equal(live.rollPaused,false);await sleep(350);assert.ok((await state()).units.some((u,i)=>u.atb>live.units[i].atb),'natural clock resumes without changing views');
  await act({action:'setHardPaused',paused:true});let remaining=(await campaign()).oxygen.ships[0].crew[0].remaining;await sleep(1100);assert.equal((await campaign()).oxygen.ships[0].crew[0].remaining,remaining);
  // End a normal campaign encounter, avoiding Explore's explicit reset-to-demo action.
  saved=await backup();saved.campaign.showcase=false;await restore(saved);
  await act({action:'exitEncounter'});c=await campaign();assert.equal(c.combatActive,false);assert.equal(c.oxygen.ships[0].crew[0].difficulty,10);assert.ok(c.oxygen.ships[0].crew[0].remaining<=remaining);
  saved=await backup();record=saved.campaign.starships.find(s=>s.id===ship.id);record.ship.oxygenState.crew[player.id].remaining=.05;
  saved.campaign.characters.find(c=>c.id===player.id).character.health.current=7;await restore(saved);await sleep(1100);
  crew=(await campaign()).oxygen.ships[0].crew[0];rollId=crew.request?.id;assert.ok(rollId);
  const body={code,token:player.token,actorId:player.id,rollId,score:0};await post('campaign/oxygen/roll',body);await post('campaign/oxygen/roll',body);
  c=await campaign();assert.equal(c.characters.find(c=>c.id===player.id).character.health.current,2,'failed check applies 5 HP exactly once');
  saved=await backup();saved.campaign.starships.find(s=>s.id===ship.id).ship.oxygenState.crew[player.id].remaining=.05;await restore(saved);await sleep(1100);
  c=await campaign();assert.equal(c.characters.find(c=>c.id===player.id).character.health.current,-3);assert.equal(c.oxygen.ships[0].crew[0].phase,'unconscious');
  await sleep(1100);assert.equal((await campaign()).characters.find(c=>c.id===player.id).character.health.current,-3);
  const exited=once(child,'exit');child.kill();await exited;child=launch();base=await listen();
  const reopened=await post('campaign/open',{name:'Oxygen Persistence',gmCode:'oxygen-test'});
  assert.equal(reopened.campaign.characters.find(c=>c.id===player.id).character.health.current,-3,'oxygen damage survives a real server restart');
  assert.equal(reopened.campaign.oxygen.ships[0].crew[0].phase,'unconscious');
});
