const test=require('node:test'),assert=require('node:assert/strict'),maps=require('../ship-map-core'),power=require('../ship-power'),cleanser=require('../ship-cleanser'),objects=require('../space-objects');
function fixture(){const ship=require('../showcase-cleanser')(),unit={id:'nova',characterId:'nova',team:'pc',currentHp:30,atb:100,location:{starshipId:ship.id,sicId:ship.id+'-bridge',square:141,mesh:0,stationed:true}};const room={starships:[ship],units:[unit],activeId:unit.id,spaceObjects:objects.normalize([{id:'object-test-planet',kind:'planet',name:'Vesper',variant:'ice',q:0,r:0,quantity:1}]),shipPositions:[{id:ship.id,q:0,r:0}]};power.refresh(room,{reset:true});const body={sicId:ship.id+'-cleanser',kind:'cleanser-charge',targetId:'object-test-planet',receipt:'cleanser-test-receipt'};return {room,ship,unit,body};}
test('planet variant and destroyed aftermath persist through normalization',()=>{const f=fixture(),p=f.room.spaceObjects[0];assert.equal(p.variant,'ice');p.destroyedAt=1234;p.destroyedBy=f.ship.id;assert.deepEqual(objects.normalize([p]),[p]);assert.throws(()=>objects.normalize([{...p,q:.3}]),/whole hex/);});
test('Cleanser build has legal split footprint, power, price and stations',()=>{const f=fixture(),d=maps.definition('planetary-cleanser');assert.equal(d.price,500000);assert.equal(d.energyCost,50);assert.equal(d.threshold,23);assert.equal(d.stations.length,2);assert.equal(maps.exteriorError(f.ship.ship),'');assert.ok(power.designBudget(f.ship).available>=0);assert.ok(maps.propulsion(f.ship).moveSpeed>0);const p=f.ship.ship.placements.find(p=>p.sicId===f.body.sicId);assert.ok(maps.mixedPlacement(f.ship.ship,f.ship.ship.sicInventory.find(i=>i.id===p.sicId),p.cell,p.exteriorCell));});
test('charge consumes one mineral once, diverts all AU and sets Masking zero',()=>{const f=fixture();let r=cleanser.command(f.room,f.unit,f.body);assert.equal(r.ok,true,r.error);assert.equal(f.ship.ship.minerals['Dark Phaeon'],2);assert.equal(cleanser.command(f.room,f.unit,f.body).duplicate,true);assert.equal(f.ship.ship.minerals['Dark Phaeon'],2);power.advance(f.room,20);assert.equal(f.ship.auState.available,0);assert.equal(power.spend(f.room,f.ship.id,1),false);assert.equal(maps.masking(f.ship),0);assert.equal(require('../ship-sensors').masking({...f.room,showcase:true},{...f.ship,sensorScenarioMasking:30}),0);});
test('120 active seconds trigger one shared simulated event; scenery destruction does not harm ships',()=>{const f=fixture();assert.equal(cleanser.command(f.room,f.unit,f.body).ok,true);cleanser.advance(f.room,119);assert.equal(f.room.planetaryEvent,undefined);cleanser.advance(f.room,1);const e=structuredClone(f.room.planetaryEvent);assert.equal(e.phase,'awaitingRoll');assert.equal(e.damage,undefined);assert.equal(cleanser.finish(f.room,Date.now()+1e9),false);cleanser.resolve(f.room,{eventId:e.id,kind:'roll'},{unit:f.unit});cleanser.resolve(f.room,{eventId:e.id,kind:'shown'},{unit:f.unit});cleanser.resolve(f.room,{eventId:e.id,kind:'confirm'},{unit:f.unit});Object.assign(e,f.room.planetaryEvent);assert.ok(e.damage>=100000&&e.damage<=160000);assert.equal(e.dice.length,3);cleanser.advance(f.room,500);assert.deepEqual(f.room.planetaryEvent,e);assert.equal(cleanser.finish(f.room,e.endsAt-1),false);assert.equal(cleanser.finish(f.room,e.endsAt),true);assert.ok(f.room.spaceObjects[0].destroyedAt);assert.equal(f.ship.currentHullHp,198);assert.equal(cleanser.finish(f.room,e.endsAt+1),false);assert.equal(f.ship.ship.cleanserState.cooldown,7200);});
test('invalid target, turn, fuel and power do not start charging',()=>{for(const mutate of [f=>f.body.targetId='absent',f=>f.room.activeId='other',f=>f.ship.ship.minerals={},f=>f.ship.ship.sicInventory.find(i=>i.type==='en-engine-6').disabled=true]){const f=fixture();mutate(f);assert.equal(cleanser.command(f.room,f.unit,f.body).ok,false);assert.notEqual(f.ship.ship.cleanserState?.phase,'charging');}});
test('impairment interrupts charge, loses progress and does not refund mineral',()=>{const f=fixture();cleanser.command(f.room,f.unit,f.body);cleanser.advance(f.room,55);f.ship.ship.sicInventory.find(i=>i.id===f.body.sicId).impaired=true;cleanser.advance(f.room,1);assert.equal(f.ship.ship.cleanserState.phase,'idle');assert.equal(f.ship.ship.minerals['Dark Phaeon'],2);assert.equal(f.room.planetaryEvent,undefined);});
test('abort and campaign cooldown use existing time units',()=>{const f=fixture();cleanser.command(f.room,f.unit,f.body);assert.equal(cleanser.command(f.room,f.unit,{...f.body,kind:'cleanser-abort',receipt:'abort-cleanser-once'}).ok,true);assert.equal(f.ship.ship.cleanserState.phase,'idle');f.ship.ship.cleanserState.cooldown=7200;cleanser.passTime(f.ship,119);assert.equal(f.ship.ship.cleanserState.cooldown,60);cleanser.passTime(f.ship,1);assert.equal(f.ship.ship.cleanserState.cooldown,0);});
test('restart retains charge, simulated result and completion deadline',()=>{const f=fixture();cleanser.command(f.room,f.unit,f.body);cleanser.advance(f.room,42);const room=structuredClone(f.room);cleanser.advance(room,78);cleanser.resolve(room,{eventId:room.planetaryEvent.id,kind:'roll'},{gm:true});cleanser.resolve(room,{eventId:room.planetaryEvent.id,kind:'shown'},{gm:true});cleanser.resolve(room,{eventId:room.planetaryEvent.id,kind:'confirm'},{gm:true});const saved=structuredClone(room);cleanser.finish(saved,saved.planetaryEvent.endsAt);assert.equal(saved.planetaryEvent.damage,room.planetaryEvent.damage);assert.ok(saved.spaceObjects[0].destroyedAt);});
test('planets cannot be collected as cargo and crew ships can share their hex',()=>{const f=fixture();assert.deepEqual(f.room.shipPositions[0],{id:f.ship.id,q:0,r:0});assert.equal(f.room.spaceObjects[0].q,0);const field=require('../ship-field-utilities'),old=require('./helpers/field-utility-fixture.cjs')();old.room.spaceObjects=f.room.spaceObjects;old.room.spaceObjects[0].q=0;old.room.spaceObjects[0].r=0;const r=field.command(old.room,old.unit,{sicId:'tractor',starshipId:old.ship.id,kind:'collect-object',targetId:f.room.spaceObjects[0].id,receipt:'collect-planet-denied'});assert.equal(r.ok,false);assert.match(r.error,/cannot be collected/);});

test('planets and aftermath draw beneath ships and reuse compact map sprites',()=>{
 const fs=require('node:fs'),vm=require('node:vm'),f=fixture(),context={window:{SAShipMap:maps,SAShipDistances:require('../ship-distances')},document:{addEventListener(){}}};vm.createContext(context);vm.runInContext(fs.readFileSync(require.resolve('../space-map.js'),'utf8'),context);
 const render=()=>context.window.SASpaceMap.markup([f.ship],f.room.shipPositions,false,{spaceObjects:f.room.spaceObjects});let html=render();assert.ok(html.indexOf('planet-ice.webp')<html.indexOf('data-space-ship="'+f.ship.id+'"'));assert.match(html,/7 hexes/);f.room.spaceObjects[0].destroyedAt=1;html=render();assert.match(html,/planet-debris.webp/);assert.ok(html.indexOf('planet-debris.webp')<html.indexOf('data-space-ship="'+f.ship.id+'"'));
});

test('damage sequencing is owned, retry safe and restart safe through GM takeover',()=>{
 const f=fixture();cleanser.command(f.room,f.unit,f.body);cleanser.advance(f.room,120);
 const id=f.room.planetaryEvent.id,step=kind=>({eventId:id,kind});
 assert.throws(()=>cleanser.resolve(f.room,step('roll'),{unit:{id:'stranger'}}),/operator/);
 assert.throws(()=>cleanser.resolve(f.room,step('confirm'),{unit:f.unit}),/View/);
 cleanser.resolve(f.room,step('roll'),{unit:f.unit});const snapshot=structuredClone(f.room.planetaryEvent);
 cleanser.resolve(f.room,step('roll'),{unit:f.unit});assert.deepEqual(f.room.planetaryEvent,snapshot);
 const restored=structuredClone(f.room);cleanser.resolve(restored,step('takeover'),{gm:true});
 assert.throws(()=>cleanser.resolve(restored,step('shown'),{unit:f.unit}),/operator/);
 cleanser.resolve(restored,step('shown'),{gm:true});assert.equal(restored.spaceObjects[0].destroyedAt,undefined);
 cleanser.resolve(restored,step('confirm'),{gm:true});const deadline=restored.planetaryEvent.endsAt;
 cleanser.resolve(restored,step('confirm'),{gm:true});assert.equal(restored.planetaryEvent.endsAt,deadline);assert.equal(restored.planetaryEvent.damage,snapshot.damage);
 cleanser.finish(restored,deadline);assert.ok(restored.spaceObjects[0].destroyedAt);
});
