const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process'),{once}=require('node:events');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
test('four repeater shots keep normal manual roll ownership, retry safety, clock freeze and restart persistence',{timeout:20000},async t=>{
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'sa-repeater-http-'));let child,base,token;
 async function start(){child=spawn(process.execPath,['server.js'],{cwd:path.resolve(__dirname,'..'),windowsHide:true,env:{...process.env,PORT:'0',DATABASE_URL:'',SA_LOCAL_DATA_DIR:directory},stdio:['ignore','pipe','pipe']});base=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Server startup timeout')),8000);child.stdout.on('data',c=>{const url=String(c).match(/Local:\s+(http:\/\/127\.0\.0\.1:\d+)/)?.[1];if(url){clearTimeout(timer);resolve(url);}});});}
 async function stop(){if(child?.exitCode===null){const done=once(child,'exit');child.kill();await done;}}t.after(stop);await start();
 const post=async(route,body,status=200)=>{const response=await fetch(base+'/api/'+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await response.json();assert.equal(response.status,status,JSON.stringify(data));return data;},get=p=>fetch(base+'/api/'+p).then(r=>r.json());
 const demo=await post('campaign/showcase/start',{}),created=await post('campaign/create',{name:'Repeater test',gmCode:'repeater-test'},201),code=created.campaign.code;token=created.token;
 const saved=await get(`campaign/backup?code=${demo.code}&token=${demo.gmToken}`),c=saved.campaign,person=c.characters[0],pilot=c.encounter.units.find(u=>u.characterId===person.id),npc=c.encounter.units.find(u=>u.team==='npc');
 const make=(id,controlType)=>({id,title:id,controlType,crewCharacterIds:controlType==='pc'?[person.id]:[],currentHullHp:80,maximumHullHp:80,ship:{minerals:{Iron:6},currentHullHp:80,maximumHullHp:80,gridCells:Array.from({length:80},(_,n)=>82+Math.floor(n/10)*20+n%10),sicInventory:[{id:'cp',type:'cockpit-1'},{id:'sn',type:'sensors-3'},{id:'en',type:'en-au-engine-4'},{id:'lock',type:'lock-on-1'},{id:'gun',type:'ballistic-rail-repeater'}],placements:[{sicId:'cp',cell:82},{sicId:'sn',cell:83},{sicId:'en',cell:164},{sicId:'lock',cell:84},{sicId:'gun',cell:46}]}});
 const source=make('repeater-source','pc'),target=make('repeater-target','gm');source.sensorState={contacts:{[target.id]:{id:target.id,level:'detected'}}};source.characterLocations={[person.id]:{starshipId:source.id,sicId:'cp',square:82,mesh:0,stationed:true}};
 Object.assign(c,{code,name:'Repeater test',showcase:false,starships:[source,target]});Object.assign(pilot,{location:source.characterLocations[person.id],atb:100,speed:.1,currentHp:30,defeatedAt:null,delayedAction:null,delayTimer:null,timedAction:null,consoleHold:null,pendingShipRolls:[]});Object.assign(npc,{location:{starshipId:target.id,sicId:'cp',square:82,mesh:0,stationed:true},atb:0,speed:.1,currentHp:30,defeatedAt:null,automationMode:'off',delayedAction:null,delayTimer:null,timedAction:null,consoleHold:null,pendingShipRolls:[]});
 Object.assign(c.encounter,{starships:[source,target],units:[pilot,npc],shipPositions:[{id:source.id,q:0,r:0},{id:target.id,q:1,r:0}],spaceObjects:[],hasEngagedClock:true,encounterEndedAt:null,activeId:pilot.id,pausedForTurn:true,running:false,hardPaused:true,resumeAfterTurn:true,commandRemaining:120,commandTotal:120});await post('campaign/restore',{code,token,backup:saved});
 const act=(body,status=200)=>post('action',{roomCode:code,gmToken:token,...body},status),state=()=>get(`state?room=${code}&token=${token}`),pending=s=>s.units.find(u=>u.id===pilot.id).delayedAction;
 const fire={action:'weaponCommand',id:pilot.id,sicId:'gun',targetId:target.id,requestId:'http-repeater-burst'};let s=await act(fire),roll=pending(s);assert.equal(roll.awaitingRoll,true);assert.equal(roll.rollBeforeDelay,true);assert.equal(roll.weaponOrder.burst.total,4);assert.equal(s.starships.find(s=>s.id===source.id).ship.minerals.Iron,5);s=await act(fire);assert.equal(s.starships.find(s=>s.id===source.id).ship.minerals.Iron,5);
 await act({action:'rollShipAction',id:pilot.id,rollId:roll.id,score:100});await act({action:'setHardPaused',paused:false});await act({action:'setRunning',running:true});await sleep(1300);s=await state();roll=pending(s);assert.ok(roll.weaponDamage);assert.deepEqual(roll.rollSpec.sides,[10]);assert.equal(s.starships.find(s=>s.id===target.id).currentHullHp,80);assert.equal(s.rollPaused,true);
 const frozen=s.units.map(u=>u.atb);await sleep(250);assert.deepEqual((await state()).units.map(u=>u.atb),frozen);
 const firstDamage={action:'rollShipAction',id:pilot.id,rollId:roll.id,diceResults:[2]};s=await act(firstDamage);roll=pending(s);assert.equal(roll.weaponOrder.burst.shot,2);assert.equal(roll.rollBeforeDelay,false);assert.equal(roll.consumeTurn,false);assert.equal(roll.awaitingRoll,true);assert.equal(roll.rollController,'gm');const secondId=roll.id;s=await act(firstDamage);assert.equal(pending(s).id,secondId);assert.equal(s.starships.find(s=>s.id===source.id).ship.minerals.Iron,4);
 s=await act({action:'rollShipAction',id:pilot.id,rollId:secondId,score:-100});assert.equal(pending(s).weaponOrder.burst.shot,3);assert.equal(pending(s).awaitingRoll,true);assert.equal(s.starships.find(s=>s.id===source.id).ship.minerals.Iron,3);
 for(let i=0;i<30;i++){const persisted=await get(`campaign/backup?code=${code}&token=${token}`);if(persisted.campaign.encounter.units.find(u=>u.id===pilot.id)?.delayedAction?.weaponOrder?.burst?.shot===3)break;if(i===29)throw Error('Third shot was not persisted');await sleep(50);}await stop();await start();token=(await post('campaign/open',{name:'Repeater test',gmCode:'repeater-test'})).token;s=await state();roll=pending(s);assert.equal(roll.weaponOrder.burst.shot,3);assert.equal(roll.rollBeforeDelay,false);assert.equal(roll.rollController,'gm');const pc=await post('campaign/character/unlock',{code,characterId:person.id,pcCode:person.pcCode});await post('action',{roomCode:code,characterId:person.id,characterToken:pc.token,action:'rollShipAction',id:pilot.id,rollId:roll.id,score:100},403);await act({action:'setHardPaused',paused:false});
 for(const damage of [3,6]){s=await act({action:'rollShipAction',id:pilot.id,rollId:pending(await state()).id,score:100});roll=pending(s);assert.ok(roll.weaponDamage);assert.deepEqual(roll.rollSpec.sides,[10]);s=await act({action:'rollShipAction',id:pilot.id,rollId:roll.id,diceResults:[damage]});}
 assert.equal(pending(s),null);assert.equal(s.rollPaused,false);assert.equal(s.starships.find(s=>s.id===target.id).currentHullHp,69);assert.equal(s.starships.find(s=>s.id===source.id).ship.minerals.Iron,2);assert.equal(s.units.find(u=>u.id===pilot.id).atb,0);assert.equal(s.starships.find(s=>s.id===source.id).weaponState.reports.filter(r=>r.shot).length,4);
});
