const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const source=name=>fs.readFileSync(path.join(__dirname,'..',name),'utf8');
function setupContext(overrides={}){
 const calls=[],c=vm.createContext({campaign:{combatActive:false},encounterState:{units:[{id:'pc'}]},forceEncounterBuilder:false,encounterSetupRequested:false,dom:{atbLive:{hidden:false},atbSetup:{hidden:true},existingEncounterActions:{},encounterBuilder:{}},showEncounterLive(){calls.push('live');},refreshEncounterState:async()=>{calls.push('refresh');},renderEncounterBuilder(){calls.push('builder');},updateExitEncounterVisibility(){},showMessage(){},document:{},...overrides});
 const s=source('gm.js');vm.runInContext(s.slice(s.indexOf('function showEncounterSetup('),s.indexOf('async function resumeEncounterWithFreshCharacters')),c);return{c,calls};
}
test('returning to Combat preserves a prepared encounter before its first clock engagement',()=>{const {c,calls}=setupContext();c.showEncounterSetup();assert.equal(calls[0],'live');assert.equal(c.dom.atbLive.hidden,false);});
test('explicit encounter setup and ended encounters do not force the live screen',()=>{for(const options of [{explicit:true},{forceBuilder:true}]){const{c,calls}=setupContext();c.showEncounterSetup(options);assert.equal(c.dom.atbLive.hidden,true);assert.equal(calls.includes('live'),false);}const{c,calls}=setupContext({encounterState:{units:[{}],encounterEndedAt:123}});c.showEncounterSetup();assert.equal(calls.includes('live'),false);});
test('ended Explore templates expose preparation instead of an unusable Resume button',()=>{
 const dom={encounterStatus:{},existingEncounterActions:{},existingEncounterSummary:{},encounterBuilder:{}},c=vm.createContext({dom,forceEncounterBuilder:false,encounterState:{units:[{characterName:'Nova'}],encounterEndedAt:123},renderEncounterBuilder(){},updateExitEncounterVisibility(){}});
 const s=source('gm.js');vm.runInContext(s.slice(s.indexOf('function renderEncounterStatus('),s.indexOf('function updateExitEncounterVisibility(')),c);
 c.renderEncounterStatus();assert.equal(dom.existingEncounterActions.hidden,true);assert.equal(dom.encounterBuilder.hidden,false);assert.equal(dom.encounterStatus.textContent,'No Active Encounter');
 c.encounterState.encounterEndedAt=null;c.renderEncounterStatus();assert.equal(dom.existingEncounterActions.hidden,false);assert.equal(dom.encounterBuilder.hidden,true);
});
function linkContext(gm){
 const imports=[],links=[],messages=[],c=vm.createContext({EMBEDDED_GM_MODE:gm,draft:{confirmedOnce:true,confirmed:{},title:'Test ship'},statesMatch:()=>true,window:{SARoomV03:{importIntoRoom:async(...args)=>{imports.push(args);return true;}}},activeCampaignCredentials:()=>({token:'gm-auth'}),campaignApi:async(url,body)=>{links.push({url,body});return{campaignName:'Test',starship:{controlType:'gm'},accessKey:'ship-access'};},saveDraft(){},refreshLinkedCampaign:async()=>{},campaignMessage:(...a)=>messages.push(a),linkedCampaignState:null});
 const s=source('starship.js');vm.runInContext(s.slice(s.indexOf('async function linkStarship('),s.indexOf('async function syncLinkedStarship(')),c);
 const event={preventDefault(){},currentTarget:{querySelector:selector=>({value:selector.includes('campaign-code')?' test ':'gm'})}};return{c,imports,links,messages,event};
}
test('GM ship creation links directly with GM authorization instead of submitting a player import',async()=>{const{c,imports,links,event}=linkContext(true);await c.linkStarship(event);assert.equal(imports.length,0);assert.equal(links.length,1);assert.equal(links[0].body.token,'gm-auth');assert.equal(links[0].body.code,'TEST');assert.equal(c.draft.campaignLink.controlType,'gm');});
test('player ship creation continues to use GM approval, even on a device with GM credentials',async()=>{const{c,imports,links,event}=linkContext(false);await c.linkStarship(event);assert.equal(imports.length,1);assert.equal(links.length,0);assert.equal(c.draft.campaignLink,undefined);});
function confirmationContext(){
 const nodes=[],doc={defaultView:{frameElement:null},createElement(tag){const node={tag,style:{},children:[],listeners:{},append(...children){this.children.push(...children);},setAttribute(){},addEventListener(name,fn){this.listeners[name]=fn;},showModal(){this.open=true;},close(){this.open=false;this.listeners.close?.();},remove(){this.removed=true;},focus(){this.focused=true;}};nodes.push(node);return node;},body:{append(){}}},c=vm.createContext({document:doc,window:{addEventListener(){},removeEventListener(){}},state:{encounterId:'one'}});
 const s=source('app.js');vm.runInContext(s.slice(s.indexOf('let encounterConfirmationPending='),s.indexOf('resetAll.addEventListener("click", async')),c);return{c,nodes};
}
test('encounter confirmation cancels safely and ignores duplicate clicks',async()=>{const{c,nodes}=confirmationContext();const first=c.confirmEncounterChange('End?','End this encounter?','End');assert.equal(await c.confirmEncounterChange('End?','','End'),false);nodes.find(n=>n.tag==='button'&&n.textContent==='Cancel').onclick();assert.equal(await first,false);assert.equal(nodes.find(n=>n.tag==='dialog').removed,true);});
test('clearing requires the exact campaign name and cannot confirm a replacement encounter',async()=>{const{c,nodes}=confirmationContext();const pending=c.confirmEncounterChange('Clear?','Enter name','Clear','Exact Campaign');const field=nodes.find(n=>n.tag==='input'),form=nodes.find(n=>n.tag==='form'),accept=nodes.find(n=>n.type==='submit');field.value='wrong';field.listeners.input();assert.equal(accept.disabled,true);form.onsubmit({preventDefault(){}});assert.equal(nodes.find(n=>n.tag==='dialog').open,true);field.value='Exact Campaign';field.listeners.input();assert.equal(accept.disabled,false);c.state.encounterId='two';form.onsubmit({preventDefault(){}});assert.equal(await pending,false);});
test('accepted encounter confirmation resolves once without a native browser prompt',async()=>{const{c,nodes}=confirmationContext();const pending=c.confirmEncounterChange('End?','End this encounter?','End');nodes.find(n=>n.tag==='form').onsubmit({preventDefault(){}});assert.equal(await pending,true);});
