const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process'),{once}=require('node:events');
test('NPC weapon Exertion dice validate once and Reset undoes the roll without resetting ships',{timeout:20000},async t=>{
 const child=spawn(process.execPath,['server.js'],{cwd:path.resolve(__dirname,'..'),windowsHide:true,env:{...process.env,PORT:'0',DATABASE_URL:'',SA_LOCAL_DATA_DIR:fs.mkdtempSync(path.join(os.tmpdir(),'sa-revision-undo-'))},stdio:['ignore','pipe','pipe']});
 t.after(async()=>{if(child.exitCode===null&&child.signalCode===null){const done=once(child,'exit');child.kill();await done;}});
 const base=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Startup timeout')),8000);child.stdout.on('data',c=>{const url=String(c).match(/Local:\s+(http:\/\/127\.0\.0\.1:\d+)/)?.[1];if(url){clearTimeout(timer);resolve(url);}});child.once('error',reject);});
 const post=async(route,body,status=200)=>{const r=await fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await r.json();assert.equal(r.status,status,JSON.stringify(data));return data;};
 const room=await post('/api/campaign/showcase/start',{});await require('./helpers/combat-demo.cjs')(base,room);
 const act=(body,status=200)=>post('/api/action',{roomCode:room.code,gmToken:room.gmToken,...body},status),state=()=>fetch(`${base}/api/state?room=${room.code}&token=${room.gmToken}`).then(r=>r.json());
 await act({action:'setHardPaused',paused:true});let s=await state();const npc=s.units.find(u=>u.team==='npc'),ship=s.starships.find(x=>x.id===npc.location.starshipId),target=s.starships.find(x=>x.id!==ship.id),weapon=ship.ship.sicInventory.find(i=>i.type.startsWith('rapid-laser-'));assert.ok(weapon);
 const backup=await fetch(`${base}/api/campaign/backup?code=${room.code}&token=${room.gmToken}`).then(r=>r.json());backup.campaign.encounter={...s,shipPositions:[{id:ship.id,q:0,r:0},{id:target.id,q:2,r:0}]};backup.campaign.encounter.starships.find(x=>x.id===ship.id).ship.sicInventory.find(i=>i.id===weapon.id).type='rapid-laser-4';await post('/api/campaign/restore',{code:room.code,token:room.gmToken,backup});
 const bridge=ship.ship.sicInventory.find(i=>i.type==='bridge-1'),square=ship.ship.placements.find(p=>p.sicId===bridge.id).cell;await act({action:'setCombatLocation',id:npc.id,location:{starshipId:ship.id,square,mesh:0}});
 await act({action:'nudge',id:npc.id,amount:100-npc.atb});s=await act({action:'weaponCommand',id:npc.id,sicId:weapon.id,targetId:target.id,requestId:'exertion-fire-once'});
 const pending=s.units.find(u=>u.id===npc.id).delayedAction,spec=pending.rollSpec;assert.equal(spec.exertionAvailable,1);const before=structuredClone(s),dice=[...spec.sides.map(n=>n),12],body={action:'rollShipAction',id:npc.id,rollId:pending.id,diceResults:dice,score:dice.reduce((a,b)=>a+b,0)+spec.bonus+1,exertion:1};
 s=await act(body);assert.equal(s.units.find(u=>u.id===npc.id).exertionCurrent,0);assert.equal(s.units.find(u=>u.id===npc.id).delayedAction.awaitingRoll,false);
 s=await act(body);assert.equal(s.units.find(u=>u.id===npc.id).exertionCurrent,0);
 await act({...body,rollId:'stale-invalid-roll'},409);s=await act({action:'reset'});
 const restored=s.units.find(u=>u.id===npc.id);assert.equal(restored.delayedAction.id,pending.id);assert.equal(restored.delayedAction.awaitingRoll,true);assert.equal(restored.delayedAction.rollSpec.exertionAvailable,1);assert.equal(s.starships.find(x=>x.id===ship.id).auState.current,before.starships.find(x=>x.id===ship.id).auState.current);assert.deepEqual(s.shipPositions,before.shipPositions);assert.equal(s.units.length,before.units.length);
 // A failed oxygen check must not incapacitate a character who still has HP.
 const oxygenSave=await fetch(`${base}/api/campaign/backup?code=${room.code}&token=${room.gmToken}`).then(r=>r.json()),player=room.players.find(p=>p.name==='Nova Vale'),pc=oxygenSave.campaign.encounter.units.find(u=>u.characterId===player.id),own=oxygenSave.campaign.encounter.starships.find(x=>x.id===pc.location.starshipId);
 for(const u of oxygenSave.campaign.encounter.units){u.delayedAction=null;u.pendingShipRolls=[];u.atb=0;}Object.assign(pc,{currentHp:20,atb:100,defeatedAt:null,oxygenUnconscious:false});
 const pcBridge=own.ship.sicInventory.find(i=>i.type==='bridge-1');pc.location={starshipId:own.id,sicId:pcBridge.id,square:own.ship.placements.find(p=>p.sicId===pcBridge.id).cell,mesh:0,stationed:true};
 oxygenSave.campaign.characters.find(c=>c.id===player.id).character.health.current=20;
 own.ship.oxygenEnabled=false;own.ship.oxygenState={graceRemaining:0,receipts:[],generation:'oxygen-check',crew:{[player.id]:{id:player.id,characterId:player.id,name:'Nova Vale',phase:'resist',remaining:0,difficulty:14,request:{id:'positive-hp-oxygen',dice:[6,6],skill:1,difficulty:14}}}};
 Object.assign(oxygenSave.campaign.starships.find(s=>s.id===own.id).ship,{oxygenEnabled:false,oxygenState:structuredClone(own.ship.oxygenState)});
 Object.assign(oxygenSave.campaign.encounter,{hasEngagedClock:true,encounterEndedAt:null,activeId:pc.id,pausedForTurn:true,hardPaused:true});await post('/api/campaign/restore',{code:room.code,token:room.gmToken,backup:oxygenSave});
 await post('/api/campaign/oxygen/roll',{code:room.code,token:player.token,actorId:player.id,rollId:'positive-hp-oxygen',score:0});s=await state();const breathing=s.units.find(u=>u.id===pc.id);assert.equal(breathing.currentHp,15);assert.ok(!breathing.defeatedAt&&!breathing.oxygenUnconscious);
 await act({action:'nudge',id:pc.id,amount:100-breathing.atb});s=await act({action:'playerCombatAction',id:pc.id,kind:'move',route:[{...pc.location,stationed:false,mesh:1}]});assert.equal(s.units.find(u=>u.id===pc.id).timedAction.kind,'move');
});
