const test=require('node:test'),assert=require('node:assert/strict'),fab=require('../ship-fabrication'),rooms=require('../ship-crew-rooms'),maps=require('../ship-map-core'),fixture=require('./helpers/science-fixture.cjs');
const cmd=(f,extra={})=>rooms.command(f.room,f.unit,{kind:'fabricate-add',starshipId:f.ship.id,sicId:'vr',machineId:'printer',recipeType:'sensors-7',requestId:crypto.randomUUID(),...extra},{campaign:f.campaign,outsideCombat:true});
test('legacy mineral spellings feed recipes without duplicating stocks',()=>{const f=fixture();delete f.ship.ship.minerals['Dark Phazon'];f.ship.ship.minerals['Dark Phaeon']=2;cmd(f);assert.equal(f.ship.ship.minerals['Dark Phaeon'],1);assert.equal(f.ship.ship.minerals['Dark Phazon'],undefined);});
test('multiple printers progress concurrently through a large time advance',()=>{const f=fixture();f.ship.ship.sicInventory.push({id:'printer2',type:'3d-printer',attachTo:'vr'});f.ship.ship.placements.push({sicId:'printer2',cell:27});cmd(f);cmd(f,{machineId:'printer2'});fab.advance(f.room,f.campaign,604800);assert.equal(f.ship.ship.sicInventory.filter(i=>i.printed).length,2);assert.equal(f.ship.ship.minerals['Dark Phazon'],8);});
test('printed recipes and shared lab upgrades have no floor footprint',()=>{const f=fixture();for(const type of ['3d-printer','mineral-processor','blueprint']){assert.equal(maps.definition(type).width,0);assert.equal(maps.definition(type).addon,'science');}assert.equal(fab.recipes.length,18);assert.equal(fab.recipe('sensors-7').seconds,604800);assert.deepEqual(fab.recipe('sensors-7').minerals,{'Dark Phazon':1});assert.equal(fab.recipe('blueprint'),null);assert.equal(maps.exteriorError(f.ship.ship),'');});
test('six-slot queue consumes minerals only at job start and emits exactly one stored SIC',()=>{const f=fixture();const body={requestId:'print-receipt-001'};cmd(f,body);cmd(f,body);for(let i=1;i<6;i++)cmd(f);assert.equal(fab.state(f.ship).systems.printer.queue.length,6);assert.equal(f.ship.ship.minerals['Dark Phazon'],9);assert.throws(()=>cmd(f),/six/);rooms.advance(f.room,f.campaign,302400);assert.equal(fab.state(f.ship).systems.printer.queue[0].remaining,302400);rooms.advance(f.room,f.campaign,302400);assert.equal(f.ship.ship.sicInventory.filter(i=>i.printed).length,1);assert.equal(f.ship.ship.minerals['Dark Phazon'],8);assert.equal(fab.state(f.ship).systems.printer.queue.length,5);assert.match(f.campaign.privateNotes[0].message,/finished crafting Sensors 7/);rooms.advance(f.room,f.campaign,0);assert.equal(f.ship.ship.sicInventory.filter(i=>i.printed).length,1);});
test('missing minerals desaturate recipe state; waiting jobs resume without double payment',()=>{const f=fixture();f.ship.ship.minerals['Dark Phazon']=1;cmd(f);assert.equal(fab.inspect(f.room,f.ship,'vr').blueprints[0].available,false);f.ship.ship.minerals['Dark Phazon']=1;cmd(f);f.ship.ship.minerals['Dark Phazon']=0;fab.advance(f.room,f.campaign,604800);assert.equal(fab.state(f.ship).systems.printer.queue[0].started,false);assert.equal(fab.state(f.ship).systems.printer.queue[0].paused,'Waiting for minerals');f.ship.ship.minerals['Dark Phazon']=1;fab.advance(f.room,f.campaign,1);assert.equal(f.ship.ship.minerals['Dark Phazon'],0);assert.equal(fab.state(f.ship).systems.printer.queue[0].remaining,604799);});
test('power/impairment pause and destruction loses only unfinished jobs',()=>{const f=fixture();cmd(f);fab.advance(f.room,f.campaign,100);const lab=f.ship.ship.sicInventory.find(i=>i.id==='vr');lab.disabled=true;fab.advance(f.room,f.campaign,604800);assert.equal(fab.state(f.ship).systems.printer.queue[0].remaining,604700);lab.disabled=false;lab.impaired=true;fab.advance(f.room,f.campaign,604800);assert.equal(fab.state(f.ship).systems.printer.queue[0].remaining,604700);delete lab.impaired;lab.status='destroyed';fab.advance(f.room,f.campaign,1);assert.equal(fab.state(f.ship).systems.printer.queue.length,0);assert.equal(f.ship.ship.minerals['Dark Phazon'],9);assert.equal(f.ship.ship.sicInventory.filter(i=>i.printed).length,0);});
test('processor executes exact recipes with leftover time, shared storage and durable progress',()=>{const f=fixture();for(let i=0;i<6;i++)cmd(f,{machineId:'processor',recipeType:'Zennium'});fab.advance(f.room,f.campaign,44);assert.equal(f.ship.ship.minerals.Zennium,2);assert.equal(f.ship.ship.minerals.Iron,7);const restored=structuredClone(f.room);fab.advance(restored,f.campaign,46);assert.equal(restored.starships[0].ship.minerals.Zennium,6);assert.equal(restored.starships[0].ship.minerals.Iron,4);assert.equal(fab.state(restored.starships[0]).systems.processor.queue.length,0);});
test('queue cancellation and receipt reuse cannot duplicate or refund material',()=>{const f=fixture();cmd(f,{requestId:'shared-print-001'});assert.throws(()=>cmd(f,{requestId:'shared-print-001',machineId:'processor',recipeType:'Zennium'}),/Receipt/);const job=fab.state(f.ship).systems.printer.queue[0];cmd(f,{kind:'fabricate-cancel',jobId:job.id});assert.equal(f.ship.ship.minerals['Dark Phazon'],9);assert.equal(fab.state(f.ship).systems.printer.queue.length,0);f.unit.location.stationed=false;assert.throws(()=>cmd(f),/station/);});

test('legacy static cards expose the same crafting recipes to the server',()=>{const fs=require('node:fs'),html=fs.readFileSync(require.resolve('../starship.html'),'utf8');for(const card of html.matchAll(/<article[^>]*data-sic-card="([^"]+)"[\s\S]*?<\/article>/g)){const text=card[0].match(/<dt>Crafting<\/dt><dd>(.*?)<\/dd>/)?.[1];if(text&&!/N\/A|Not Available/.test(text))assert.ok(fab.recipe(card[1]),card[1]);}});
