const test=require('node:test'),assert=require('node:assert/strict'),{CampaignApi}=require('../campaign-api');
test('campaign fabrication survives restart, GM time, stale edits, unauthorized orders and completion notices',async()=>{
 const records=new Map(),store={get:async c=>structuredClone(records.get(c)||null),create:async c=>{records.set(c.code,structuredClone(c));return true;},save:async c=>records.set(c.code,structuredClone(c)),findByName:async()=>[]};let api=new CampaignApi({store,storageMode:'test'});
 const call=async(path,body={},status=200)=>{let result;await api.handle({method:'POST'},{},new URL('http://test/api/campaign/'+path),async()=>body,(_,code,value)=>{assert.equal(code,status,JSON.stringify(value));result=value;});return result;};
 const created=await call('v03/create',{name:'Fabrication'},201),code=created.campaign.code,token=created.token,f=require('./helpers/science-fixture.cjs')();const campaign=await api.campaign(code);campaign.starships=[f.ship];campaign.characters=[f.character];await api.save(campaign);const stale=structuredClone(f.ship.ship);
 const body={code,token,characterId:'pc',starshipId:f.ship.id,sicId:'vr',machineId:'printer',recipeType:'sensors-7',kind:'fabricate-add',requestId:'science-job-001'};
 await call('starship/crew-room',{...body,token:'not-authorized'},403);await call('starship/crew-room',body);await call('starship/crew-room',body);await call('time/pass',{code,token,amount:3,unit:'days',requestId:'science-time-001'});
 let saved=await api.campaign(code);assert.equal(saved.starships[0].ship.fabricationState.systems.printer.queue.length,1);assert.equal(saved.starships[0].ship.fabricationState.systems.printer.queue[0].remaining,345600);assert.equal(saved.starships[0].ship.minerals['Dark Phazon'],9);
 await call('starship/save',{code,token,starship:stale,buildRevision:0});saved=await api.campaign(code);assert.equal(saved.starships[0].ship.fabricationState.systems.printer.queue[0].remaining,345600);
 api=new CampaignApi({store,storageMode:'test'});await call('time/pass',{code,token,amount:4,unit:'days',requestId:'science-time-002'});saved=await api.campaign(code);assert.equal(saved.starships[0].ship.sicInventory.filter(i=>i.printed).length,1);assert.ok(saved.privateNotes.some(n=>/finished crafting Sensors 7/.test(n.message)));
 await call('starship/save',{code,token,starship:stale,buildRevision:1},409);await call('time/pass',{code,token,amount:4,unit:'days',requestId:'science-time-002'});saved=await api.campaign(code);assert.equal(saved.starships[0].ship.sicInventory.filter(i=>i.printed).length,1);
 await call('starship/crew-room',{...body,requestId:'science-job-002'});saved=await api.campaign(code);const job=saved.starships[0].ship.fabricationState.systems.printer.queue[0];await call('starship/crew-room',{...body,kind:'fabricate-cancel',jobId:job.id,requestId:'science-cancel-001'});saved=await api.campaign(code);assert.equal(saved.starships[0].ship.fabricationState.systems.printer.queue.length,0);
});
