const test=require('node:test'),assert=require('node:assert/strict');
const locks=require('../ship-locks'),maps=require('../ship-map-core'),power=require('../ship-power'),sensors=require('../ship-sensors'),weapons=require('../ship-weapons');
function fixture(){
  const make=id=>({id,title:id,currentHullHp:40,maximumHullHp:40,currentShieldHp:0,ship:{gridCells:[42,43,44,45,62,63,64,65],sicInventory:[{id:'cp',type:'cockpit-1'},{id:'sn',type:'sensors-3'},{id:'en',type:'en-au-engine-1'},{id:'au',type:'au-engine-1'},{id:'au2',type:'au-engine-1'},{id:'lock',type:'lock-on-1'},{id:'gun',type:'rapid-laser-1'},{id:'thr',type:'exhaust-thruster-1'}],placements:[{sicId:'cp',cell:42},{sicId:'sn',cell:43},{sicId:'en',cell:64},{sicId:'au',cell:62},{sicId:'au2',cell:63},{sicId:'lock',cell:44},{sicId:'gun',cell:22},{sicId:'thr',cell:25}]}});
  const a=make('a'),b=make('b'),c=make('c'),unit={id:'u',team:'pc',weaponSystemsSkill:2.5,sensorSkill:5,pilotSkill:3,atb:100,location:{starshipId:'a',sicId:'cp',square:42,mesh:0,stationed:true}};
  const room={starships:[a,b,c],units:[unit],activeId:'u',threshold:100,showcase:true,shipPositions:[{id:'a',q:0,r:0},{id:'b',q:1,r:0},{id:'c',q:2,r:0}],log:[]};
  room.starships.forEach(s=>s.sensorScenarioMasking=10);power.refresh(room,{reset:true});sensors.refresh(room);return {room,a,b,c,unit};
}
let receipt=0;const queue=(room,u,targetId='b',kind='lock',extra={})=>locks.queue(room,u,{targetId,kind,requestId:'lock-test-'+(++receipt),...extra});
function resolve(room,u,score){const roll=()=>{throw Error('No automatic dice');};roll.submittedScore=score;return locks.resolve(room,u,roll);}
test('Lock-On 1 uses source dimensions, cost, threshold and no physical station',()=>{const d=maps.definition('lock-on-1');assert.equal(d.price,560);assert.equal(d.threshold,3);assert.equal(d.energyCost,1);assert.deepEqual(d.stations,[]);});
test('failed locks add shared retry, equality succeeds and survives serialization',()=>{const {room,a,unit}=fixture();assert.ok(queue(room,unit).ok);assert.deepEqual(unit.delayedAction.rollSpec.sides,[4,4]);resolve(room,unit,9);assert.equal(a.lockState.failures.b,1);queue(room,unit);assert.equal(unit.delayedAction.rollSpec.bonus,3.5);assert.ok(resolve(room,unit,10).success);const saved=JSON.parse(JSON.stringify(room));assert.ok(locks.locked(saved,saved.starships[0],'b'));});
test('second target pays 4 AU per 12 combat seconds and drops only extra target when empty',()=>{const {room,a,unit}=fixture();queue(room,unit);resolve(room,unit,10);const before=a.auState.current;assert.ok(queue(room,unit,'c').ok);assert.equal(a.auState.current,before-4);resolve(room,unit,10);a.auState.current=0;locks.refresh(room,11);assert.equal(a.lockState.targets.length,2);locks.refresh(room,1);assert.deepEqual(a.lockState.targets.map(t=>t.targetId),['b']);});
test('power loss, new impairment and sensor range break locks and reset retry',()=>{for(const kind of ['power','impairment','range']){const {room,a,unit}=fixture();queue(room,unit);resolve(room,unit,10);const item=a.ship.sicInventory.find(i=>i.id==='lock');if(kind==='power')item.status='powered-down';if(kind==='impairment')item.impairmentPoints=1;if(kind==='range')room.shipPositions[1].q=100;locks.refresh(room);assert.equal(a.lockState.targets.length,0,kind);if(kind==='impairment'){queue(room,unit);assert.deepEqual(unit.delayedAction.rollSpec.sides,[2,2]);}}});
test('SIC lock requires analyzed installed component, ship lock and shields down',()=>{const {room,a,b,unit}=fixture();assert.equal(queue(room,unit,'b','sic',{targetSicId:'lock'}).ok,false);queue(room,unit);resolve(room,unit,10);a.sensorState.reports.unshift({analysis:true,targetId:'b',layout:JSON.parse(JSON.stringify(b.ship))});assert.ok(queue(room,unit,'b','sic',{targetSicId:'lock'}).ok);resolve(room,unit,10);assert.equal(a.lockState.targets[0].sicId,'lock');b.currentShieldHp=1;locks.refresh(room);assert.equal(a.lockState.targets[0].sicId,null);assert.equal(queue(room,unit,'b','sic',{targetSicId:'lock'}).ok,false);});
test('locked laser skips accuracy but still requests 4D4; SIC damage gives threshold impairments',()=>{const {room,a,b,unit}=fixture();queue(room,unit);resolve(room,unit,10);a.lockState.targets[0].sicId='lock';assert.ok(weapons.queue(room,unit,{sicId:'gun',targetId:'b',requestId:'locked-laser'}).ok);assert.equal(unit.delayedAction.rollConfirmed,true);weapons.resolveInput(room,unit,()=>{throw Error('Accuracy auto-roll');});assert.equal(unit.delayedAction.weaponDamage.count,4);assert.equal(b.currentHullHp,40);weapons.resolveDamage(room,unit,[3,3,3,3]);assert.equal(b.currentHullHp,28);assert.equal(b.ship.sicInventory.find(i=>i.id==='lock').status,'destroyed');assert.equal(room.units.length,1);});
test('Break Lock-On respects zero Masking and normal 13 difficulty',()=>{const {room,a,b,unit}=fixture();locks.state(b).targets.push({targetId:'a',remaining:12});a.sensorScenarioMasking=0;assert.match(queue(room,unit,'b','break').error,/zero/);a.sensorScenarioMasking=10;assert.ok(queue(room,unit,'b','break').ok);assert.equal(unit.delayedAction.rollSpec.difficulty,13);resolve(room,unit,13);assert.equal(b.lockState.targets.length,0);});
test('release is free, idempotent and never interrupts pending input',()=>{const {room,a,unit}=fixture();queue(room,unit);resolve(room,unit,10);room.activeId=null;assert.equal(queue(room,unit,'b','release').free,true);assert.equal(a.lockState.targets.length,0);unit.delayedAction={id:'other'};assert.equal(queue(room,unit,'b','release').ok,false);});

test('overlapping acquisition cannot skip second-target AU payment',()=>{
  const {room,a,unit}=fixture();queue(room,unit);const pending=unit.delayedAction;unit.delayedAction=null;
  queue(room,unit,'c');resolve(room,unit,10);const before=a.auState.current;unit.delayedAction=pending;
  resolve(room,unit,10);assert.equal(a.lockState.targets.length,2);assert.equal(a.auState.current,before-4);
});

test('breaking an incoming lock does not require owning a Lock-On SIC',()=>{
  const {room,a,b,unit}=fixture();a.ship.sicInventory=a.ship.sicInventory.filter(i=>i.id!=='lock');
  locks.state(b).targets.push({targetId:'a',remaining:12});assert.ok(queue(room,unit,'b','break').ok);resolve(room,unit,13);assert.equal(b.lockState.targets.length,0);
});
