const test=require('node:test'),assert=require('node:assert/strict');
const weapons=require('../ship-weapons'),maps=require('../ship-map-core'),power=require('../ship-power'),shields=require('../ship-shields'),sensors=require('../ship-sensors');
function fixture(){
  const make=id=>({id,title:id,currentHullHp:40,maximumHullHp:40,ship:{gridCells:[42,43,44,62,63,64],defenseScore:10,sicInventory:[{id:'cp',type:'cockpit-1'},{id:'sn',type:'sensors-3'},{id:'en',type:'en-au-engine-1'},{id:'au',type:'au-engine-1'},{id:'gun',type:'rapid-laser-1'}],placements:[{sicId:'cp',cell:42},{sicId:'sn',cell:43},{sicId:'en',cell:64},{sicId:'au',cell:62},{sicId:'gun',cell:22}]}});
  const a=make('a'),b=make('b'),unit={id:'u',team:'pc',weaponSystemsSkill:6,dexterityDice:[8,6],atb:100,location:{starshipId:'a',sicId:'cp',square:42,mesh:0,stationed:true}};
  const room={starships:[a,b],units:[unit],activeId:'u',threshold:100,shipPositions:[{id:'a',q:0,r:0},{id:'b',q:1,r:0}],log:[]};
  power.refresh(room);a.auState.current=5;a.auState.maximum=5;
  // One additional action engine supplies the firing pool without bypassing power.refresh.
  a.ship.sicInventory.push({id:'au2',type:'au-engine-1'});a.ship.placements.push({sicId:'au2',cell:63});power.refresh(room,{reset:true});
  room.showcase=true;a.sensorScenarioMasking=10;b.sensorScenarioMasking=10;
  sensors.refresh(room);return {room,a,b,unit};
}
const order={sicId:'gun',targetId:'b',requestId:'laser-test-order'};
function resolve(room,unit,total,die=4){const roll=()=>4;roll.submittedScore=total;weapons.resolveInput(room,unit,roll);if(unit.delayedAction?.weaponDamage)weapons.resolveDamage(room,unit,Array(unit.delayedAction.weaponDamage.count).fill(die));}

test('a hit waits for explicit damage confirmation and never invokes an automatic damage roll',()=>{const {room,b,unit}=fixture();weapons.queue(room,unit,order);const roll=()=>{throw Error('Unexpected automatic roll');};roll.submittedScore=30;weapons.resolveInput(room,unit,roll,roll);assert.equal(b.currentHullHp,40);assert.equal(unit.delayedAction.awaitingRoll,true);assert.equal(unit.delayedAction.rollSpec.damage,true);const restored=JSON.parse(JSON.stringify(room));const actor=restored.units[0];weapons.resolveDamage(restored,actor,[1,2,3,4]);assert.equal(restored.starships[1].currentHullHp,30);assert.equal(actor.delayedAction,null);});
test('Rapid Laser card metadata and no physical station',()=>{const d=maps.definition('rapid-laser-1');assert.equal(d.price,450);assert.equal(d.energyCost,1);assert.equal(d.exterior,true);assert.equal(d.threshold,4);assert.deepEqual(d.stations,[]);});
test('evasion applies to every hit and miss until 20 combat seconds expire',()=>{const {room,a,b,unit}=fixture();require('../ship-cooperation').state(b).evasions=[{defense:25,remaining:20}];for(const [i,score] of [20,30].entries()){a.auState.current=a.auState.maximum;assert.equal(weapons.queue(room,unit,{...order,requestId:'evasion-shot-'+i}).ok,true);resolve(room,unit,score);assert.equal(b.commandSystems.evasions.length,1);assert.equal(sensors.defense(room,b),25);}require('../ship-commands').advance(room,20);assert.equal(sensors.defense(room,b),10);});
test('laser modifiers suppress floating point noise and use currently revealed defense',()=>{const {room,unit}=fixture();room.shipPositions[1].q=1.9999999999999998;unit.weaponSystemsSkill=2.5;sensors.refresh(room);const spec=weapons.rollSpec(room,unit,{shipId:'a',targetId:'b'});assert.equal(spec.bonus,Number(spec.bonus.toFixed(6)));assert.equal(spec.difficulty,10);});
test('repeat activation surcharge expires in combat seconds and survives serialization',()=>{const {room,a,unit}=fixture();weapons.queue(room,unit,order);resolve(room,unit,11);a.auState.current=a.auState.maximum;const before=a.auState.current;assert.equal(weapons.queue(room,unit,{...order,requestId:'repeat-laser'}).ok,true);assert.equal(a.auState.current,before-6);const saved=JSON.parse(JSON.stringify(room));weapons.advance(saved,12);assert.equal(saved.starships[0].weaponState.repeatWindow.gun,0);});
test('Fast input quality one and Weapon Systems ingenuity mapping',()=>{for(const [skill,bars] of [[0,0],[1,1],[2,1],[3,2],[4,2],[5,3],[6,4],[9,4]]){const s=weapons.settings({weaponSystemsSkill:skill});assert.equal(s.base,10);assert.equal(s.factors.Quality,1);assert.equal(s.factors.Ingenuity,bars);}});
test('laser queue spends once, freezes resolution until submitted, preserves hull before completion',()=>{const {room,a,b,unit}=fixture(),before=a.auState.current;assert.equal(weapons.queue(room,unit,order).ok,true);assert.equal(a.auState.current,before-5);assert.equal(b.currentHullHp,40);assert.equal(unit.delayedAction.remaining,100);assert.equal(weapons.queue(room,unit,order).duplicate,true);assert.equal(a.auState.current,before-5);resolve(room,unit,16);assert.equal(b.currentHullHp,24);assert.equal(a.weaponState.reports[0].dice.length,4);});
test('equal defense misses and no damage die is rolled',()=>{const {room,b,unit}=fixture();weapons.queue(room,unit,order);resolve(room,unit,10);assert.equal(b.currentHullHp,40);assert.equal(b.weaponState.reports[0].hit,false);});
test('impaired lasers cap at 1D4 and sacrificed dice reduce damage rather than improve it',()=>{const {room,a,b,unit}=fixture();a.ship.sicInventory.find(i=>i.id==='gun').impaired=true;weapons.queue(room,unit,order);resolve(room,unit,50);assert.equal(b.currentHullHp,36);room.activeId=unit.id;a.auState.current=a.auState.maximum;weapons.queue(room,unit,{...order,requestId:'laser-second',sacrifice:1});resolve(room,unit,50);assert.equal(b.currentHullHp,36);});
test('cannot fire without a bridge seat, a detected contact, AU, or outside own turn',()=>{const {room,a,unit}=fixture();unit.location.stationed=false;assert.equal(weapons.queue(room,unit,order).ok,false);unit.location.stationed=true;room.activeId='other';assert.equal(weapons.queue(room,unit,order).ok,false);room.activeId='u';a.auState.current=0;assert.match(weapons.queue(room,unit,order).error,/Auxiliary/);assert.equal(unit.delayedAction,undefined);});
test('forced departure cancels input without damage; incoming reports do not reveal unknown attacker',()=>{const {room,a,b,unit}=fixture();weapons.queue(room,unit,order);unit.location.stationed=false;resolve(room,unit,30);assert.equal(b.currentHullHp,40);assert.match(a.weaponState.reports[0].text,/interrupted/);unit.location.stationed=true;a.auState.current=a.auState.maximum;weapons.queue(room,unit,{...order,requestId:'laser-resume'});resolve(room,unit,30);assert.equal(b.weaponState.reports[0].shipId,undefined);assert.equal(b.weaponState.reports[0].total,undefined);});
test('damage respects shields and discards overflow',()=>{const {room,b,unit}=fixture();b.ship.sicInventory.push({id:'shield',type:'shield-1'});b.ship.placements.push({sicId:'shield',cell:44});shields.refresh(room);shields.entries(b)[0].state.hp=1;weapons.queue(room,unit,order);resolve(room,unit,30);assert.equal(b.currentHullHp,40);assert.equal(b.currentShieldHp,0);});
