const test=require('node:test'),assert=require('node:assert/strict'),maps=require('../ship-map-core'),power=require('../ship-power'),transport=require('../ship-transporter'),doors=require('../ship-doors'),intruders=require('../ship-intruders');
const fixture=require('./helpers/transporter-fixture.cjs');

test('Transporter has printed price, footprint, EN, threshold and station',()=>{const d=maps.definition('transporter');assert.equal(d.price,20000);assert.equal(d.energyCost,15);assert.equal(d.width*d.height,9);assert.equal(d.threshold,18);assert.equal(d.stations.length,4);});
test('transport waits, consumes no AU, assigns reusable transponder and relocates without crew reassignment',()=>{const f=fixture(),r=transport.command(f.room,f.unit,f.body);assert.equal(r.ok,true,r.error);assert.equal(f.unit.location.starshipId,f.ship.id);assert.equal(f.unit.delayedAction.remaining/f.unit.delayedAction.rate,12);assert.match(transport.resolve(f.room,f.unit),/completed/);assert.equal(f.unit.location.starshipId,'enemy');assert.equal(f.enemy.crewCharacterIds,undefined);assert.deepEqual(f.ship.ship.transporterState.systems.vr.holders,['pc']);});
test('shields, range, lock, analysis and capacity are authoritative',()=>{for(const change of [f=>f.ship.currentShieldHp=1,f=>f.enemy.currentShieldHp=1,f=>f.room.shipPositions[1].q=9,f=>f.ship.lockState.targets=[],f=>f.ship.sensorState.analyses={},f=>f.body.passengerIds=Array(6).fill(f.unit.id)]){const f=fixture();change(f);assert.equal(transport.command(f.room,f.unit,f.body).ok,false);}});
test('arrival revalidation cancels atomically if destination shields rise',()=>{const f=fixture();assert.equal(transport.command(f.room,f.unit,f.body).ok,true);f.enemy.currentShieldHp=1;assert.match(transport.resolve(f.room,f.unit),/cancelled/);assert.equal(f.unit.location.starshipId,f.ship.id);assert.deepEqual(f.ship.ship.transporterState.systems.vr.holders,[]);});
test('impaired transporter uses submitted individual D10s, and no unrolled death',()=>{const f=fixture();f.ship.ship.sicInventory.find(i=>i.id==='vr').impairmentPoints=2;assert.equal(transport.command(f.room,f.unit,f.body).ok,true);assert.deepEqual(transport.rollSpec(f.room,f.unit,f.unit.delayedAction.transporterOrder).sides,[10]);f.unit.delayedAction.rollConfirmed=true;f.unit.delayedAction.submittedRoll={values:[2]};transport.resolve(f.room,f.unit);assert.equal(f.unit.currentHp,0);assert.equal(f.unit.location.starshipId,f.ship.id);});
test('planet surface transport carries its planet identity and does not need a ship lock',()=>{const f=fixture();f.room.spaceObjects=[{id:'planet',kind:'planet',name:'Home',q:1,r:0}];f.body.targetId='planet';assert.equal(transport.command(f.room,f.unit,f.body).ok,true);transport.resolve(f.room,f.unit);assert.equal(f.unit.location.planetId,'planet');assert.equal(f.unit.location.starshipId,'');});
test('hidden intruder is omitted until same room, then alert persists without tracking after leaving sight',()=>{const f=fixture(),npc={id:'guard',team:'npc',characterName:'Guard',currentHp:10,location:{starshipId:f.ship.id,square:147,mesh:4}};f.room.units.push(npc);intruders.reconcile(f.room);assert.equal(intruders.visible(f.room,f.ship,npc),false);let v=intruders.project(f.room,f.room,{characterId:'pc'});assert.equal(v.units.some(u=>u.id==='guard'),false);assert.equal(v.intruderShips.length,0);npc.location.square=f.unit.location.square;intruders.reconcile(f.room);assert.equal(intruders.visible(f.room,f.ship,npc),true);npc.location.square=147;intruders.reconcile(f.room);v=intruders.project(f.room,f.room,{characterId:'pc'});assert.equal(v.units.some(u=>u.id==='guard'),false);assert.equal(v.intruderShips.length,1);});
test('working camera sees all occupants and disabled camera stops location tracking',()=>{const f=fixture(),npc={id:'guard',team:'npc',currentHp:10,location:{starshipId:f.ship.id,square:147,mesh:4}},cam={id:'camera',type:'surv-camera'};f.room.units.push(npc);f.ship.ship.sicInventory.push(cam);f.ship.ship.placements.push({sicId:'camera',cell:36});assert.equal(intruders.visible(f.room,f.ship,npc),true);cam.disabled=true;assert.equal(intruders.visible(f.room,f.ship,npc),false);});
test('door threshold counts qualifying hits, opens on third, diagnostics repairs all doors',()=>{const f=fixture(),key=doors.list(f.ship)[0],target={shipId:f.ship.id,key};assert.equal(doors.hit(f.room,target,9),0);assert.equal(doors.hit(f.room,target,20),1);assert.equal(doors.hit(f.room,target,10),2);assert.equal(doors.hit(f.room,target,100),3);assert.equal(f.ship.ship.doorStates[key],'open');const maintenance=require('../ship-maintenance');maintenance.diagnostics(f.ship,'pc');maintenance.passTime(f.ship,55);assert.equal(doors.broken(f.ship,key),false);});
test('Transporter command receipts reject changed replay and accept exact retry',()=>{const f=fixture();assert.equal(transport.command(f.room,f.unit,f.body).ok,true);assert.equal(transport.command(f.room,f.unit,f.body).duplicate,true);assert.equal(transport.command(f.room,f.unit,{...f.body,square:43}).ok,false);});
module.exports={fixture};

test('boarding PC retains their own marker on an enemy ship',()=>{const f=fixture();transport.command(f.room,f.unit,f.body);transport.resolve(f.room,f.unit);const view=intruders.project(f.room,f.room,{characterId:'pc'});assert.ok(view.units.some(u=>u.id===f.unit.id));});
test('destroyed planets cannot receive passengers',()=>{const f=fixture();f.room.spaceObjects=[{id:'planet',kind:'planet',q:1,r:0,destroyedAt:123}];f.body.targetId='planet';assert.equal(transport.command(f.room,f.unit,f.body).ok,false);});

test('spectators and PCs on other ships cannot track a hidden intruder',()=>{const f=fixture();f.room.units.push({id:'guard',team:'npc',currentHp:10,characterName:'Guard',location:{starshipId:f.ship.id,square:147,mesh:4}});for(const viewer of [{spectator:true},{characterId:'other-pc'}])assert.equal(intruders.project(f.room,f.room,viewer).units.some(u=>u.id==='guard'),false);});


test('four stationed crew travel together, including crew holding at the Transporter',()=>{const f=fixture(),layout=maps.buildLayout(f.ship.ship),seats=[...layout.footprint.values()].flatMap(c=>c.sicId==='vr'?c.stations.filter(s=>s.x===c.column&&s.y===c.row).map(s=>({square:c.index,mesh:s.mesh})):[]);assert.equal(seats.length,4);const first=f.unit.location;for(let n=1;n<4;n++){const seat=seats[n],square=Number.isInteger(seat.square)?seat.square:[...layout.footprint].find(([index,c])=>c.sicId==='vr'&&c.stations.some(s=>s.x===c.column&&s.y===c.row&&s.mesh===seat.mesh))?.[0];f.room.units.push({...structuredClone(f.unit),id:'crew-'+n,characterId:'crew-'+n,consoleHold:true,location:{...first,square,mesh:seat.mesh}});}f.body.passengerIds=f.room.units.filter(u=>u.location?.sicId==='vr').map(u=>u.id);assert.equal(f.body.passengerIds.length,4);const r=transport.command(f.room,f.unit,f.body);assert.equal(r.ok,true,r.error);assert.match(transport.resolve(f.room,f.unit),/4 arrived/);for(const id of f.body.passengerIds){const u=f.room.units.find(u=>u.id===id);assert.equal(u.location.starshipId,'enemy');assert.equal(u.consoleHold,false);}});

test('Transporter reaches eight units and rejects anything beyond eight',()=>{const f=fixture();f.room.shipPositions[1].q=8;assert.equal(transport.command(f.room,f.unit,f.body).ok,true);const far=fixture();far.room.shipPositions[1].q=8.01;assert.equal(transport.command(far.room,far.unit,far.body).ok,false);});
