const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process'),{once}=require('node:events');
test('Transporter privacy and door damage use authenticated HTTP actions',{timeout:35000},async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sa-transport-http-')),child=spawn(process.execPath,['server.js'],{cwd:path.resolve(__dirname,'..'),windowsHide:true,env:{...process.env,PORT:'0',DATABASE_URL:'',SA_LOCAL_DATA_DIR:dir},stdio:['ignore','pipe','pipe']});
 t.after(async()=>{if(child.exitCode===null){const done=once(child,'exit');child.kill();await done;}});
 const base=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('startup timeout')),10000);child.stdout.on('data',c=>{const url=String(c).match(/Local:\s+(http:\/\/127\.0\.0\.1:\d+)/)?.[1];if(url){clearTimeout(timer);resolve(url);}});});
 const post=async(p,b,status=200)=>{const r=await fetch(base+'/api/'+p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}),d=await r.json();assert.equal(r.status,status,JSON.stringify(d));return d;};
 const demo=await post('campaign/showcase/start',{}),backup=await fetch(`${base}/api/campaign/backup?code=${demo.code}&token=${demo.gmToken}`).then(r=>r.json()),e=backup.campaign.encounter,f=require('./helpers/transporter-fixture.cjs')(),nova=e.units.find(u=>u.team==='pc'),npc=e.units.find(u=>u.team==='npc'),source=e.starships.find(s=>s.id===nova.location.starshipId),target=e.starships.find(s=>s.id!==source.id);
 Object.assign(source,{ship:f.ship.ship,currentShieldHp:0,currentHullHp:200,lockState:{targets:[{targetId:target.id,systemId:'lock'}],reports:[],receipts:[],failures:{}}});Object.assign(target,{ship:f.enemy.ship,currentShieldHp:0,currentHullHp:100});source.sensorState={contacts:{[target.id]:{id:target.id,level:'detected'}},analyses:{[target.id]:{layout:structuredClone(target.ship)}},reports:[],failures:{}};
 nova.location={...f.unit.location,starshipId:source.id,stationed:false,mesh:4};npc.location={starshipId:source.id,square:147,mesh:4};nova.atb=100;Object.assign(e,{hasEngagedClock:true,encounterEndedAt:null,activeId:nova.id,pausedForTurn:true,running:false,hardPaused:true,commandRemaining:120,commandTotal:120,shipPositions:[{id:source.id,q:0,r:0},{id:target.id,q:2,r:0}]});
 const restore=()=>post('campaign/restore',{code:demo.code,token:demo.gmToken,backup});await restore();
 const state=token=>fetch(`${base}/api/state?room=${demo.code}&token=${token}`).then(r=>r.json()),pc=demo.players[0],act=body=>post('action',{roomCode:demo.code,characterId:pc.id,characterToken:pc.token,id:nova.id,...body});
 let s=await state(pc.token);assert.ok(s.units.some(u=>u.id===nova.id));assert.equal(s.units.some(u=>u.id===npc.id),false);assert.equal(s.intruderShips.length,0);assert.ok((await state(demo.gmToken)).units.some(u=>u.id===npc.id));
 npc.location.square=nova.location.square;await restore();s=await state(pc.token);assert.ok(s.units.some(u=>u.id===npc.id));assert.equal(s.intruderShips.length,1);
 const door=require('../ship-doors').targets(e,nova).find(d=>d.distance<=8);assert.ok(door);
 for(const damage of [9,10,14,100]){nova.atb=100;nova.delayedAction=null;nova.delayTimer=null;e.activeId=nova.id;await restore();s=await act({action:'playerCombatAction',kind:'fire',targetId:door.id,distance:1});assert.equal(s.attackResolution.phase,'damage');assert.equal(s.attackResolution.defenderId,door.id);s=await act({action:'submitAttackDamage',attackId:s.attackResolution.id,rolledDamage:damage,mode:'manual'});const live=(await state(demo.gmToken)).starships.find(x=>x.id===source.id);source.ship.doorDamage=live.ship.doorDamage;source.ship.doorStates=live.ship.doorStates;}
 assert.equal(source.ship.doorDamage[door.doorTarget.key],3);assert.equal(source.ship.doorStates[door.doorTarget.key],'open');await restore();s=await state(demo.gmToken);assert.equal(s.starships.find(x=>x.id===source.id).ship.doorDamage[door.doorTarget.key],3);
});
