// Isolated fresh-campaign browser checks. Never touches the normal campaign store.
const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {spawn}=require('node:child_process'),{once}=require('node:events');
const root=path.resolve(__dirname,'..'),artifacts=path.join(root,'test-artifacts','shields');
fs.mkdirSync(artifacts,{recursive:true});
const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'sa-shield-browser-'));
let child,browser;
async function startServer(){
  child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,PORT:'0',DATABASE_URL:'',SA_LOCAL_DATA_DIR:dataDir},stdio:['ignore','pipe','pipe'],windowsHide:true});
  return await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Server startup timed out')),10000);child.on('error',reject);child.stdout.on('data',c=>{const url=String(c).match(/Local:\s+(http:\/\/127\.0\.0\.1:\d+)/)?.[1];if(url){clearTimeout(timeout);resolve(url);}});child.stderr.on('data',c=>process.stderr.write(c));});
}
async function main(){
  let base=await startServer();
  const post=async(route,body,status=200)=>{const response=await fetch(base+'/api/'+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();assert.equal(response.status,status,JSON.stringify(result));return result;};
  const created=await post('campaign/create',{name:'Shield Crew Test',gmCode:'shield-test-gm'},201),code=created.campaign.code,token=created.token;
  const people=['Pilot','Engineer'].map(name=>({id:'shield-'+name.toLowerCase(),phase:'finalized',access:{pcCode:'shield-'+name.toLowerCase()},identity:{characterName:name,playerName:name},attributes:{health:[1,0,-1,-1],intellect:[1,0,-1,-1],perception:[1,0,-1,-1],dexterity:[1,0,-1,-1]},computed:{maximumHp:30,moveSpeed:2,speed:1,commandWindow:120,skills:{Engineering:0}},health:{current:30}}));
  const playerTokens=[];
  for(const character of people){const p=await post('campaign/join/request',{code,character},201);await post('campaign/join/respond',{code,token,requestId:p.requestId,decision:'approve'});playerTokens.push((await post('campaign/join/status',{code,characterId:character.id,pcCode:character.access.pcCode})).token);}
  const ship={id:'shield-ship',title:'Bastion',crewCharacterIds:people.map(p=>p.id),ship:{id:'shield-ship',title:'Bastion',confirmedOnce:true,gridCells:Array.from({length:120},(_,i)=>81+Math.floor(i/12)*20+i%12),sicInventory:[{id:'cp',type:'cockpit-2',stationLayout:'corners-v1'},{id:'sh',type:'shield-1',stationLayout:'corners-v1'},{id:'en',type:'en-engine-3'},{id:'au',type:'au-engine-4'},{id:'th',type:'ionic-pulse-thruster-1'}],placements:[{sicId:'cp',cell:82},{sicId:'sh',cell:81},{sicId:'en',cell:122},{sicId:'au',cell:128},{sicId:'th',cell:80}]}};
  await post('campaign/starship/link',{code,token,starship:ship.ship},201);await post('campaign/starship/crew',{code,token,starshipId:ship.id,crewCharacterIds:ship.crewCharacterIds});
  const act=(body,status=200)=>post('action',{roomCode:code,gmToken:token,...body},status),state=()=>fetch(base+'/api/state?room='+code).then(r=>r.json());
  await act({action:'prepareEncounter',preparationId:'shield-browser-prep',mode:'starship',starships:[ship],units:[{characterId:people[0].id,characterName:'Pilot',team:'pc',speed:.1,commandWindow:120,location:{starshipId:ship.id,square:82,mesh:0,stationed:true}},{characterId:people[1].id,characterName:'Engineer',team:'pc',speed:.1,commandWindow:120,location:{starshipId:ship.id,square:81,mesh:0,stationed:true}},{preparationUnitId:'shield-npc',characterName:'Relief Pilot',team:'npc',speed:.1,commandWindow:120,location:{starshipId:ship.id,square:82,mesh:2,stationed:true}}]});
  const units=(await state()).units,pilot=units.find(u=>u.characterId===people[0].id),engineer=units.find(u=>u.characterId===people[1].id),npc=units.find(u=>u.team==='npc');
  browser=await chromium.launch({channel:process.env.SA_BROWSER_CHANNEL||'msedge',headless:true});
  const errors=[],requests=[];
  async function page(){const context=await browser.newContext({viewport:{width:1600,height:1000}});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().endsWith('/api/action')&&r.postDataJSON()?.action==='shieldCommand')requests.push(r.postDataJSON());});return p;}
  const gm=await page();await gm.goto(base+'/gm.html?campaign='+code);await gm.getByRole('textbox',{name:'Campaign Name',exact:true}).fill('Shield Crew Test');await gm.getByRole('textbox',{name:'GM Code',exact:true}).fill('shield-test-gm');await gm.getByRole('button',{name:'Open Campaign',exact:true}).click();await gm.getByRole('button',{name:'Combat',exact:true}).click();await gm.getByRole('button',{name:'Resume Encounter',exact:true}).click();
  const gmFrame=gm.frameLocator('#atbFrame');await gmFrame.getByRole('button',{name:'Engage Clock',exact:true}).click();await act({action:'setHardPaused',paused:true});
  const pcs=[];
  for(const character of people){const p=await page();await p.goto(`${base}/character.html?campaign=${code}&character=${character.id}`);await p.getByRole('button',{name:'Enter PC Code',exact:true}).click();await p.getByRole('textbox',{name:'Enter PC Code',exact:true}).fill(character.access.pcCode);await p.getByRole('button',{name:'Unlock Character',exact:true}).click();await p.getByRole('button',{name:'Combat',exact:true}).click();pcs.push(p);}
  const [pc,eng]=pcs;
  await pc.frameLocator('#playerAtbFrame').locator('[data-console-operator]').first().selectOption(pilot.id);
  await eng.frameLocator('#playerAtbFrame').locator('[data-console-operator]').first().selectOption(engineer.id);
  await pc.getByRole('dialog',{name:'Pilot console',exact:true}).waitFor();
  await eng.getByRole('dialog',{name:'Shield console',exact:true}).waitFor();
  assert.equal(await gm.locator('.ship-navigation-dialog,.shield-console-dialog').count(),0,'PC consoles do not appear for the GM');
  await gmFrame.getByRole('combobox',{name:'Bastion consoles',exact:true}).selectOption(npc.id);
  await gm.getByRole('dialog',{name:'Pilot console',exact:true}).waitFor();
  await gm.getByRole('button',{name:'Combat View',exact:true}).click();
  await pc.getByRole('button',{name:'Combat View',exact:true}).click();
  await pc.frameLocator('#playerAtbFrame').getByRole('combobox',{name:'Bastion consoles',exact:true}).selectOption(pilot.id);
  await pc.getByRole('dialog',{name:'Pilot console',exact:true}).waitFor();
  await pc.getByRole('combobox',{name:'Station console',exact:true}).selectOption('sh');
  const remote=pc.getByRole('dialog',{name:'Shield console',exact:true}),local=eng.getByRole('dialog',{name:'Shield console',exact:true});
  assert.match(await remote.locator('.console-defense').innerText(),/DEFENSE -?\d/);
  await remote.waitFor();assert.match(await remote.locator('[data-connection]').innerText(),/REMOTE ACCESS/);assert.match(await local.locator('[data-connection]').innerText(),/LOCAL STATION/);
  assert.equal(await local.getByRole('button',{name:'Restabilize Shield',exact:true}).isEnabled(),false);
  assert.equal(await local.getByRole('button',{name:'Reinforce Field',exact:true}).isEnabled(),true);
  await pc.setViewportSize({width:1366,height:768});await pc.screenshot({path:path.join(artifacts,'remote-console-1366.png')});
  assert.ok((await remote.getByRole('button',{name:'Restore Shield HP',exact:true}).boundingBox()).x>=0);
  await pc.setViewportSize({width:1600,height:1000});
  assert.equal(await remote.getByRole('button',{name:'Restabilize Shield',exact:true}).isVisible(),false);
  assert.equal(await remote.locator('[data-condition]').innerText(),'','Player shield condition must not expose exact HP');
  await act({action:'damageStarship',starshipId:ship.id,amount:6});
  const before=(await state()).starships[0].auState.current;
  const button=remote.getByRole('button',{name:'Restore Shield HP',exact:true}),box=await button.boundingBox();
  await pc.mouse.move(box.x+box.width/2,box.y+box.height/2,{steps:20});await pc.mouse.down();await pc.waitForTimeout(350);await pc.mouse.up();await pc.mouse.click(box.x+box.width/2,box.y+box.height/2);
  await remote.locator('[data-input-status]').filter({hasText:'Entering restoration'}).waitFor();
  assert.equal(requests.length,1,'Held/double mouse click sends one request');
  assert.equal((await state()).starships[0].auState.reserved,5);
  await local.getByRole('button',{name:'Reinforce Field',exact:true}).click();
  await local.locator('[data-input-status]').filter({hasText:'Entering reinforcement'}).waitFor();
  assert.equal((await state()).starships[0].auState.reserved,8);
  await pc.waitForTimeout(600);
  const pausedSave=JSON.parse(fs.readFileSync(path.join(dataDir,'campaigns.json'),'utf8')).find(c=>c.code===code).encounter;
  assert.equal(pausedSave.starships[0].auCommands.length,2,'Paused AU reservations must reach durable storage');
  await act({action:'setHardPaused',paused:false});await pc.waitForTimeout(2000);await act({action:'setHardPaused',paused:true});
  let current=(await state()).starships[0];assert.equal(current.auState.current,before-8);assert.ok(current.shieldSystems.sh.hp>6);assert.equal(current.shieldSystems.sh.protection,1);
  await pc.screenshot({path:path.join(artifacts,'remote-shield-console.png')});await eng.screenshot({path:path.join(artifacts,'local-shield-console.png')});
  await remote.getByRole('spinbutton').fill('100');await remote.getByRole('button',{name:'Reinforce Field',exact:true}).click();await remote.locator('[data-error]').filter({hasText:'not enough Auxiliary power'}).waitFor();
  await remote.getByRole('spinbutton').fill('1');await remote.getByRole('button',{name:'Restore Shield HP',exact:true}).click();await remote.locator('[data-input-status]').filter({hasText:'Entering restoration'}).waitFor();
  const auBeforeLeave=(await state()).starships[0].auState.current;
  await act({action:'setCombatLocation',id:pilot.id,location:{starshipId:ship.id,square:83,mesh:4,stationed:false}});
  await remote.waitFor({state:'hidden'});current=(await state()).starships[0];assert.equal(current.auState.reserved,0);assert.equal(current.auState.current,auBeforeLeave);
  await act({action:'setCombatLocation',id:pilot.id,location:{starshipId:ship.id,square:81,mesh:0,stationed:true}},409);
  await act({action:'setCombatLocation',id:pilot.id,location:{starshipId:ship.id,square:82,mesh:0,stationed:true}});await pc.getByRole('dialog',{name:'Shield console',exact:true}).waitFor();
  await act({action:'damageStarship',starshipId:ship.id,amount:100});
  await eng.waitForFunction(()=>document.querySelector('.shield-console-dialog [data-reinforce]')?.disabled||[...document.querySelectorAll('.shield-console-dialog button')].some(b=>b.textContent==='Reinforce Field'&&b.disabled),null,{timeout:5000});
  assert.equal(await local.getByRole('button',{name:'Restabilize Shield',exact:true}).isEnabled(),true);
  await post('action',{roomCode:code,characterId:people[0].id,characterToken:playerTokens[0],id:pilot.id,action:'shieldCommand',sicId:'sh',kind:'restabilize',requestId:'remote-forbidden'},409);
  eng.once('dialog',d=>d.accept());await local.getByRole('button',{name:'Restabilize Shield',exact:true}).click();
  await local.locator('[data-turn]').filter({hasText:'RESTABILIZING'}).waitFor();assert.equal(await local.getByRole('button',{name:'Leave Console',exact:true}).isEnabled(),false);
  await act({action:'nudge',id:engineer.id,amount:100},409);
  for(let i=0;i<8;i++)await act({action:'step'});
  current=(await state()).starships[0];assert.ok(current.shieldSystems.sh.restabilization.progress>0);assert.ok((await state()).units.find(u=>u.id===engineer.id).shieldRestabilizing);
  await eng.screenshot({path:path.join(artifacts,'restabilization.png')});
  await act({action:'setCombatLocation',id:engineer.id,location:{starshipId:ship.id,square:83,mesh:4,stationed:false}});await local.waitFor({state:'hidden'});
  const progress=(await state()).starships[0].shieldSystems.sh.restabilization.progress;await act({action:'step'});assert.equal((await state()).starships[0].shieldSystems.sh.restabilization.progress,progress);
  await act({action:'nudge',id:npc.id,amount:100});await gmFrame.getByRole('button',{name:'Console View',exact:true}).click();await gm.getByRole('combobox',{name:'Station console',exact:true}).selectOption('sh');
  const gmConsole=gm.getByRole('dialog',{name:'Shield console',exact:true});await gmConsole.waitFor();assert.match(await gmConsole.locator('[data-connection]').innerText(),/REMOTE ACCESS/);assert.match(await gmConsole.locator('[data-condition]').innerText(),/0/);await gm.screenshot({path:path.join(artifacts,'gm-remote-shield.png')});
  const builder=await page();await builder.goto(base+'/starship.html');await builder.getByRole('button',{name:'Construction',exact:true}).waitFor();assert.equal(await builder.locator('.desktop-grid-viewport').isVisible(),true);await builder.screenshot({path:path.join(artifacts,'construction-workspace.png')});await builder.getByRole('button',{name:'Ship Details',exact:true}).click();assert.equal(await builder.locator('.blueprint-source').isVisible(),true);await builder.getByRole('button',{name:'SICs',exact:true}).click();await builder.locator('summary[aria-label="Bridge: expand 8 cards"]').click();await builder.getByRole('dialog',{name:'Bridge',exact:true}).waitFor();assert.equal(await builder.locator('.sic-picker-slot').count(),8);await builder.screenshot({path:path.join(artifacts,'bridge-roster.png')});
  await builder.locator('.sic-picker-slot img').evaluateAll(images=>Promise.all(images.map(image=>image.decode())));
  const broken=await builder.locator('.sic-picker-slot img').evaluateAll(images=>images.filter(image=>!image.naturalWidth).length);assert.equal(broken,0);
  await builder.waitForTimeout(1200);await builder.screenshot({path:path.join(artifacts,'bridge-roster.png')});
  assert.deepEqual(await builder.locator('.sic-picker-slot [data-purchase-type]').evaluateAll(nodes=>nodes.map(n=>n.dataset.purchaseType)),Array.from({length:8},(_,i)=>`bridge-${i+1}`));
  await builder.locator('[data-family-back]').click();
  await builder.locator('summary[aria-label="Shield: expand 10 cards"]').click();
  await builder.getByRole('dialog',{name:'Shield',exact:true}).waitFor();
  assert.deepEqual(await builder.locator('.sic-picker-slot [data-purchase-type]').evaluateAll(nodes=>nodes.map(n=>n.dataset.purchaseType)),Array.from({length:10},(_,i)=>`shield-${i+1}`));
  await builder.locator('.sic-picker-slot img').evaluateAll(images=>Promise.all(images.map(image=>image.decode())));
  await builder.waitForTimeout(800);await builder.screenshot({path:path.join(artifacts,'shield-roster.png')});
  const cards=await builder.locator('.sic-picker-slot').evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom};}));
  assert.ok(cards.every(r=>r.x>=0&&r.y>=0&&r.right<=1600&&r.bottom<=1000),'All shield cards fit in the viewport');
  await builder.locator('[data-family-back]').click();
  await builder.getByRole('button',{name:'Construction',exact:true}).click();
  assert.ok((await builder.locator('.desktop-grid-viewport').boundingBox()).width>900,'Construction map uses available desktop width');
  assert.equal(await builder.locator('.construction-command-bar button').isVisible(),true);
  await builder.getByRole('button',{name:'Ship Details',exact:true}).click();
  assert.equal(await builder.locator('.desktop-construction-sidebar').isVisible(),false);
  await builder.screenshot({path:path.join(artifacts,'ship-details.png')});
  const newcomer=await page();await newcomer.goto(base+'/character.html?library=1');
  await newcomer.getByRole('button',{name:'OK',exact:true}).click();
  await newcomer.getByRole('heading',{name:/^create character/i}).waitFor();
  await newcomer.locator('#classCardPickerButton').click();await newcomer.locator('[data-class-card=""]').click();
  await newcomer.getByRole('button',{name:'Choose No Class',exact:true}).click();
  assert.equal((await newcomer.locator('#classCardPickerButton').textContent()).trim(),'No Class');
  assert.doesNotMatch(await newcomer.locator('#nextRequirement').innerText(),/Choose Class/);
  await newcomer.waitForTimeout(700);await newcomer.reload();
  assert.equal((await newcomer.locator('#classCardPickerButton').textContent()).trim(),'No Class');
  assert.ok(await newcomer.locator('.skill-buy[disabled][title]').count()>0);
  if(await newcomer.getByRole('button',{name:'Skills',exact:true}).isVisible())await newcomer.getByRole('button',{name:'Skills',exact:true}).click();
  await newcomer.locator('[data-skill-description]').filter({hasText:'Engineering'}).click();
  const description=newcomer.getByRole('dialog',{name:'Engineering description'});
  await description.waitFor();assert.equal(await description.getByRole('button',{name:'Roll',exact:true}).isEnabled(),false);
  const rect=await description.boundingBox();assert.ok(Math.abs(rect.x+rect.width/2-800)<5&&Math.abs(rect.y+rect.height/2-500)<5);
  await newcomer.screenshot({path:path.join(artifacts,'skill-description-draft.png')});
  await description.getByRole('button',{name:'Close skill description'}).click();
  const skillPlayer=await page();await skillPlayer.goto(`${base}/character.html?campaign=${code}&character=${people[0].id}`);
  await skillPlayer.getByRole('button',{name:'Enter PC Code',exact:true}).click();await skillPlayer.getByRole('textbox',{name:'Enter PC Code',exact:true}).fill(people[0].access.pcCode);await skillPlayer.getByRole('button',{name:'Unlock Character',exact:true}).click();
  if(await skillPlayer.getByRole('button',{name:'Skills',exact:true}).isVisible())await skillPlayer.getByRole('button',{name:'Skills',exact:true}).click();
  for(const attribute of ['intellect','dexterity']){
    await skillPlayer.locator('[data-skill-description]').filter({hasText:'Engineering'}).click();
    const dialog=skillPlayer.getByRole('dialog',{name:'Engineering description'});
    assert.equal(await dialog.getByRole('combobox',{name:'Roll attribute'}).inputValue(),'intellect');
    await dialog.getByRole('combobox',{name:'Roll attribute'}).selectOption(attribute);
    await dialog.getByRole('button',{name:'Roll',exact:true}).click();
    await skillPlayer.locator('#skillSetupStage').waitFor();
    assert.match(await skillPlayer.locator('#skillSetupStage').innerText(),new RegExp(attribute,'i'));
    assert.match(await skillPlayer.locator('#skillSetupStage').innerText(),/D6\s*\+\s*D4/);
    await skillPlayer.locator('#skillCheckClose').click();
  }
  await newcomer.screenshot({path:path.join(artifacts,'character-creation.png')});
  assert.deepEqual(errors,[]);
  await act({action:'completeTurn',id:npc.id});
  await act({action:'nudge',id:engineer.id,amount:100});
  await act({action:'setCombatLocation',id:engineer.id,location:{starshipId:ship.id,square:81,mesh:0,stationed:true}});
  assert.notEqual((await state()).activeId,engineer.id,'Joining shield recovery releases an active command window');
  const saved=await state();await new Promise(resolve=>setTimeout(resolve,500));
  await browser.close();browser=null;
  const stopped=once(child,'exit');child.kill();await stopped;base=await startServer();
  const resumed=await state();
  assert.deepEqual(resumed.starships[0].shieldSystems,saved.starships[0].shieldSystems);
  assert.deepEqual(resumed.starships[0].shieldReceipts,saved.starships[0].shieldReceipts);
  assert.equal(resumed.starships[0].auState.current,saved.starships[0].auState.current);
  assert.ok(resumed.units.find(u=>u.id===engineer.id).shieldRestabilizing);
  assert.equal(resumed.hardPaused,true);
  console.log('Shield browser checks passed: fresh campaign, GM/two PCs, out-of-turn consoles, local/remote control, mouse retries, shared AU, cancellation, physical-only restabilization, station occupancy, bridge artwork and server restart.');console.log(artifacts);
}
main().catch(async error=>{console.error(error);if(browser)for(const [i,context] of browser.contexts().entries())for(const [j,p] of context.pages().entries())await p.screenshot({path:path.join(artifacts,`failure-${i}-${j}.png`)}).catch(()=>{});process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(child&&child.exitCode===null){const closed=once(child,'exit');child.kill();await closed;}});
