// API-created campaign, followed by actual player console and shared dice interaction.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {spawn}=require('node:child_process');
const root=path.resolve(__dirname,'..'),artifacts=path.join(root,'test-artifacts','lasers');fs.mkdirSync(artifacts,{recursive:true});
let child,browser,base=process.env.SA_TEST_BASE;
async function main(){
  if(!base){child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,PORT:'0',DATABASE_URL:'',SA_LOCAL_DATA_DIR:fs.mkdtempSync(path.join(os.tmpdir(),'sa-laser-'))},windowsHide:true,stdio:['ignore','pipe','pipe']});base=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Server startup timeout')),10000);child.stdout.on('data',c=>{const url=String(c).match(/Local:\s+(http:\/\/127\.0\.0\.1:\d+)/)?.[1];if(url){clearTimeout(timer);resolve(url);}});child.stderr.on('data',c=>process.stderr.write(c));child.on('error',reject);});}
  const post=async(route,body,status=200)=>{const r=await fetch(base+'/api/'+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();assert.equal(r.status,status,JSON.stringify(j));return j;};
  const made=await post('campaign/create',{name:'Laser Verification',gmCode:'laser-test-gm'},201),code=made.campaign.code,token=made.token;
  const pcRecord={id:'laser-pc',phase:'finalized',access:{pcCode:'laser-player'},identity:{characterName:'Laser Operator',playerName:'Test'},attributes:{health:[1,0,-1,-1],intellect:[1,0,-1,-1],dexterity:[3,3,-1,-1]},computed:{maximumHp:30,moveSpeed:2,speed:.1,commandWindow:120,skills:{'Weapon Systems':6}},health:{current:30}};
  const join=await post('campaign/join/request',{code,character:pcRecord},201);await post('campaign/join/respond',{code,token,requestId:join.requestId,decision:'approve'});
  const playerToken=(await post('campaign/join/status',{code,characterId:pcRecord.id,pcCode:'laser-player'})).token;
  const ships=[0,1].map(i=>({id:'laser-ship-'+i,title:i?'Target Craft':'Laser Craft',crewCharacterIds:i?[]:[pcRecord.id],ship:{id:'laser-ship-'+i,title:i?'Target Craft':'Laser Craft',confirmedOnce:true,defenseScore:-100,gridCells:Array.from({length:56},(_,n)=>42+Math.floor(n/8)*20+n%8),sicInventory:[{id:'cp',type:'cockpit-1'},{id:'sn',type:'sensors-3'},{id:'en',type:'en-au-engine-4'},{id:'gun',type:'rapid-laser-1'}],placements:[{sicId:'cp',cell:42},{sicId:'sn',cell:43},{sicId:'en',cell:85},{sicId:'gun',cell:22}]}}));
  for(const ship of ships){await post('campaign/starship/link',{code,token,starship:ship.ship},201);await post('campaign/starship/crew',{code,token,starshipId:ship.id,crewCharacterIds:ship.crewCharacterIds});}
  const act=(body,status=200)=>post('action',{roomCode:code,gmToken:token,...body},status),state=()=>fetch(`${base}/api/state?room=${code}&token=${token}`).then(r=>r.json());
  await act({action:'prepareEncounter',preparationId:'laser-browser-prep',mode:'starship',starships:ships,shipPositions:[{id:ships[0].id,q:0,r:0},{id:ships[1].id,q:1,r:0}],units:[{characterId:pcRecord.id,characterName:'Laser Operator',team:'pc',speed:.1,commandWindow:120,weaponSystemsSkill:6,dexterityDice:[10,10],location:{starshipId:ships[0].id,square:42,mesh:0,stationed:true}}]});
  const unit=(await state()).units[0];
  browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1366,height:768}}),errors=[];
  context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
  await context.addInitScript(()=>{window.laserAnimations=[];const animate=Element.prototype.animate;Element.prototype.animate=function(frames,options){if(options?.duration===650||this.hasAttribute('data-laser-effect'))window.laserAnimations.push({frames,options});return animate.call(this,frames,options);};});
  const gm=await context.newPage();await gm.goto(base+'/gm.html?campaign='+code);await gm.getByRole('textbox',{name:'Campaign Name',exact:true}).fill('Laser Verification');await gm.getByRole('textbox',{name:'GM Code',exact:true}).fill('laser-test-gm');await gm.getByRole('button',{name:'Open Campaign',exact:true}).click();await gm.getByRole('button',{name:'Combat',exact:true}).click();await gm.getByRole('button',{name:'Resume Encounter',exact:true}).click();await gm.frameLocator('#atbFrame').getByRole('button',{name:'Engage Clock',exact:true}).click();await act({action:'setHardPaused',paused:true});
  const pc=await context.newPage();await pc.goto(`${base}/character.html?campaign=${code}&character=${pcRecord.id}`);await pc.getByRole('button',{name:'Enter PC Code',exact:true}).click();await pc.getByRole('textbox',{name:'Enter PC Code',exact:true}).fill('laser-player');await pc.getByRole('button',{name:'Unlock Character',exact:true}).click();await pc.getByRole('button',{name:'Combat',exact:true}).click();await pc.getByRole('dialog',{name:'Pilot console',exact:true}).waitFor();await pc.getByRole('combobox',{name:'Station console',exact:true}).selectOption('gun');
  const consoleView=pc.getByRole('dialog',{name:'Weapons console',exact:true});await consoleView.waitFor();await act({action:'nudge',id:unit.id,amount:100});await consoleView.getByRole('button',{name:'Fire Rapid Laser',exact:true}).waitFor();await pc.waitForTimeout(1000);
  await pc.screenshot({path:path.join(artifacts,'console-1366.png')});
  const before=(await state()).starships[1].currentHullHp;
  await consoleView.getByRole('button',{name:'Fire Rapid Laser',exact:true}).click();
  const roll=pc.getByRole('dialog',{name:'Ship action dice roll'});await roll.waitFor();let pending=(await state()).units[0].delayedAction;assert.ok(pending.weaponOrder);assert.equal(pending.remaining,100);await act({action:'step'});assert.equal((await state()).units[0].delayedAction.remaining,100);assert.equal((await state()).starships[1].currentHullHp,before);
  await post('action',{roomCode:code,characterId:'wrong',characterToken:playerToken,action:'weaponCommand',id:unit.id,sicId:'gun',targetId:ships[1].id,requestId:'unauthorized-laser'},403);
  const skill=roll.frameLocator('iframe');await skill.getByRole('button',{name:'Roll for Me',exact:true}).click();await pc.waitForTimeout(900);assert.ok(await skill.locator('#diceCanvas canvas').count());await pc.screenshot({path:path.join(artifacts,'laser-dice.png')});await skill.getByRole('button',{name:'Confirm and Submit',exact:true}).click();await roll.waitFor({state:'detached'});
  assert.equal((await state()).units[0].delayedAction.remaining,100);assert.equal((await state()).starships[1].currentHullHp,before);
  for(let n=0;n<20&&(await state()).units[0].delayedAction;n++)await act({action:'step'});
  const done=await state();assert.ok(done.starships[1].currentHullHp<before,'Damage applied on input completion');assert.ok(done.starships[0].weaponState.reports[0].hit);await consoleView.locator('[data-reports]').filter({hasText:'HIT'}).waitFor();
  await pc.waitForTimeout(250);assert.ok(await pc.evaluate(()=>laserAnimations.some(a=>a.options.duration===650&&a.frames.some(f=>f.fill==='#ff3048'))),'Red impact animation rendered');assert.ok(await pc.evaluate(()=>laserAnimations.some(a=>a.options.duration===300)),'Laser beam rendered');
  await pc.screenshot({path:path.join(artifacts,'laser-result.png')});await pc.setViewportSize({width:1920,height:1080});await pc.waitForTimeout(300);await pc.screenshot({path:path.join(artifacts,'console-1920.png')});await pc.setViewportSize({width:390,height:844});await pc.waitForTimeout(300);await pc.screenshot({path:path.join(artifacts,'console-mobile.png')});
  assert.equal(await gm.locator('.weapon-console').count(),0);assert.deepEqual(errors,[]);
  const shop=await context.newPage();await shop.goto(base+'/starship.html');await shop.getByRole('button',{name:'SICs',exact:true}).click();await shop.locator('[data-sic-card="rapid-laser-1"]').scrollIntoViewIfNeeded();await shop.locator('[data-sic-card="rapid-laser-1"] img').evaluate(img=>img.decode());await shop.screenshot({path:path.join(artifacts,'laser-card.png')});assert.ok(await shop.locator('[data-purchase-sic="rapid-laser-1"]').isVisible());
  console.log('PASS: laser card, GM/PC access, shared dice, frozen roll/input, atomic damage, responsive weapons console. '+base);
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();if(child){const exited=new Promise(r=>child.once('exit',r));child.kill();await exited;}});
